### PR TITLE
lighthouse justice dept

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- put justice department in maints right of sec
- make old lawyer room into a trial evidence room so you can just pull evidence out epic style
- add screen to evac so you can see the eta
- sec animal spawner

### CODE REVIEW

**Comment by Timemaster99** [comment]
maints law firm is unmatched

**Comment by deltanedas** [comment]
yeah im facing execution for murder but have you seen my lawyer? i met him in maints hes gotta be good

**Comment by therealDLondon** [comment]
Where prosecutor

**Comment by deltanedas** [comment]
forgor :trollface:

**Comment by therealDLondon** [comment]
HOW

**Comment by Timemaster99** [comment]
Gavel block mapped somewhere?

**Comment by Timemaster99** [comment]
> Gavel block mapped somewhere?

Same question for Court desk timer

**Comment by deltanedas** [comment]
no and no :trollface:

**Comment by deltanedas** [comment]
prosecutor spawns added to the justice room, court stuff in court

**Comment by IamVelcroboy** [comment]
* Maints Justice is kinda whack, maybe short term, but long term lets find a proper place for them
* Lawyer needs an office that is separated far enough from Prosecutor that conversations cannot be overheard
* Chief Justice should spawn in bridge conference room with the rest of the heads
* Fire/air Alarms?
* I wonder if it makes more sense to put CJ/Prosecutor where Detective and evidence room are and move detective to the maints office with the lawyer? 
image (Just a suggestion)
* Keep 2 lawyer slots open
* If you do keep the evidence room, these should probably be Justice locked? 
image
* (random) tile missing here 
image
* Another option might be to move EVA but I don't have a suggestion where 🤷‍♂️

**Comment by deltanedas** [comment]
> long term lets find a proper place for them

ideally it would be right of court but then half the map has to get remade

i think ill do your suggestion of swapping det and cj/prosecutor

**Comment by deltanedas** [comment]
prosector/cj remodeled in here


lawyer/detective cave

**Comment by therealDLondon** [comment]
The clerk :skull:

**Comment by Timemaster99** [comment]
> prosector/cj remodeled in here 
> 
> lawyer/detective cave 

If you do want to take it out of maints as Velcro suggested, I would suggest turning the maints hallway into a normal hall and just make it two tiles wide by cutting into EVA if needed

**Comment by IamVelcroboy** [comment]
Funny error says station doesn't exist

**Comment by deltanedas** [comment]
nothing weird about barriers probably a heisenbug

**Comment by IamVelcroboy** [comment]
image

**Comment by Timemaster99** [comment]
Make sure to add the new Clerk doors, or the Clerk windoor in this case

**Comment by deltanedas** [comment]
> Make sure to add the new Clerk doors, or the Clerk windoor in this case

yes i did that 5 h ago

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
