### PR TITLE
Edge Rebuild Phase 4, The Final Phase

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
- Made arrivals service into a Vox Box
- Changed decals around singulo
- ENTIRELY rebuilds security (wow!)
- Extends evac, adds starbucks
- Adds silvia to CMO's room, puts runtime in Epi (removes Willow)
- Removes the hotwired singulo HV wires
- Tweaks wires and lights station-wide
- Names all departmental doors, external and maints doors are unnamed
- Extends botany, gives them a pet cat 🐈 
- Tweaks to botany and kitchen
- Adds a few extra nitrogen closets for our vox friends
- Insults the warden
- Minor tweaks to sign and poster placement station-wide
- Tweaks spawnpoints for most jobs

## Why / Balance
Why not?

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Fox
- add: Edge Station has finished being refit, new sec, new evac, and a vox-safe service area!

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Haha, it's failing like every possible test. (Not your fault)

**Comment by deltanedas** [comment]
the spawn troll will be fixed in a bit but this should be failing the rsi test :trollface:

**Comment by IamVelcroboy** [comment]
Search map for invalids

**Comment by therealDLondon** [comment]
The invalids have been taken out back and shot @IamVelcroboy

**Comment by IamVelcroboy** [comment]
Make the casing consistent here and is unknown an important fax? or a random maint fax?
image
Open/close the crate
image
Public view of the RPG is hilarious
image
These aren't going to be accessible from this side but that's not your fault. These should get fixed.
image
Give HoS some privacy shutters. (and pray they don't practice with lasers 😄)
image
Again, check the casing (can easily edit these in the file directly)
image
Centcom gear is on the blacklist....Though, I'll admit it's rather protected...I'll allow it for now. Maybe removed in the future, maybe
image
2 libraries
image
Justice/Clerk overlap too much
image
Add a beacon here for "Nitrogen Safe Area" or something. Don't call it a Vox Box though
image
Just put one beacon right in the middle here
image


More...

**Comment by IamVelcroboy** [comment]
Completely optional but we have pretty good produce, meat, and ingredient spawners that could be used here for some RNG.
image
Hide this scrubber under a machine or something. Colin will eat your soul
image
Need scrubbers here
image
Unnamed SMES 
image
Capitalize Office for consistency
image
Run colorpipes again
image

**Review by IamVelcroboy — APPROVED** [review]
Going to merge since nothing is mechanically broken(that I could find) Make the changes above when you can.

**Comment by IamVelcroboy** [comment]
Oh, found the Unknown, It's in the AI sat 
image

**Pull request merged**
