### PR TITLE
Senior loadouts require whitelist

### PR DESCRIPTION
**Pull request by Axionyxx**
## About the PR
Approved by Fox in admin chat

### CODE REVIEW

**Comment by therealDLondon** [comment]
Approved by Fox in admin chat. Approved by Fox in GitHub

**Comment by ProphetCrow** [comment]
Wouldnt it be easier to reenable the senior roles, then whitelist that role like every other whitelisted role?

**Comment by WarMechanic** [comment]
> Wouldnt it be easier to reenable the senior roles, then whitelist that role like every other whitelisted role?

see https://github.com/DeltaV-Station/Delta-v/pull/1198 for why it isn't easier

**Comment by DangerRevolution** [comment]
> Approved by Fox in admin chat


image

**Comment by Axionyxx** [comment]
> > Approved by Fox in admin chat
> 
> image

You do realize I'm only making this a pr so it has tests ran, right? I would've directly merged this into master if it wasn't bad practice

**Comment by DangerRevolution** [comment]
still a PR :)

**Pull request merged**
