### PR TITLE
Theatre: Medieval

### PR DESCRIPTION
**Pull request by DangerRevolution**
## About the PR

TODO: Write this section, I'm opening this PR primarily because running the tests on my laptop takes me too long and it's faster using Github.

I'm also looking for more ideas, and maybe a little help doing all these sprites as I'm *not* an artist <3

Actual TODO list:

- [X] Tree Prop
- [X] Tree Variant
- [X] Castle Prop
- [X] Castle Variant
- [X] House Prop
- [X] House Variant
- [x] King Clothing
- [ ] Queen Clothing
- [ ] Prince Clothing
- [ ] Princess Clothing
- [ ] Knight Armour 1
- [ ] Knight Armour 2
- [ ] Royal Clothing 1
- [ ] Royal Clothing 2
- [ ] Peasant Clothing 1
- [ ] Localisation

## Why / Balance

Roleplay

## Media

TODO:
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added Medieval-themed props for theatre shows

### CODE REVIEW

**Comment by angelofallars** [comment]
Hi @DangerRevolution, since this pull request is still WIP, you can turn this into a [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) so it's clear that this PR is still in progress, not yet ready for review. IIRC the tests should still work even if this is a draft.

**Comment by DangerRevolution** [comment]
> Hi @DangerRevolution, since this pull request is still WIP, you can turn this into a [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) so it's clear that this PR is still in progress, not yet ready for review. IIRC the tests should still work even if this is a draft.

Tests don't work on drafts (unless changed recently), but I will draft it when I don't need the tests ran :)

**Comment by DangerRevolution** [comment]
12 commits later, finally fixed test fails. 🙏 🙏 🙏

**Comment by IamVelcroboy** [comment]
> Tests don't work on drafts (unless changed recently), but I will draft it when I don't need the tests ran :)

You can run tests locally. It's actually WAY faster. Too busy today but I can show you tomorrow or ask someone in Discord. It's not difficult.

**Comment by DangerRevolution** [comment]
> > Tests don't work on drafts (unless changed recently), but I will draft it when I don't need the tests ran :)
> 
> You can run tests locally. It's actually WAY faster. Too busy today but I can show you tomorrow or ask someone in Discord. It's not difficult.

I find it slower on my laptop than Github and running tests forces me to stop what I'm doing to run the test :(

**Comment by rosieposieeee** [comment]
minor suggestion for your sprites, maybe make the top rim have that corrugated cardboard inside

image

helps put it in perspective a little more as well

**Comment by DangerRevolution** [comment]
> minor suggestion for your sprites, maybe make the top rim have that corrugated cardboard inside
> 
> image
> 
> helps put it in perspective a little more as well

I was really confused until I saw you edited the sprite lmao, umm, I'm not completely sure I understand so I sent you message on Discord :O

**Comment by DangerRevolution** [comment]
finally got myself together and sprited this chonker: 
image

(still WIP)

**Comment by Samsterious** [comment]
Godfrey, et al, will be pleased. Looking forward to seeing the finished product!

**Comment by DangerRevolution** [comment]
> Godfrey, et al, will be pleased. Looking forward to seeing the finished product!

Sorry to disappoint.

**Comment by TadJohnson00** [comment]
All good, thanks for letting us know.

**Pull request closed without merging**
