### PR TITLE
Submarine Patches 2/10

### PR DESCRIPTION
**Pull request by rosieposieeee**
image

Content Client_dTF8IjYecY

Content Client_TyBeCfP7Io

- moved bar & arcade to food court
- retooled west wing of hospital; its shorter now, has a borg charger room, and a proper viro room
- swapped reception and made it a little smaller
- added a door between chems counter and hall between ICU & exam rooms
- removed the north ICU door
- ICU now has a windoor'd chem storage in the center
- ICU now has directional windows preventing doctors from moving all the beds into an unhygienic and unsafe pile in the center.
- ICU & cryo room were combined into one
- added central hospital substation to ease up on power issues
- gave corpsman a little more gear, moved their office to sec, previous office is now just a perma mini-med room
- fixed atmos markers in gas area
- fixed some misc emergency lights, lowered overall emergency light amount in maints
- removed barbershop, laundry made smaller and slid over a bit
- epi no longer has terrible labyrinth maints
- SIX SMES's. power problems better be fixed or im eating my hat
- removed labyrinth because it was sucks. now there is a cave guy who is much better; far easier to navigate, filled with crystal caves and a handful of lakes. also has some more dilapidated stuff similar to the zombie lab, such as a xeno lab, a rusty old prison, and an enhanced black market
- security checkpoint added near arrivals
- engi outpost added near arrivals
- binguswalter room added
- ai core room added
- made all maints lockers be wall mounted because i hate the regular ones
- removed the diagonals in any walk-into-able areas. i hate that those can't handle atmos
- made the robo room in epi more space-efficient
- added more jani lights, named jani light buttons
- fixed all buttons not being directional, so now medical is no longer all-access for everyone who knows how to press a button through a wall
- a number of substations are now very pretty
- moved detective out of sec, next to the journalist
- added martial artist, slightly tweaked job slots
- added custom luxury submarine-y escape pods
- added custom submarine-y evac shuttle, NTES Propeller
- armory & warden's office swapped positions; sec now has direct access into the south end of perma; armory now takes longer than 10 seconds to breach for nukies.
- court was made a little smaller so now everyone can see everyone else seated.
- moved comms to the zoo so you can't 1-2-3 the armory, bridge, and comms as a nukie just walking straight in from evac
- moved the singulo to the east side, entrance from the park
- disposals now leads to space; be careful! janitors have been given some EVA suits to compensate.
- everywhere that has suit storages now has them in cooler-looking 'secure' storage
- second sec checkpoint added near evac, mirroring the arrivals one
- psych ward now has a central panopticon
- dilapidated flesh lab added where the previous singulo was as a fun thing for salvage to do now that the labyrinth is gone
- engineering now has a real counter like the other departments
- camera routers were consolidated into one room
- blue lights added to all external/docking areas to match evac
- every area of space locked inside the station now has external access, more external access points dotted around too
- added more signage from my signage PR
- added button frames everywhere
- added lockable buttons wherever reasonable, mostly sec
- church is now prettier
- submarine station has a symbol; the yellow-orange plus!
- added grey stalagmites (but got distracted halfway through and didn't finish...)
- used new fancy curtains and tables when appropriate
- one billion other tiny changes & fixes

**Changelog**
:cl:
- tweak: Submarine has received another batch of design tweaks and revisions. The deepest recesses of the station are shifting...

### CODE REVIEW

**Comment by deltanedas** [comment]
the power problems is from med running off of 1 55kw apc give it like 6, from experience that makes all flickering go away

**Comment by DebugOk** [comment]
The test fail seems legit, and might be related to me accidentically reverting your entire signage pr when your upstream version didn't include SignDirectionalICU. I'll have to check this later, if that is the case, I'll make a fix for it

**Comment by rosieposieeee** [comment]
> The test fail seems legit, and might be related to me accidentically reverting your entire signage pr when your upstream version didn't include SignDirectionalICU. I'll have to check this later, if that is the case, I'll make a fix for it

oh shit did i forget the ICU sign upstream. oh fuck

**Comment by rosieposieeee** [comment]
oh okay, i didnt, i just changed the ID from ICU to Icu for some reason that will forever be lost to time because i dont remember. i fixed it already so its fine

**Comment by DebugOk** [comment]
> > The test fail seems legit, and might be related to me accidentically reverting your entire signage pr when your upstream version didn't include SignDirectionalICU. I'll have to check this later, if that is the case, I'll make a fix for it
> 
> oh shit did i forget the ICU sign upstream. oh fuck

Pull master, https://github.com/DeltaV-Station/Delta-v/commit/717e81c255e8f0f07148530b1574ecf1be1336a8

**Review by IamVelcroboy — APPROVED** [review]
Fuck it. Let's see what happens

**Pull request merged**
