### PR TITLE
A Ninja Adjustment

### PR DESCRIPTION
**Pull request by Avalon-Proto**
## About the PR
Ninjas have always had trouble dealing with psionics, so, they are now insulated. Also their gloves are now slightly better than standard thieving gloves at stealing, as it can make interesting scenarios allowing them to cloak and steal

## Why / Balance
Everyone and their mother with mass sleep likes to valid hunt, so lets remove their option to ninja hunt. And thieving gloves so that ninjas can pull more interesting shenanigans

## Technical details
Changed a number and added a component
## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

🆑 
 - Tweak: Ninja helmets have been imbued with anti psionic sigils, and they are sneakier than ever with the ability to steal silently

### CODE REVIEW

**Comment by Radezolid** [comment]
Question, as far as i know tin foil hats combust once after someone tries to use powers on the person. Would the ninja's helmet combust too?

**Comment by Avalon-Proto** [comment]
I am honestly not sure! I couldnt find the comp to modify it anywhere

**Comment by Stop-Signs** [comment]
Ninja is already really powerful, so i dont necessarily agree with yet another buff, i understand that mass sleep validhunting exists but if sec is getting tortured by a stun and steal gun ninja it might be worth it to have those people.

**Comment by Avalon-Proto** [comment]
While true, also consider this- secoff in pairs will destroy a ninja if they are out to kill since the stun has a cool down and ninja has 0 armor. This is just to stop those solo players from getting a free kill by sleeping the ninja or mind swapping them etc

**Comment by Lyndomen** [comment]
Idk it seems to me like the problem here is with those psionics, not with the ninja

**Comment by Avalon-Proto** [comment]
I mean, just seems like an easier solution to protect the ninja from psionics rather than try and mess with psychic code

**Comment by Lyndomen** [comment]
At some point tho this problem exists for every solo antagonist. If it's a problem, it is much better to address it at the root rather than give every solo antag free insulation.

**Comment by Avalon-Proto** [comment]
What do you suggest instead then? Id rather not take away the possible tools for antags or sec to get useful psionics like sleep or zap, since both can be used to help with goals and the like

**Comment by Lyndomen** [comment]
> What do you suggest instead then? Id rather not take away the possible tools for antags or sec to get useful psionics like sleep or zap, since both can be used to help with goals and the like

I guess I don't see it as an issue myself. If security is using it, okay fair game. Ninja also has a one button stunlock, and could steal psionic insulation if they really want. If crew does it, they get bwoinked for validhunting, if it's applicable.

**Comment by Radezolid** [comment]
I'm against this, as a ninja enjoyer, they are already absolutely broken having to fear psionics is cool but I do agree on the no counter play and window for valid hunting it gives. This does look like a community issue rather than mechanical.
Edit: My suggestion (WYCI) is making psionic powers be at least a small do after, let people react.

**Review by deltanedas — CHANGES_REQUESTED** [review]
even nukies can get mass slept, doesnt make sense that ninja of all antags gets immunity

and would need psionic insulation refactor anyway so ninja helmet doesnt burn up at high glimmer

**Comment by Avalon-Proto** [comment]
Yeah just closing this one tbh I need tah figure it out

**Pull request closed without merging**
