### PR TITLE
Randomized Listening Outpost Spawning

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR
I have changed the listening outpost so that instead of FTL'ing to the station from null space, it instead spawns at a random location roughly 1 to 1.5 kilometers away, and at a random angle. 

## Why / Balance
This is the originally intended spawning system, but neither me nor DangerRevolution had yet worked out how to manage it. 

## Technical details
This code is very much shit and kind of rough, and it uses a deprecated function. It should probably be slightly rewritten to use the newer TryLoad system instead of LoadGrid. It also needs to be double checked for unnecessary "Using" statements, since I basically took the list from PirateSpawnRule while making this. Also it is shamelessly using code from said PirateSpawnRule

## Media
image

**Changelog**
:cl: VMSolidus and DangerRevolution
- tweak: The Listening Outpost now spawns a random large distance from the station, instead of null space.

### CODE REVIEW

**Comment by deltanedas** [comment]
wont it be visible on mass scanners

**Comment by VMSolidus** [comment]
> wont it be visible on mass scanners

Yes, and that's next on my list. I want to deprecate the IFF console and make it so that it instead shows up on the console missing a name entirely, and appearing as if its an asteroid.

**Comment by deltanedas** [comment]
asteroids dont exist and dont do that so it will be metad outright or "hmm whats this unmarked object lets send out 5 suited up sec and the salv squad to investigate"

**Comment by IamVelcroboy** [comment]
> asteroids dont exist and dont do that so it will be metad outright or "hmm whats this unmarked object lets send out 5 suited up sec and the salv squad to investigate"

That why we're going to start spawning in decoy asteroids and more random stuff as well.

**Comment by DangerRevolution** [comment]
> asteroids dont exist and dont do that so it will be metad outright or "hmm whats this unmarked object lets send out 5 suited up sec and the salv squad to investigate"

intended goal of this is in #539; spawning a lot more in-map stuff for Salvage to encounter like this

>lets send out 5 suited up sec and Salv squad to investigate

You'd actually be surprised that it's been raided officially only once so far, and it's within 300 meters of the station

**Comment by VMSolidus** [comment]
While looking into the IFF code and doing some experiments, I've concluded that it's not actually possible to have a grid like this spawn in with the IFFComponent, despite being able to simply shove it into the .yml file without issue. Instead I'm going to need to make a variant clone of the IFF Console that does the whole "Spoof an Asteroid" thing by default.

**Comment by VMSolidus** [comment]
I'm closing this PR since it's being merged with PR639

**Pull request closed without merging**
