### PR TITLE
Add borg censorship filter

### PR DESCRIPTION
**Pull request by SolStar2**
## About the PR
Added a censored accent to NT borgs that replaces various swears with [CENSORED]. Along with not coming on Syndicate borgs
emagging and sometimes ion-stroms will remove the accent.
## Why / Balance
I find it fitting to have NT borgs censor less friendly language and can add to funny moments. Having emags interact with the filter may indicate the status of a borg though not very reliably as they can also lose it randomly in an ion-strom.

## Technical details
Added censored accent components and systems following the style of other delta v accents. The censored accent translates various swears into [CENSORED]. Added the censored accent to the BaseBorgChassisNT. I subscribed borg_system.cs to OnGotEmagged to give the effect of losing its accent on emagging. The logic for accepting OnAttemptEmag is still handled in the SharedSiliconLawSystem.cs. No duplicate emag charges are used. Added a RemoveAccentChance variable to the IonStromTargetComponent of 0.2 checks for if ion storm removes a given borgs censored accent along with the checks for law changes in IonStormRule.cs.

## Media
image 
image
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
 - added a new field to IonStromTargetComponent "RemoveAccentChance". Anything iterating over that component will need to be able to handle the new case

**Changelog**
:cl:
- add: NanoTrasen borgs now have swear filters.
- tweak: Emagged and some Ion-stormed borgs will lose their swear filter.

### CODE REVIEW

**Comment by deltanedas** [comment]
"law 2 say fuck" new emag check

**Comment by therealDLondon** [comment]
Im personally a fan of Borgs being able to swear. They have the rights to!

**Comment by SolStar2** [comment]
> "law 2 say fuck" new emag check

They can still lie about being compromised how well they do it is up to how the borg is played.

**Comment by deltanedas** [comment]
it will just devolve to metaknowledge of which swears are on the list and then someone checking what a borg said against it

**Comment by SolStar2** [comment]
> it will just devolve to metaknowledge of which swears are on the list and then someone checking what a borg said against it

I have a bit of faith in the community that its not going to be abused like that. Besides, there isn't really any reason to think they were emagged over an ion storm so there isn't much you can do if you do catch a borg swearing.

**Comment by SolStar2** [comment]
If I added a toggle in the borg's maintenance panel would that alleviate yall's objections? @therealDLondon @deltanedas

**Pull request closed without merging**
