### PR TITLE
Add access wire to airlocks

### PR DESCRIPTION
**Pull request by JustTNE**
## About the PR

Re-added access wires to airlocks

## Why / Balance

They were not re-added since rebase and are a very nice to have feature.

## Technical details

This is only a yaml change since upstream has all the code this used to use already included.

**Changelog**

:cl:
- add: Airlocks now have access wires

### CODE REVIEW

**Comment by Carolyn3114** [comment]
This makes hacking easier which is kinda lame

**Comment by JustTNE** [comment]
This kind of implies that hacking is supposed to be difficult in the first place, which it's not. This is just how it was on pre-rebase delta-v, and I've personally made good use of that in some role play scenarios before as well as allowing maintenance drones to link things to doors they don't have access to for example.

**Comment by Carolyn3114** [comment]
considering how insuls are supposed to be rare, and that wires were randomized because of this change *on nyanotrasen and delta v*, I'd say access wire is poopy

**Comment by JustTNE** [comment]
The wires are still randomized on delta-v, that hasn't changed.

**Comment by DebugOk** [comment]
At this time, I do not believe adding back access wires will be beneficial in any way. Doors can still be hacked open with ease, assuming you have a multitool and insulated gloves.

**Pull request closed without merging**
