### PR TITLE
Shoukou from Nyanotrasen.

### PR DESCRIPTION
**Pull request by Adrian16199**
Adds Shoko to the rebase.

TO-DO: Ensure that everything is actualy in order in the uh... (reads paper) 79.... thousand lines of yml. Make it work.

## About the PR

Adds Shoukou from nyanotrasen, made by Colin_tel.
It has been redone to fit the current departments. The changes include:
Middle of security has been redone, expandin it in cost of the maintenance.
Lawyers office has been moved to the medical outpost and instead, now corpsman's medbay now resides there in lawyer's place.
Atmos has been expanded at the cost of salvage, adding a TEG. Salvage has been also deleted with an additional cost of maintenance to present robotics subdepartment.
Bridge's meeting room has been redone to fit all 7 heads.
Cargo has been expanded for it to become logististics department, in cost of emergency pods that have been moved to the evacuation area.
Engineering's has been readjusted by deletin their robotics due to science now having that proffesion and CE's office has been expanded.
## Why / Balance

Because shoko is cool

## Technical details

Brings back the old map with new changes.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Shoukou from Nyanotrasen and hopefully improved it.

### CODE REVIEW

**Review by DebugOk — COMMENTED** [review]
Shoko should be added to the map tests aswell

**Comment by Adrian16199** [comment]
uh... **yes**

> Shoko should be added to the map tests aswell

**Comment by Colin-Tel** [comment]
Generally speaking, you just have to move salvage and make logistics bigger by expanding south and taking up the space where the evac pods are. 
You *could* make the security outpost into a detective office if you wanted, or just *don't* have a detective. 
Robotics is also over in engineering so that needs to change.

**Comment by Colin-Tel** [comment]
First of all there's a valid test failure.

image
This looks unfinished.

image
1. don't give logistics a protolathe
2. this is a command room secured by regular window and wall
3. there are vents/scrubbers on top of the carpet
4. get rid of the ripley stuff
5. the APC is blocked by the door

image
Please don't do this. You have HV cable passing through double thickness reinforced wall.

image
1. There are vents/scrubbers on top of carpet. Why is there carpet in an EVA storage room anyways?
2. the asymmetry that the gas tank dispenser brings to the suit storage units gives me conniptions
3. These airlocks are EVA locked. I don't know if that's a problem but it's unprecedented.
4. Speaking of unprecedented, I've never seen an APC on a window before.

image
1. There is no exosuit fabricator unless I'm missing it
2. There is no cyborg recharging station unless I'm missing it
3. Epi doesn't need an autolathe on our maps, let alone a second one in robotics. Just put down a blue toolbox or tool closet instead
4. Drones aren't really an epi thing, they're moreso engineering.
5. you should put down an operating table somewhere where they can "operate" (i.e. beat them to the point of gibbing) on their patients.

image
1. turn the camera monitor into a wireless camera monitor
2. the DetDrobe is in the way and would be better up against the north wall or something

image
1. You should extend this maintenance shaft to end at the north wall of the detective's office, and get rid of all the windows into the maintenance shaft.
2. lawyer's office has vents over carpet
3. lawyer's office should have a maintenance access so he doesn't die if there's a gas leak in his room and the firelock closes.

image
1. There's a service intercom in this room.
2. this wall locker makes no sense because it will automatically pick up anything on the rack

image

This is cushy and I like it, but please thin the wall between security and perma; it doesn't need to be double thick.

image

Ain't no damn way this is gonna work.

**Comment by Adrian16199** [comment]
I believe I have done everything that was requested.
(hopefully)

**Comment by Colin-Tel** [comment]
image
👀

**Comment by Colin-Tel** [comment]
I've made *some* adjustments to the map so that some of the changes you've made would be more to my liking. However it should be stated that some of what you've changed has evident relics from how the map was prior to changes, which gets me concerned that there may be more subtle relics that end up causing hard-to-detect problems later.

Some things that were changed I greatly disagree with.

image

Why is there a table there? What's with the random pipes above the CO2 chamber? Even if the right side of the table had a pipe to connect the CO2 chamber to the recycler, would the recycler loop even work without a pump? What's the point of the external airlocks behind the CO2 chamber? Why is one of the external airlocks sealing a corner of the hallway? Why does the HV power cable on the north side go through a wall when it could just move a couple tiles to the left and use the door?

I don't want to record a long list of my gripes with the changes you've made, but some of them seem so obvious to me that it greatly worries me that people will end up playing the map and say the same things I'm saying, and then it'll come back to me. At the end of the day, I don't feel comfortable with someone mapping so sloppily on one of my maps, only for me to uncover a deluge of issues with it.

I've pushed some changes to the map, but this project is **certainly** not finished and it will require polish and testing before I am willing to give my OK on it.

**Comment by DebugOk** [comment]
Converting to draft based on Colin's feedback

**Comment by Adrian16199** [comment]
I guess, i just dont get the comment of putting the table there if it was you that did it. Why would I map a table in atmos?

**Comment by Colin-Tel** [comment]
image
Remember that you have to set up the name of the fax, or it displays as "Unknown"

**Comment by Colin-Tel** [comment]
Corrected corpsman fax name
EOD training room now has a crate of training bombs and a yellow toolbox
Removed mcgriff (haha loser dog)
thinned out the other part of perma that borders sec main
replaced old basic generator in south sec substation room with the new one and a fuel tank (no smoking in there!)
perma disposals escapees now have to fight through a small layer of grilles to delay their escape
gave perma a sec intercom
added mass scanner
redid warp points, added bombing objectives, added beacons
colored the pipes to the TEG where they were otherwise white
ran the `variantize` and `fixgridatmos` commands

**Review by Colin-Tel — DISMISSED** [review]
すばらしい、このステーションは大好きだ！

**Comment by Adrian16199** [comment]
> image Remember that you have to set up the name of the fax, or it displays as "Unknown"

Oooooooooh, I had no idea how to name them so i prefered not to touch em, didnt knew it was suppose to be in variables.

**Review by Colin-Tel — DISMISSED** [review]
(still good)

**Comment by Colin-Tel** [comment]
image

**Review by DebugOk — DISMISSED** [review]
> image

I would still like a Velcro review if possible, even if it's nog very detailed. Either that or a proper list of changes

**Comment by IamVelcroboy** [comment]
> I would still like a Velcro review if possible, even if it's nog very detailed. Either that or a proper list of changes

Yeah, fwiw, I think all map PRs should have a list of changes in the description, including simple ones (fixed missing LV, etc). Look at my PRs for example.

**Comment by DebugOk** [comment]
> > I would still like a Velcro review if possible, even if it's nog very detailed. Either that or a proper list of changes
> 
> Yeah, fwiw, I think all map PRs should have a list of changes in the description, including simple ones (fixed missing LV, etc). Look at my PRs for example.

Mapping guidelines, when you pr it :blunt:

**Comment by Adrian16199** [comment]
I DID NO SUCH THING GITHUB, STOP LYING, I WOULD NEVER DISMISS >:(

**Comment by IamVelcroboy** [comment]
This is ready to go

**Comment by IamVelcroboy** [comment]
Hey, since this is still open, maybe you could sneak in one more update and name the SMESs and substations.

**Comment by Adrian16199** [comment]
> Hey, since this is still open, maybe you could sneak in one more update and name the SMESs and substations.

Oh uh, If i wont frick it up, I can attempt.

**Comment by IamVelcroboy** [comment]
It's simple, just **view variables**. Make sure you're on **Server Variables**, edit the name and hit **Enter**

**Comment by Adrian16199** [comment]
> Hey, since this is still open, maybe you could sneak in one more update and name the SMESs and substations.

On another note, Why name the SMES's? I get substations with engineering, service etc. But smes's?

**Comment by DebugOk** [comment]
> > Hey, since this is still open, maybe you could sneak in one more update and name the SMESs and substations.
> 
> On another note, Why name the SMES's? I get substations with engineering, service etc. But smes's?

They appear in the power monitoring console

**Comment by Adrian16199** [comment]
I believe I have updated it correctly, adjusted bit of cables since i noticed that 2 substations were connected to eachother via MV cable.

**Comment by IamVelcroboy** [comment]
I would say you don't need the possessive " 's " but I'm not going to nitpick on it. Looks good. 👍

**Comment by Adrian16199** [comment]
> I would say you don't need the possessive " 's " but I'm not going to nitpick on it. Looks good. 👍

I looked at them without it and my initial though: This will haunt me till the rest of my days.

**Comment by IamVelcroboy** [comment]
Fair enough

**Comment by Colin-Tel** [comment]
Velcro says it's ready, so I'm ready for it when Debug re-reviews.

**Comment by Adrian16199** [comment]
So uh, I will just say that the shoukou is ready for review, from my understandin debug has to review it so uh, Im just puttin out there if a certain individual were to see this, dont really want to be pinging or bother but uh, yeah. Would be very cool.

**Comment by IamVelcroboy** [comment]
I thought I already said it but I do approve this update.

**Comment by IamVelcroboy** [comment]
Am I understanding this is just waiting on Colin now? Or do I still need to do something?

**Comment by Colin-Tel** [comment]
> Am I understanding this is just waiting on Colin now? Or do I still need to do something?

Nope, was just waiting for Debug to dismiss the "changes requested"

**Pull request merged**
