### PR TITLE
Change Secret Weights

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
Adjusted secret weights. Less survival, more of everything else. No, revs aren't back. Sorry. 

## Why / Balance
More antagonists, more action, more contention. 

## Technical details
Yaml warrior reporting all clear

## Media

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Hope not. Probably not.

**Changelog**
- tweak: Secret Weights adjusted!

### CODE REVIEW

**Review by Axionyxx — CHANGES_REQUESTED** [review]
These never had comments, and we shouldn't need to now. These values don't match whats upstream anyways. If you want to keep the comments, you'll have to make them actually match whats upstream

https://github.com/space-wizards/space-station-14/blob/master/Resources/Prototypes/secret_weights.yml#L4-L8

**Comment by deltanedas** [comment]
for the purpose of resolving conflicts it shouldnt matter, not like we use revs anyway so it wont match

**Comment by Axionyxx** [comment]
> for the purpose of resolving conflicts it shouldnt matter, not like we use revs anyway so it wont match

Thats why the comments should just be removed entirely lol

**Comment by Bonktrauma** [comment]
Ahoy me bucko

**Comment by Lyndomen** [comment]
I'm not sure how to say yes to a review, but I removed the comments that were extraneous!

**Review by Axionyxx — APPROVED** [review]

**Pull request merged**
