### PR TITLE
Cooking Guidebook

### PR DESCRIPTION
**Pull request by Venrixia**
## About the PR

This PR contains Guidebook pages for all the recipes , Recipe Groupings and Recipes sourced from Delta V Wiki 
## Why / Balance

Until now the ingame guidebook has lacked a comprehensive list of most available recipes , the current list being quite basic in comparison.  

Theoretically speaking , assuming chefs take advantage of the Moth Page that outlines Moth safe recipes , there should be an uptick in moth players feeling an illusion of greater speed , due to them not starving.

## Technical details

Current Guidebook recipe page was re-named and re-used as the Parent for all added pages . 

Added pages were added as children of the chef guide entry on line 37 of  `shiftandcrew.yml` file located at `Resources\Prototypes\Guidebook\shiftandcrew.yml`

A chef subfolder was added to the service folder inside the Guidebook Directory due to sheer number of page xmls. This is where all new files reside. 
`"/ServerInfo/Guidebook/Service/Chef/`

## Media

Below are a few pages previewed and the guide tree shown.
Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame

## Breaking changes

**Changelog**

:cl:
- add: All Cooking recipes related to the Chef from the wiki have been added to the ingame Guidebook. Happy Cooking.

### CODE REVIEW

**Review by deltanedas — CHANGES_REQUESTED** [review]
this should be autogenerated instead, i believe theres a pr upstream that was abandoned

**Comment by jimmy12or** [comment]
Whether it's ready or not, this is such a great thing to add, thank you for putting the effort into it.

**Comment by Venrixia** [comment]
> this should be autogenerated instead, i believe theres a pr upstream that was abandoned

Hey thanks for responding ! Just reaching out , because I'm unsure of what you want me to do further with this PR . I believe that you are referencing the below PR . To my understanding this would require a bit of code that Im unable to do, due to that fact of how the guidebook functions. The bartender Page works by using the [ GuideReagentGroupEmbed tag ](https://docs.spacestation14.com/en/general-development/tips/writing-guidebook-entries.html#guidereagentgroupembed) . This Tag allows you to embed all reagents of a group , listing their recipes . Foods are not reagents therefore I cant use it this way . 

https://github.com/space-wizards/space-station-14/pull/28716 .

**Comment by deltanedas** [comment]
was refering to https://github.com/space-wizards/space-station-14/pull/20978 which iirc enumerates microwave recipe prototypes

**Comment by Venrixia** [comment]
Well , looking over that PR , I have no technical ability to implement theirs . You can pull this one or wait til someone revives that one . the choice is up to you I suppose . 

- edit Closing as I dont have the C# skills to make it autogenerated.

**Pull request closed without merging**
