### PR TITLE
Buffed Harpy

### PR DESCRIPTION
**Pull request by DefinitelyNotFurryXD**
Now Harpy can mimic more instruments!

### CODE REVIEW

**Comment by Axionyxx** [comment]
Please follow the pull request format and reopen when you've done so

**Comment by DefinitelyNotFurryXD** [comment]
whats the pull request format?

**Comment by Axionyxx** [comment]
Its automatically filled in when opening an new pull request, but you can also find it [here](https://raw.githubusercontent.com/DeltaV-Station/Delta-v/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by DefinitelyNotFurryXD** [comment]
> Its automatically filled in when opening an new pull request, but you can also find it [here](https://raw.githubusercontent.com/DeltaV-Station/Delta-v/master/.github/PULL_REQUEST_TEMPLATE.md)

done
https://github.com/DeltaV-Station/Delta-v/pull/1217

**Pull request closed without merging**
