### PR TITLE
fugitives redux

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
old fugitives but better in every way
- spawning no longer has a "please metagame this antag" popup shown to everyone, only you see it
- it uses your loaded profiles appearance and a fake name so when okelte fugi everyone can mald
  also means non human fugis are real :trollface:
- because deltav is supposedly mrp, instead of a secoff arresting you not being able to give you any charges, now the report has a list of randomly generated crimes that you get to stand trial for during your Trial At CentComm :tm:
- internally reworked to not have as much shitcode
- swapped 1h civilian for 1h sec, just why

big change is fugi now has knockoff thief toolbox that gives you 1 small kit of your choosing
theres something for everyone

## Why / Balance
good

## Technical details
fugitives rule just handles the announcement/report logic everything else reuses existing components

new logic only sends the paper to comms consoles of the target station not centcom / some random shittle / etc

## Media

illegal

ignore it saying thief toolbox at the top its hardcoded :trollface:

all the gamer loot

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Fugitives can now be wanted by GALPOL, they might even be hiding in your very station!

### CODE REVIEW

**Comment by UnicornOnLSD** [comment]
your honor, based, merge this this instant

**Comment by deltanedas** [comment]
still a draft goober

**Comment by UnicornOnLSD** [comment]
merge the draft paper

Also what if someone who died IC picks it, then you got a dead body of X or Y with a copy on board.
Considering it does the same with loneop I guess it's whatever

**Comment by noctyrnal** [comment]
Might be cool to give them a small piece of contraband out of a field to make evasion a bit easier, like a smoke grenade or a scram implant

**Comment by deltanedas** [comment]
> Also what if someone who died IC picks it, then you got a dead body of X or Y with a copy on board.
Considering it does the same with loneop I guess it's whatever

right now if Okelte Valid goes cryo and then becomes a fugi she would be expected to either pretend she doesnt know anything (not allowed to remember past life lmao) or say shes a clone or that shes the real one and the dead one is the clone and its all part of big nanotrasens conspiracy that she got caught up in :trollface:

ideally AntagLoadProfileRule would be able to figure out if someone played as that character in the round before and then use random mob instead but wyci

**Comment by DangerRevolution** [comment]
How does loaded profile appearance work with the potential for your body to still be on board; and is using the profile even worth to begin with?

**Comment by deltanedas** [comment]
> is using the profile even worth to begin with?

people really like it for nukies and loneop, and its nice not having every fugitive always be a human

**Comment by DangerRevolution** [comment]
> > is using the profile even worth to begin with?
> 
>  its nice not having every fugitive always be a human

Did Nukies get refactored to use loaded profile? I remember the fuckery to get non-human Nukies to spawn. Is loaded profile the only solution rn to non-humans?

**Comment by deltanedas** [comment]
yes both nukie rules have used profiles for past month or two

**Comment by DangerRevolution** [comment]
> yes both nukie rules have used profiles for past month or two

that's not skibidi rizz :(

**Comment by UnicornOnLSD** [comment]
> > Also what if someone who died IC picks it, then you got a dead body of X or Y with a copy on board.
> > Considering it does the same with loneop I guess it's whatever
> 
> right now if Okelte Valid goes cryo and then becomes a fugi she would be expected to either pretend she doesnt know anything (not allowed to remember past life lmao) or say shes a clone or that shes the real one and the dead one is the clone and its all part of big nanotrasens conspiracy that she got caught up in :trollface:
> 
> ideally AntagLoadProfileRule would be able to figure out if someone played as that character in the round before and then use random mob instead but wyci

based, works for me

**Comment by Lyndomen** [comment]
So I've had good success running this event as an admeme, but security is much better at catching people than they used to be. I found that giving fugitives the choice between various implants and contraband worked well, with most opting for an EMP or freedom implant.  

It also made them a bit more obviously an free antagonist rather than greytider+. 

Overall, yay.

**Comment by deltanedas** [comment]
> I found that giving fugitives the choice between various implants and contraband worked well, with most opting for an EMP or freedom implant.

copy paste thief toolbox time :trollface:

**Comment by Lyndomen** [comment]
Here's a short list of what I have provided historically. This isn't a list of "only what's allowed" but rather just what's been done. I've also thrown in smoke grenade, EMP shit, whatever really. 

    No Slip Chameleon Shoes
    Grey Jumpsuit
    Insulated Gloves
    Passenger PDA
    Passenger Headset
    Backpack
    Full Toolbelt
    CHOICE between

    Scram Implant
    Acid Implant
    Freedom Implant

**Comment by Bonktrauma** [comment]
> Scram Implant
> Acid Implant
> Freedom Implant
> ```

I don't  think the acid implant is a good idea, the fugitive in the end is just a fugitive, why would they literally melt themselves alive just to not be caught

**Comment by Lyndomen** [comment]
> > Scram Implant
> > Acid Implant
> > Freedom Implant
> 
> I don't think the acid implant is a good idea, the fugitive in the end is just a fugitive, why would they literally melt themselves alive just to not be caught

It prevents security from just gunning them down if they are needed alive- and provides them some option to utilize their life as a bargaining tool.

**Comment by Bonktrauma** [comment]
> > > Scram Implant
> > > Acid Implant
> > > Freedom Implant
> > 
> > I don't think the acid implant is a good idea, the fugitive in the end is just a fugitive, why would they literally melt themselves alive just to not be caught
> 
> It prevents security from just gunning them down if they are needed alive- and provides them some option to utilize their life as a bargaining tool. 

But it also means the moment they get caught they can just kill themselves, honestly we need a acid Implant that you can't just activate

**Comment by Bonktrauma** [comment]
> > > > Scram Implant
> > > > Acid Implant
> > > > Freedom Implant
> > > 
> > > I don't think the acid implant is a good idea, the fugitive in the end is just a fugitive, why would they literally melt themselves alive just to not be caught
> > 
> > It prevents security from just gunning them down if they are needed alive- and provides them some option to utilize their life as a bargaining tool. 
> 
> But it also means the moment they get caught they can just kill themselves, honestly we need a acid Implant that you can't just activate

**Review by Axionyxx — APPROVED** [review]
I didn't spot anything terrible in my quick glance

**Comment by deltanedas** [comment]
free

**Pull request merged**
