### PR TITLE
Interdyne Shuttle Update

### PR DESCRIPTION
**Pull request by Unkn0wnGh0st333**
# **Closed per request of Foxmin on discord**

## About the PR
Alters the Synthesis Specialist Shuttle
Changes:
- Replaced Shuttle Console with Syndicate Shuttle Console
- Replaced ChemVender(emagged) with SyndieJuice(emagged)
- Added Long Range Syndicate Fax Machine named "Interdyne Synthesis"
- Added 10 pieces of paper and pen
- Replaced "tin can and water bottles" with Syndicate Lunch Boxes
- Replaced box of shotgun drums with shotgun shell dispenser
- Added Beanbag box for nonlethal option
- Replaced chair in lobby with Star-kist Vender(Emagged)
- Replaced chairs in the lobby with red comfy benches
- Added 2500 Spesos to Syndicate Crate (Encourage trading)
- Replaced Microwave Board with Donk Branded Mircowave Board in Chemical Locker
- Added Chemical Guidebook & Medical History Computer(useless) in the Lab
- Backroom completely reworked
- Bathroom added with syndicate soap
- Added second bed, curtains on beds, slippers for both, and finally a nukie plushie (Snoozing)
- Replaced P.A.C.M.A.N. Generator with a S.U.P.E.R.P.A.C.M.A.N. Generator (Reasoning will be in Why / Balancing)
- Added Button that bolts shuttles front doors (not docks)
- Added Emergency Fire Wall Locker
- Added Medical Wall Locker with Toxin Medkit (Poisoners need emergency anti-poison)
- Adjust thruster layout

## Why / Balance
Lets start with the backroom rework, the original backroom was cramp, sad, and couldn't even fit both specialist in the back. This is just overall nicer and gives them a better living environment for their long work trips!

Now the more important change:  P.A.C.M.A.N. Generator to a S.U.P.E.R.P.A.C.M.A.N. Generator

The P.A.C.M.A.N. Generator uses plasma sheets creating around 30kW for 16 minutes, the reason I changed it for the S.U.P.E.R.P.A.C.M.A.N. is because of two reasons. First being fuel time, this isn't a huge issue but more a luxury. The second is Plasma Sheets are hell to get compared to Uranium Sheets. Uranium is rarer yes but you have to realize, **several departments** inhale every plasma sheet that is blessed on this station. 90% of the time I have to resort to stealing other power sources from the station and feeling bad about it.

Uranium is easier, and still encourages the trading with station idea. 

## Media
before after
before after 2

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
yeag

**Changelog**
🆑 
- tweak: Interdyne Synthesis Shuttle has been revamped for the better! No more sad Specialist (hopefully)

### CODE REVIEW

**Comment by therealDLondon** [comment]
As the creator and owner of this shuttle I wish you wouldve asked me first

**Comment by Unkn0wnGh0st333** [comment]
> As the creator and owner of this shuttle I wish you wouldve asked me first

I'ma be fr I didn't even know it was DeltaV original, my bad og

**Comment by Avalon-Proto** [comment]
> Replaced ChemVender(emagged) with SyndieJuice(emagged)

Hey. Uh. The reason this was a chemvend and not a syndie juice was so that the syndie chemists could barter for restocks and use them. Now as it stands they can't restock their machine and are far more limited in terms of supplies

**Comment by Radezolid** [comment]
I disagree on the pacman change, uranium is harder to get by a lot, Logi can order plasma which you can barter to get, with uranium you have to get lucky that the salvagers aren't bad and actually do some mining.
Edit: Is that locker locked on the new version? Synth only has Syndicate access, no way to open that without breaking it,

**Comment by Lyndomen** [comment]
It was also on my list to make it more interdyne themed rather than syndicate themed, with the colors and whatnot

**Comment by Bonktrauma** [comment]
Yeah interdyne shouldn't be going too heavy into syndicate side of things with the public merchants

**Comment by Unkn0wnGh0st333** [comment]
> Yeah interdyne shouldn't be going too heavy into syndicate side of things with the public merchants

I personally disagree, I believe it should still have many Syndicate variants to it. Though I do agree with Fox and Lyndo with it having Interdyne colors and being seen as more a trader shuttle. Why I took down several posters I felt wasn't appropriate in exchange for others.

**Comment by Unkn0wnGh0st333** [comment]
> I disagree on the pacman change, uranium is harder to get by a lot, Logi can order plasma which you can barter to get, with uranium you have to get lucky that the salvagers aren't bad and actually do some mining. Edit: Is that locker locked on the new version? Synth only has Syndicate access, no way to open that without breaking it,

Nothing's locked of course, also I have at least 5 or so rounds done exactly that and never once have I gotten plasma from logi. They either just tell me no, go talk to epi, or it'll show up soon and then I'll never get it.

**Comment by Unkn0wnGh0st333** [comment]
> > Replaced ChemVender(emagged) with SyndieJuice(emagged)
> 
> Hey. Uh. The reason this was a chemvend and not a syndie juice was so that the syndie chemists could barter for restocks and use them. Now as it stands they can't restock their machine and are far more limited in terms of supplies

Would it be that hard of a PR to make them restockable :blunt:

**Comment by Radezolid** [comment]
> Would it be that hard of a PR to make them restockable :blunt:

https://github.com/DeltaV-Station/Delta-v/pull/2143

**Comment by perryprog** [comment]
Big fan of the generator change. I have played Interdyne I think twice (at least once) and both times actually getting plasma sheets was a _huge_ pain point. Even if you do get someone to come over with, say, logistics access, plasma is usually the first on the list to hand over to epistemics, and epistemics is 1) not likely to have free time to come do Interdyne RP, 2) not likely to hand over their precious, precious plasma. Uranium at least has a chance of being stockpiled by logistics, which is a department that is much more likely to head over to buy some stimulants (salv) or LSD (cargo techs).

Honestly, I also wonder if it's possible to just have one of both generators, so you can just barter for whatever's available. But yeah, getting fuel was definitely the most tedious and least-enjoyable part of playing Interdyne for me and why I haven't played it much at all since those two times.

**Comment by Avalon-Proto** [comment]
Hey, you know what would really give these guys a good bargaining chip

https://github.com/space-wizards/space-station-14/pull/32720

Give em one of these. People would love to be able to buy some of this kit from them

**Comment by Unkn0wnGh0st333** [comment]
> Hey, you know what would really give these guys a good bargaining chip
> 
> [space-wizards/space-station-14#32720](https://github.com/space-wizards/space-station-14/pull/32720)
> 
> Give em one of these. People would love to be able to buy some of this kit from them

Well I'm ngl it kinda takes away the whole "Synthesiser" part of the job, it's just meds and a fancy defib

**Comment by Avalon-Proto** [comment]
Not really. People can still ask for things they can make. IE Hyperzine. Lexorin. CLF3 smoke bomb mixes. This is just a bag of semi-legal goods they can sell to the station for their initial fuel needs

**Comment by Lyndomen** [comment]
They are an antag, if they can't get fuel they can steal it. I designed it
such that it rewards players good at chem, it doesn't need to just be a
medical merchant

**Comment by Lyndomen** [comment]
I'd also advocate that in patches like this we don't power creep it. These changes so far seem fine, but let's see how it plays out before we add more and more stuff - roles should be imperfect in what supplies they have

**Comment by perryprog** [comment]
So, another thing that isn't clear then is that leaving the ship is perfectly reasonable. Part of the ghost role description seems to imply that leaving the ship shouldn't occur at all. This is also mentioned in the original PR that "They are ruled to stay attached to their ship, and should encourage a bit more creative antagonism." which is made also made me think this was strictly the case. Pretty difficult to get out to steal some fuel if you can't leave your ship.

**Comment by Lyndomen** [comment]
> So, another thing that isn't clear then is that leaving the ship is perfectly reasonable. Part of the ghost role description seems to imply that leaving the ship shouldn't occur at all. This is also mentioned in the original PR that "They are ruled to stay attached to their ship, and should encourage a bit more creative antagonism." which is made also made me think this was strictly the case. Pretty difficult to get out to steal some fuel if you can't leave your ship.

If their ship has no fuel, I don't think anyone could begrudge them setting out to refueling it by any means necessary.

**Comment by Lyndomen** [comment]
Just to elaborate a bit more, broadly every rule is framed in the "spirit of the law". If this player has done their part in trying to make the original rules work, but circumstances have dictated their ship no longer functions, ship happens.

**Comment by Unkn0wnGh0st333** [comment]
> They are an antag, if they can't get fuel they can steal it. I designed it such that it rewards players good at chem, it doesn't need to just be a medical merchant

almost every time I've had to steal power sources like the cargo ship generator. I want to play my trader syndicate synthesis not the "run around looking for fuel until you inevitably steal the cargo generator" questline.

**Pull request closed without merging**
