### PR TITLE
Central Command Intern, a Patreon Ghost Role

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
Adds a CC Intern ghost role, based around a hypothetical whitelist tier. This is a draft PR for a few reasons. 
First, I've reached my current limit of technical experience. I only can struggle through C#, and building on to RMC's role whitelist thing is gonna be daunting. 
Second, we might not even want this, as the optics are kinda mid of always displaying a ghost role that you have to pay for. Its a mid ghost role, with no actual authority, but its still pretty dubious. I'd love to hear opinions. 

## Why / Balance
Spawning in these roles for patreon is kinda mid, and requires admin handholding. Would be nice if we had admins doing their best badmin work. 

## Technical details
Right now its all YAML but  I hit the hard part where the RoleWhitelist thing from RMC doesn't seem to work on ghost roles, so I'm kinda stuck for now. TBD. If you love working on arcane technology, feel free to drop in. 

It also adds the spawner to the CC map. 

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Dunno, probably not. 

**Changelog**
:cl:
- add: CC Intern Ghost Role for Patreons

### CODE REVIEW

**Comment by Axionyxx** [comment]
Due to NC licensed assets, none of this can be implemented with a Patreon requirement for in game benefits. Entities and such existing is fine, but nothing can exist that automatically grants Patreons in game stuff

**Comment by Lyndomen** [comment]
What are your thoughts on  keeping it as a predefined loadout we can spawn in? That way, an admin is still required to do that work, but it isnt a roundstart role.

**Comment by Axionyxx** [comment]
> What are your thoughts on keeping it as a predefined loadout we can spawn in? That way, an admin is still required to do that work, but it isnt a roundstart role.

Technically nothing wrong with that

**Comment by TadJohnson00** [comment]
Is this still being worked on, @Lyndomen?

**Comment by Lyndomen** [comment]
> Is this still being worked on, @Lyndomen?

Frankly, I'm not sure it's a good idea. Having a pre built spawner for us to place a CC intern would be nice, but no more than that.

**Comment by TadJohnson00** [comment]
I'll close this up for the moment then, I'll see if I can get something going with a random spawner or some shite

**Pull request closed without merging**
