### PR TITLE
Updated Asterisk

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Made several QoL changes to Asterisk station and raised its max players after a good high-pop test run.

## Media

image
image
image

**Changelog**

:cl:
- tweak: Updated Asterisk station with several QoL changes and a higher max population.

### CODE REVIEW

**Comment by Colin-Tel** [comment]
a fucking mimic??
image

**Comment by DangerRevolution** [comment]
> a fucking mimic?? image

yes, the debug version Github is running is trying to run the Mimic event on the debug map and is failing because it has no vending machines for the event (because the map is empty)

**Comment by Colin-Tel** [comment]
You know what, I'm gonna make some adjustments to maints and add some rooms before this all gets pushed.

**Comment by Colin-Tel** [comment]
> yes, the debug version Github is running is trying to run the Mimic event on the debug map and is failing because it has no vending machines for the event (because the map is empty)

LOL, well, the map changes are done. I guess I'll wait on review/merge.

**Review by IamVelcroboy — APPROVED** [review]
Sardine Station is a go...

**Pull request merged**
