### PR TITLE
shoukou atmos futureproofing and fish

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- teg loops have throttle pumps for when thats cherry picked
- all pumps are powered
- doubled co2 cooling setup since i do it every single round, grilled it off from salv too
- :fish:

### CODE REVIEW

**Comment by ghost** [comment]
As the current maintainer of Shoukou as a map I approve these changes. Mmm fish.

**Comment by IamVelcroboy** [comment]
One criticism is that running cables directly over the pumps can obscure them and make them hare to see/read 
image

**Comment by deltanedas** [comment]
that wasnt me i just powered the cooling pumps :trollface:

**Comment by IamVelcroboy** [comment]
The TEG being completely ready to go roundstart is too much. It should require *some* assembly/complexity.  Maybe remove a few radiators and/or connecting pipes. Something, so there is "some assembly required"

**Comment by IamVelcroboy** [comment]
> that wasnt me i just powered the cooling pumps :trollface:

ahh, fair enough

**Comment by deltanedas** [comment]
> It should require some assembly/complexity

done and replaced 2 useless cans with oxy and plasma

**Comment by deltanedas** [comment]
@IamVelcroboy approv

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
