### PR TITLE
No more "HONK mimimimimi" for the clown 

### PR DESCRIPTION
**Pull request by leonardo-dabepis**
## About the PR

Comments out the unique snoring noise for clown job.

## Why / Balance

That sound file triggers my misophonia and every time I hear it I want to scream and go feral, which is not conducive to MRP. This may seem like a strong emotional response to a noise but that's because it is.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: the clown has received medical treatment for his chronic snoring. No more HONK mimimimimi

### CODE REVIEW

**Comment by ps3moira** [comment]
I find it very funny and in character of clown.

**Comment by leonardo-dabepis** [comment]
> I find it very funny and in character of clown.

the geniuses of history were often considered incorrect and controversial by their peers, only to be later proven correct by the facts. The facts are on my side, someday it will be revealed to the world the true extent of my genius.

**Review by DEATHB4DEFEAT — APPROVED** [review]
Probably controversial

**Comment by AitorLogedo** [comment]
its really fun, expecially when clown has the trait that puts you to sleep randomly 👎

**Comment by dvir001** [comment]
No joke I have the same issue with that fucking sound, while its "funny" its LRP at best and annoying at worst.

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
