### PR TITLE
remove syndicats from the uplink

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

title

## Why / Balance

it's inherently valid yet people still go "errrm actually it's a sophont" then pretend it's not a walking bomb 
animal reinforcements are bad in general and syndicats are pointless and almost always end up causing disproportional damage
still can be spawned in by admemes, just not available in the uplink

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- remove: Removed syndicats from the uplink.

### CODE REVIEW

**Comment by Avalon-Proto** [comment]
Is it still available for nukies?

**Comment by MilonPL** [comment]
> Is it still available for nukies?

no but it could! (even though I don't see why they would buy a syndicat)

**Comment by SolStar2** [comment]
To be fair it's implied the bomb is implated and not visible and them being explosive may not be common knowledge so its fair if people are friendly to syndicates in rp. I don't really see any issue with syndicats being available and don't think its any more problematic proportionality wise than most explosives you can buy.

**Comment by Unkn0wnGh0st333** [comment]
Idea: Change the sprite to have a literally bomb vest on, then people can't "pretend" its not a walking bomb.

**Comment by dvir001** [comment]
Give the cat the syndicate bomb wire panel so you can defuse it. :trollface:

**Comment by Radezolid** [comment]
I'm against this because it's **funny** to see them explode. IMO they aren't that useful neither but they are a great distraction and chaos inducing item and it's more expensive than most bombs, removing the discount might work better to see less of them.
Edit: It's not a sophont unless cognied, until then you can shoot them.

**Comment by Lyndomen** [comment]
mouse + microbomb is just mechanically better anyway if people want to animal ops

**Comment by HTMLSystem** [comment]
If people still want them (I'm all for removing them btw) perhaps the explosion they make could be lowered so the damage isn't disproportianal (??)? Then again I haven't seen a syndicat in a WHILE, so I don't remember how bad the explosion is.

**Comment by Radezolid** [comment]
> Then again I haven't seen a syndicat in a WHILE, so I don't remember how bad the explosion is.

It's literally a micro bomb, so a 3x3 explosion.

**Comment by Radezolid** [comment]
I change my stance on them, nuke them.

https://github.com/user-attachments/assets/c1541857-08c2-45f9-9c0e-210e262ea5c1

**Comment by deltanedas** [comment]
mouseop better for actual assassination

**Review by deltanedas — APPROVED** [review]

**Comment by MilonPL** [comment]
based

**Pull request merged**
