### PR TITLE
Re enable the mime suit

### PR DESCRIPTION
**Pull request by dge21**
## About the PR

Re enabled crafting of the mime hardsuit
## Why / Balance

The clown hardsuit was re added. I see no reason to enable it and not the mime suit
## Technical details

minor yml change, just uncommented some lines
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

none I believe, I just uncommented existing yml
**Changelog**

:cl:
- add: the mime suit is craftable now!

### CODE REVIEW

**Comment by dge21** [comment]
can't believe I forgot to name the pr

**Comment by Colin-Tel** [comment]
You didn't uncomment `Resources/Prototypes/Recipes/Construction/Graphs/clothing/mime_hardsuit.yml`

**Comment by dge21** [comment]
oh oops, lemme fix that

**Review by Colin-Tel — CHANGES_REQUESTED** [review]
The hardsuit does not show up in the crafting menu.

image

**Comment by dge21** [comment]
third times the charm, It should work now

**Comment by therealDLondon** [comment]
*rubber stamp sound*
Headmin approv!

**Comment by deltanedas** [comment]
most likely fixed now that its uncommented

**Review by Colin-Tel — APPROVED** [review]
It works!

**Pull request merged**
