### PR TITLE
New Accents, Accent Weight Change + New Irish Accent Redux (From PR #1640 Thanks GitHub)

### PR DESCRIPTION
**Pull request by SsalamethVersaach**
## About the PR

This (resubmitted) PR changes existing accent weights on normal accents to make them 2 across the board and also adds the ability to choose more accents in the character menu, as well as a new Irish accent. I did some yaml changes, along with adding a new accent.

## Why / Balance

The reason behind this change was due to my own desire for people to have more accent choices, and to allow people to choose French, Russian, Spanish, Irish, and Mobster on round start. Part of this also stemmed from my desire to make it easier for players to diversify their characters, as well as being annoyed that "Accentless" was worth 2 in the code, despite being claimed as "free".

## Technical details

I changed the cost of some speech attributes in the speech.yml file, as well as added additional information and descriptions for these accents within the ftl files. In addition, I created an Irish accent which utilizes the irish.ftl and word_replacements.yml files- and added an accent system for it to function. 

## Media

screenshine

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes (that I know of).

**Changelog**

:cl:
- add: Added more accents, adjusted language accent weights from 1 to 2 on the character creation page, removed accent cost from others, and added the brand new Irish accent!

### CODE REVIEW

**Comment by SsalamethVersaach** [comment]
Github willing, this should be the final thing, hopefully, maybe. I pray that it doesn't randomly merge and pull all those commits like last time...

**Review by ghost — COMMENTED** [review]
Seems fine from a YAML perspective, no clue about the accent's C# but it seems short enough that it just ties it together as an accent.

**Comment by StarboundSolaris** [comment]
This was in a converstaion over in the discord, in our administrator general chat, but I suggested that they, just so that someone does not make their character completely incomprehensible, keep every accent at 2 points, and to make the speech disabilities/misc accents such as social anxiety, pathological liar, and frontal lisp cost no points.

**Comment by SsalamethVersaach** [comment]
After internal discussion, changed accent weights from 1 to 2 for language, but made accents like lisp, accentless, stutter, and pathological liar free.

**Review by ghost — APPROVED** [review]
Changes were documented, and this is just accent C# - I approve of the balancing because it stops John LRP from stacking two accents (other than the ones at zero here) and becoming incomprehensible. If me merging this, which is majority yaml with TWO C# files in it this breaks something, so help me god.

**Pull request merged**
