### PR TITLE
Add Paralyzer By Finger Eleven To The Jukebox

### PR DESCRIPTION
**Pull request by HawkeyeBlade**
## About the PR
title, hope everything is fine

## Why / Balance
old gem

## Breaking changes

**Changelog**

:cl:
- add: Added Paralyzer by Finger Eleven to the jukebox!

### CODE REVIEW

**Comment by therealDLondon** [comment]
I am nearly 99% sure this song is not copyright free

**Comment by HawkeyeBlade** [comment]
> I am nearly 99% sure this song is not copyright free

how do you check that? I believe it is fine to use it as nearly every youtube video uses it back in the day

**Comment by therealDLondon** [comment]
Im almost sure that the song is owned by Universal Media Group, or UMG

**Comment by HawkeyeBlade** [comment]
> Im almost sure that the song is owned by Universal Media Group, or UMG

is that a good thing?

**Comment by therealDLondon** [comment]
Thats a terrible no good very bad thing

**Comment by HawkeyeBlade** [comment]
> Thats a terrible no good very bad thing

how can I check whether if a song can be added to jukebox though?

**Comment by therealDLondon** [comment]
Do some prodding around, check if a song is under a creative commons liscence, or ask the record holder for special permission

**Comment by deltanedas** [comment]
nothing in the description gives permission to use it, nor under a CC license. reopen if you can get permission from UMG (99% impossible challenge)

**Pull request closed without merging**
