### PR TITLE
Fix verbs in mapping state (#30631)

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR

small prank

**Changelog**
:cl:
- fix: Fixed verbs not working...

### CODE REVIEW

**Review by MilonPL — APPROVED** [review]
slight miscalculation

**Review by ghost — APPROVED** [review]
I can barely read C# but this looks like five lines of C# that fixes the state, like Milon said and I hope it fixes the game breaking bug so I'm approving :tm:

**Comment by deltanedas** [comment]
didnt fix it lmao

**Comment by ghost** [comment]
fix ops FAILED

**Pull request merged**
