### PR TITLE
Return dragons

### PR DESCRIPTION
**Pull request by Mnemotechnician**
## About the PR
Returns the space dragon event and fixes the devour system

## Why / Balance
Because more time was wasted discussing the removal of one of the few midround antags than it took me to fix what caused the removal in the first place.

As I was told, the reason was round-removal of eaten bodies.

## Technical details
Made DevourSystem empty the stomach container of the Devourer when it's being gibbed (butchering includes gibbing) and reverted the PR that removed the dragon spawn.

## Media

https://github.com/DeltaV-Station/Delta-v/assets/69920617/0eaeb2db-9418-49c0-a1cb-69bebaed6757

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**
:cl:
- fix: The space dragon event is back!
- fix: Butchering or gibbing a space dragon will now properly drop the bodies it has eaten.

### CODE REVIEW

**Comment by Lyndomen** [comment]
Excellent, just what we needed. Thank you for the fix.

**Comment by Axionyxx** [comment]
This should be done upstream

**Comment by Lyndomen** [comment]
Mnemotechnician, are you interested in submitting this fix upstream?

**Comment by Mnemotechnician** [comment]
No, and I think you see why I didn't want to bother in the first place.

**Comment by Lyndomen** [comment]
With your permission I will upstream this under their license. Just let me know- thanks!

**Comment by Mnemotechnician** [comment]
feel free to, I don't care.

**Pull request closed without merging**
