### PR TITLE
Fix salvage mobs having ghost roles when they shouldn't

### LINKED ISSUE #901: There are still salvage mobs with ghost roles
## Description
It was supposed to be disabled in a recent upstream merge. The files probably need to be completely reverted

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
me when the

**Changelog**

:cl:
- fix: Space mobs no longer have ghost roles

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
What why? This will totally mess up Arena

**Comment by DebugOk** [comment]
You'll have to make special entities for arena then, instead of replacing the mobs used for salvage

**Comment by IamVelcroboy** [comment]
I guess I misunderstood and thought this was reverting everything. Still wondering why we don't want ghost takeover on salvage mods though?

**Comment by deltanedas** [comment]
they are always shitters

**Comment by IamVelcroboy** [comment]
> they are always shitters

Dang, shitters ruining everything I guess 😞

**Pull request merged**
