### PR TITLE
glacier ai/robotics update

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR

- ai spawner
- add robotics stuff (only roboticists get breaks and toilet now :trollface:)
- add a vendomat in epi
- added secborg spawners so incase it gets a slot they can spawn in sec
- add a criminal records console at the brig cells for pro to use
- fix some sec issues
- secret

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Fortress of Solitude, nice

**Comment by IamVelcroboy** [comment]
Power monitor not hooked up 
image

**Comment by IamVelcroboy** [comment]
Minor issue. Go ahead and merge now. Can fix in next map update.

**Review by IamVelcroboy — APPROVED** [review]

**Comment by deltanedas** [comment]
> Power monitor not hooked up

power monitor hasnt needed hv since the power monitor rework

**Comment by IamVelcroboy** [comment]
> power monitor hasnt needed hv since the power monitor rework

Huh, well, that's silly.

**Pull request merged**
