### PR TITLE
Finally, a big merge

### PR DESCRIPTION
**Pull request by DebugOk**
Breaking master any% speedrun

### CODE REVIEW

**Comment by deltanedas** [comment]
holy shit real

**Comment by DebugOk** [comment]
Man I love a random merge conflict while I'm also working on the DB, very cool, thanks github

**Comment by DebugOk** [comment]
Damnit Github, what the fuck is conflicting

**Comment by DebugOk** [comment]
Time to maybe break shit, cant go back now since I'm already doing the migration

**Pull request merged**
