### PR TITLE
Revert "Revert "Revert AME buff""

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Reverts DeltaV-Station/Delta-v#939

We might revert this again if everything burns but it's worth a shot. Let's gooo

**Changelog**
:cl: Velcroboy
- tweak: Reverted AME buff. AME will require more than 1 core again to function properly.

### CODE REVIEW

**Review by Axionyxx — APPROVED** [review]
Let's do it!

**Comment by DebugOk** [comment]
I've already said before this isn't a good idea without the pending fixed from upstream, but I can't stop you

**Comment by IamVelcroboy** [comment]
> I've already said before this isn't a good idea without the pending fixed from upstream, but I can't stop you

We talked about it. We took into consideration what you said. Decided it's worth the risk/reward and we're prepared to undo it if it's too problematic.

**Comment by DebugOk** [comment]
> > I've already said before this isn't a good idea without the pending fixed from upstream, but I can't stop you
> 
> We talked about it. We took into consideration what you said. Decided it's worth the risk/reward and we're prepared to undo it if it's too problematic.

If it breaks, I told you so ¯\\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by deltanedas** [comment]
is there any issue i havent seen any problem when not using 1 core ops

**Pull request merged**
