### PR TITLE
This fixes the birb gasping

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR
Birbs accumulate Co2 in their lungs, and don't remove it as fast as they breath more in

## Why / Balance
Birbs were suffocating in breathable air

## Technical details
Please merge this ASAP

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: VMSolidus
- fix: Harpies no longer choke on completely breathable air

### CODE REVIEW

**Comment by Colin-Tel** [comment]
Test failure is legit
image

**Comment by VMSolidus** [comment]
Any idea what the heck this test failure means?

**Comment by VMSolidus** [comment]
image
Damnit there's not even anything wrong with the file. It runs just fine in game.

**Comment by jzburda** [comment]
I'm stumped too. 
The error say you're modifying the SolutionContainerManager in .yml. That's BS. I'm reading over your .YML edit and while it did add in a whole new BaseOrgan, it's a straight cpaste from HumanBaseOrgan.

**Comment by VMSolidus** [comment]
image
I think we're being gaslight by the build test, because it loads ingame completely without issue, and the Harpy works exactly as advertised

**Pull request merged**
