### PR TITLE
remove femtanyl from the jukebox

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

nukes femtanyl from the jukebox

## Why / Balance

requested by adei for the reason "loud"

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
no.

### CODE REVIEW

**Comment by deltanedas** [comment]
there was a pr to make it quieter no

**Comment by MilonPL** [comment]
> there was a pr to make it quieter no

there was but I've been told to remove it while I had VSC open so

**Comment by ghost** [comment]
okay but you can't deny it's still fucking kind of loud!!

**Comment by MilonPL** [comment]
> okay but you can't deny it's still fucking kind of loud!!

okay but you can't deny that having an extremely loud song that doesn't fit the environment of the game at all is kinda funny

**Comment by ghost** [comment]
you know what, that's sort of true. I'm gonna request Colin for this because he had a hand in this one. Colin, what do you think of this clown suggestion.

**Review by Colin-Tel — APPROVED** [review]
🤷

**Pull request merged**
