### PR TITLE
Anchors Edge Station!

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
We're losing it captain! Divert all power to inertial dampners and prepare to abandon ship!
...
Adds Station anchor to Edge.

## Why / Balance
Anchor...

## Media
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
No CL No fun

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
*...invalids...*

**Comment by therealDLondon** [comment]
> _...invalids..._

What do you mean they're back! I thought I killed them!

**Comment by IamVelcroboy** [comment]
> > _...invalids..._
> 
> What do you mean they're back! I thought I killed them!

did you make new ones?  😄

**Comment by IamVelcroboy** [comment]
Looks like just a random firelock 
image

**Comment by therealDLondon** [comment]
"Looks like just a random firelock"
How in gods green-
Nevermind ill assassinate the firelock later

**Comment by IamVelcroboy** [comment]
Closed in favor of [#1961](https://github.com/DeltaV-Station/Delta-v/pull/1961)

**Pull request closed without merging**
