### PR TITLE
Pebble Station Update

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
- Removed Cloning bay
- Added cryogenics and medical research lab
- Added new maints above arrivals, surrounding new cryo
- Changed maints lights to the correct ones station-wide
- Moved Psych to the old mining pod on the south asteroid
- Added new hallway from dorms to the mining pod and evac
- Adjusts some sus pipes
- Adjusts some wires
- Adds the RPG-7 to the armoury
- Adjusts some maints spawns

**Changelog**

:cl: Fox
- add: Added cryo and some new maints to Pebble!
- tweak: Adjusts some elements of Pebble

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
- [ ] missing tiny fan
image
- [ ] All of the rest of sec is using reinforced walls on the exterior except the new area.
- [ ] The various "survival" and mining signs make this a little odd
image

I think moving pysch up here might be better, it's a shorter walk and then the mining pod can still be used as a fun hidden location. 
image

**Comment by IamVelcroboy** [comment]
Coming back to this?

**Comment by therealDLondon** [comment]
I will come back to this its just havent found the motivation to work on Pebble seeing as im only maintaining it as nobody else will.

**Comment by IamVelcroboy** [comment]
OK. Just checking. No pressure

**Comment by therealDLondon** [comment]
Screenshot 2024-09-05 145124
pebble1

Added station anchor as a temp, seeing how important it is for a low mass station like pebble

Psych office location remains, for privacy, new mining pod added to the south west asteroid

Tiny fans replaced with directional fans where appropriate

**Review by IamVelcroboy — APPROVED** [review]
Going to merge this with the knowledge that Yule is taking over maintaining, We can take a look at any potential issues after that.

**Pull request merged**
