### PR TITLE
Re-add removed security gear + Fix boot knives

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

- Re-adds the removed legacy security gear to loadouts for more customisation.
- - In the interest of not entirely undoing intent, the Station Security line of customisation options have been moved to the top of security loadouts where applicable. Security lockers will also maintain StaSec coats.
- Fixes missing boot knives from combat boots.
- Re-adds winter boots to HoS and Warden lockers.
- Re-adds winter boots and cowboy boots to Secdrobe.
- Removed service / cryogenics access from brigmedic, as this is outdated design.

**IMPORTANT:**
This PR also reverts the removal of Wizden armors. This is a special conversation, but I don't think that a change like this should have been PR'd with a resprite. See below. 

## Why / Balance

A 'resprite' shouldn't involve a net reduction in content as it left quite a few people frustrated, and a few people were especially frustrated over the detective coat 1984 in particular. By removing the opposition's content, you lose the ability to gather metrics/feedback from comparing different sprites in use. Also, Loadouts serve to provide character customisation option to the player, and attempting to standardise security uniform is counter-intuitive to its implementation.

This PR only reverts changes in the last PR, otherwise I'd be hypocritical. However, the situation has raised some questions.

- While removing knives from combat boots was an accident, I do think it's wise to think about making combat knife independent of boot selection. Combat/jackboots are basically mandatory even if you want winter boots.
- We've had Wizden armours in loadouts for a while now, and I think security officers have gotten comfortable using them. They will either need to be resprited / rebalanced / removed in a future PR.
- - I'm all for more options, but the Wizden armours don't align with DeltaV's "specialised armour" design. I'd like to see new stats for either of them - personally I think a 'flak jacket' which reduces explosive damage by 20% would do nicely with breaching charge personalities (me).
- Warden didn't have an option to select winter boots in loadouts beforehand, and thus will not be getting the option in this PR either. I'm happy for TJ to add it if they eventually resprite winter boots like they say, or for anyone else to PR it earlier.

## Technical details

All YAML

## Media

image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Readded some legacy clothing options to Security loadouts.
- fix: Security officers get their combat knives back.

### CODE REVIEW

**Comment by Axionyxx** [comment]
I agree with this pr

**Comment by ghost** [comment]
I approve because this was my reviewless squashless blunder! If we could get the other bugs in the loadouts too (mail carrier coat spelling error) and give sec their boot knives back that'd be great

**Comment by Timemaster99** [comment]
#1517 now makes this a duplicate

**Comment by ghost** [comment]
WarMechanic, given the changes that this PR addresses were reverted, I'm going to close this PR, if that is fine with you.

**Pull request closed without merging**
