### PR TITLE
The Resprite: Diagonal Reinforced Wall, Greyscale Decal Cleanup, Secret Doors

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

Fixed some wooden tiles (Aikakakah did it, blame them.)
Pulled the diagonal walls from them, and as collateral, got a shit-ton of secret doors. From new-frontiers-14/frontier-station-14#757
Fixed decal offsetting on the new sprites, because there were a bunch of old ones clashing with the normal ones.
## Why / Balance

I got annoyed at a bunch of little spriting discrepancies and I've decided that I needed to take Noct's resprite project under my wing so forward things I need to do to me. I have a hefty list.
## Technical details

A lot of RSIs, YAML.
## Media

295443841-455d93c1-465d-4138-8a12-6200abfc68b2
image
image
image

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl: Adei, ErhardSteinhauer, Aikakakah
- tweak: Tweaked wooden tiles so they go with the rest of wood chairs / items more.
- tweak: Decals are now no longer offset by one pixel!
- add: You can now build more secret doors.

### CODE REVIEW

**Comment by TadJohnson00** [comment]
Me personally? I'd love if this could get split into separate PRs

**Comment by ghost** [comment]
I'll split the tanks into a seperate PR, and the walls / decals / door assembly can stay here >:)

**Comment by ghost** [comment]
I rember 😔

**Comment by TadJohnson00** [comment]
Wood tiles get Dir. approval
Diagonal walls get Dir. approval
And secret doors, I guess, get Dir. approval - unless there's something secret about those secret doors I ain't seeing

**Comment by ghost** [comment]
There is nothing secret about the secret doors TJ.

BUT WHAT ABOUT THE DECALS?!!??!?!?!!!??!?!??!111

**Comment by TadJohnson00** [comment]
Decals fine x3

**Review by TadJohnson00 — APPROVED** [review]
YAML seems fine after looking through too. All good to merge?

**Comment by ghost** [comment]
Yeah, pretty much. What harm could it do?

**Comment by dvir001** [comment]
@adeinitas We actually made more edits to the walls to allow walls to combine with other walls, did you grab the last changes to the files?

https://github.com/new-frontiers-14/frontier-station-14/pull/1603

**Comment by ghost** [comment]
No! I am doing that now, because oh fuck, oh shit!!

**Pull request merged**
