### PR TITLE
The Removal Of War

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
Removed the war declarator from the commander's starting gear.

## Why / Balance
It makes a LRP gamemode kill whatever it had left of RP and it just becomes a big NRP TDM round.

## Technical details
Commented out 2 lines in a YAML.

## Media
None.

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Hopefully none.

**Changelog**

:cl:
- remove: Removed the war declarator from the nuclear operatives.

### CODE REVIEW

**Comment by Stop-Signs** [comment]
While I agree war needs some adjustment to prevent every tider passenger from immediately running into sec and taking all the firearms. I also disagree with removing it entirely, war is just such a fun game-mode once you get past the tide of "give me a weapon" people.

**Comment by Lyndomen** [comment]
Warops was an experiment, and it's ok to say it doesn't really work on mrp. If there are anydments suggested/, implemented that would be sick but wyci demon

**Comment by Monotheonist** [comment]
I'm going to agree with Lyndomen - it was an experiment, and if it doesn't work out, then we have a conclusive reason as to why. If there's amendments, suggest, and perhaps implement.
I am of the opinion that war should not last forever.

**Comment by ThataKat** [comment]
I agree, it was absent for a long time for a reason. People have fun with it, but primarily for mechanical reasons, and combat. Not for the good rp. As an MRP fork, I think we tried it and it doesn't fit

**Comment by CybersunOperative** [comment]
The original Contrib that added War Ops to Delta V has voiced that it was never meant to stay.

Direction has echoed similar sentiments, and with this PR, we wish to see War Ops removed.

Direction Approved :)

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
