### PR TITLE
Bit of quality to shoukou.

### PR DESCRIPTION
**Pull request by Adrian16199**
Adds a siobhan toy on the front of epistemics
Adds a boxing bell in the abandoned ring in the maintenance Adds renault toy in bridge's table next to disabler and stun baton Adds atmos plushie who is now sitting on a chair (That was also added) in atmos. 
The fire extinguisher in cargo that was behind the cargo shuttle computer is now next to the logidrobe.
Gave TEG's burning chamber some blast doors for convenience.
Adjusted arrivals to be symmetrical.
Gave lawyer the lawdrobe
Added Igniter and a signaller to TEG room and linked both.
Added a canister of each: plasma, water vapour, oxygen to TEG room
Added a plasma table which the signaller resides on.

## About the PR

I added plushies

## Why / Balance

I believe it would add bit of life to the map.

## Technical details

Mapping

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image
image
image
image
image
image
image
image

## Breaking changes

**Changelog**

-tweak: Shoukou received some plushies and a boxing bell.
-tweak: TEG room now is more convenient to atmosians.
-tweak: Lawyer now has a law drobe.
-tweak: Arrivals is now symmetrical.

### CODE REVIEW

**Comment by Adrian16199** [comment]
Going to close the PR since there was a map change and I dont want to waste anyones time if I fuck up the map due to it.

**Comment by Adrian16199** [comment]
Buh, I dont like reopenin it but I guess.

**Comment by Colin-Tel** [comment]
If you're willing to just change the lawyer office door and maint hatch to Lawyer access and change the reporter maint hatch to Service access, we can merge this today.

**Comment by Adrian16199** [comment]
Uh, sure

**Pull request merged**
