### PR TITLE
Adds new station: Lobster Station (DONT REVIEW THIS ONE I MADE A DIFFERENT PR BC IM UNFAMILIAR WITH GITHUB RAHH)

### PR DESCRIPTION
**Pull request by PubliclyExecutedPig**
Adds lobster station

## About the PR
Lobster station, named because its shaped like a lobster, is a modern and expensive station, mainly focussed on research and development, income from passengers (like a resort), with a strong security to back it
## Why / Balance
To add some variation to the map pool, especially on apoapsis, whilst being quite unique in its characteristics... kinda like a dv fland station (but hopefully better)

## Media
Lobster-0

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).  
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
-add: Lobster Station, a medium pop station! (actual lobster is not guaranteed and is at the discretion of the chefs)

### CODE REVIEW

**Comment by PubliclyExecutedPig** [comment]
i need to add some more stuff

**Comment by IamVelcroboy** [comment]
you don't have to close it to add more. You can add additional commits. You can also put it on "draft" mode while still working on it

**Comment by PubliclyExecutedPig** [comment]
ive never PR'd before :/

**Comment by PubliclyExecutedPig** [comment]
IGNORE THIS PR PLEASE

**Pull request closed without merging**
