### PR TITLE
add scarfs to all loadouts

### PR DESCRIPTION
**Pull request by portfiend**
## About the PR
add scarfs to all loadouts (except prisoner and gladiator)

## Why / Balance
was gonna add this to a downstream server but i was told by a project manager to add it here

## Technical details
YAML warrior with my finest weapon "Ctrl-V"

a small note: if a scarf and another neck item are equipped at the same time it will drop the scarf (usually) on the floor when the person spawns

## Media
Screenshot_135

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: portfiend
- tweak: every loadout has scarfs now

### CODE REVIEW

**Comment by portfiend** [comment]
drafting because i hate this

**Comment by Lyndomen** [comment]
I really love scarves, and this is awesome.

**Comment by portfiend** [comment]
> I really love scarves, and this is awesome.

surely theres a less repetitive way to add them than this though

**Comment by Timemaster99** [comment]
Is this meant to be drafted, still?

**Comment by portfiend** [comment]
> Is this meant to be drafted, still?

i believe so, this PR creates redundancy with a bunch of other loadouts. a lot of loadouts have scarfs in the job-based neck selection AND in the scarfs loadout now and ive been trying to think on how to go about it

**Comment by DangerRevolution** [comment]
> > I really love scarves, and this is awesome.
> 
> surely theres a less repetitive way to add them than this though

there isn't, loadouts is specifically designed to stop multi-loadout items

**Comment by Samsterious** [comment]
Until we have some sort of universal loadout in addition to role-specific loadouts, I am generally in favor of expanding the selection. Some of these lists are going to get _really_ long though, and giving every single role access to the wide variety of passenger drip in this game is going to be a tedious nightmare to write and review.

Also, let prisoners and gladiators have scarves! Is there any mechanical reason _not_ to let them have such things?

**Comment by ghost** [comment]
> Until we have some sort of universal loadout in addition to role-specific loadouts, I am generally in favor of expanding the selection. Some of these lists are going to get _really_ long though, and giving every single role access to the wide variety of passenger drip in this game is going to be a tedious nightmare to write and review.

I'm pretty sure the way Frontier got past the restriction of giving everyone passenger drip was just getting rid of the job restriction in some sense

**Comment by TadJohnson00** [comment]
Is this still being worked on, @portfiend?

**Comment by portfiend** [comment]
> Is this still being worked on, @portfiend?

nope

**Pull request closed without merging**
