### PR TITLE
Система возрождения для призраков

### PR DESCRIPTION
**Pull request by OCOtheOmega**
## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by OCOtheOmega** [comment]
Oops

**Comment by deltanedas** [comment]
shamelessly stolen from frontier smh

**Comment by OCOtheOmega** [comment]
> shamelessly stolen from frontier smh

I would not say that if I were you, because even the code is not similar, otherwise I would call you just an idiot, before accusing of such things, check how it work in NF.

**Comment by deltanedas** [comment]
its a joke

**Pull request closed without merging**
