### PR TITLE
Reverts - Makes sabre sheathe use ItemSlots.

### PR DESCRIPTION
**Pull request by Adrian16199**
Just no.

## About the PR

Reverted a PR
## Why / Balance

It felt unneccesary and it doesnt really make sense for it to act like a combat boot. Also its alot more convenient.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/DeltaV-Station/Delta-v/assets/144424013/08604064-2d16-4fa2-aac8-18675f9a0594

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Captain's sabre sheathe works how it did previously.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
It's fine as is, no? It's not inconvenient to click the belt rather than opening its inventory and pull it out

**Comment by Adrian16199** [comment]
Thing is, the current one, you *have to* pull it out one way by alternatively clicking it, with this, you can do like with backpacks, aka pulling out the last object that was in said storage. Its alot more convenient compared to tryin to find it on your belt while you are gettin shot compared to doin what you would do with your backpack, keybind it without lookin (so basicly the point of shethes to quickly draw a weapon)

**Comment by deltanedas** [comment]
i thought ctrl e worked for itemslots now

**Comment by Adrian16199** [comment]
> i thought ctrl e worked for itemslots now

Doesnt seem to work when im tryin it.

**Comment by deltanedas** [comment]
might just need to wait for next upstream merge then, 99% sure mirrorcult made a pr to have ctrl+e work on itemslots

**Comment by Adrian16199** [comment]
If thats the case then im probably just goin to put this on draft and just wait. If there will be such PR merged, then I will close it if its not goin to be closed by anyone else before it.

**Comment by DangerRevolution** [comment]
> i thought ctrl e worked for itemslots now

^ I also thought this was an option so worth seeing.

**Comment by Adrian16199** [comment]
image

There was a PR merged regardin somesort of "smart" equipping but ctrl + E doesnt seem to work on it so ee ¯\_(ツ)_/¯
 Which makes me skeptical because the person you are refferncin is indeed that guy.

**Comment by Adrian16199** [comment]
image
And the settings refference that the shift + E would be the smart equipping but currently on the sheathe, all it does is take out THE ENTIRE SHEATH and not the sabre

**Comment by deltanedas** [comment]
yeah might be worth reverting then, its pretty bad for a sheath to not have fast access to sword

**Comment by DebugOk** [comment]
I'll review this during the upstream merge, and revert it if necessary during that.

**Pull request closed without merging**
