### PR TITLE
disable vent fauna events

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
"removed pending rework" is reminiscent of a certain repo but there are good ideas floated like picking 1 vent, announcing the location and giving it a good delay for people to run away then sec has something to do instead of everyone needing bats to defend themselves from simplemobs that spawn on them with 0 telegraphing

## Why / Balance
it promotes absolute no RP, preys on new players and doesnt really provide sec anything to do unless they are the ones slimes etc spawn on
if you are slowed at all you cant outrun slimes so you can't leave them for sec to kill, you either kill them there or die

## Breaking changes

**Changelog**
:cl:
- remove: Removed vent fauna (spiders, slimes, snakes) events pending rework.

### CODE REVIEW

**Comment by rosieposieeee** [comment]
yeah 100% agreed. the location idea is neat, maybe something like a dragon rift sans dragon

**Comment by Lyndomen** [comment]
Under direction review, 24 hours

**Review by Lyndomen — APPROVED** [review]
Direction approved for a test merge, we are leaning towards reverting this in 24 hours if it's anywhere near shit. Maybe 10,000 gas leaks is fun tho idk

**Comment by Axianamos** [comment]
Not a fan of this. Removing content with nothing ready to replace it is a net negative. Vent critters isnt the most interrsting event, but now we're left with meteors, gas leaks, and more meteors.

We need more events. Not less.

**Comment by deltanedas** [comment]
theres ideas to replace it already

**Pull request merged**
