### PR TITLE
adds new headset sprites for the listening post operatives

### PR DESCRIPTION
**Pull request by DangerRevolution**
## About the PR

added new headset sprites
## Why / Balance

just a little drip for them

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

image

image

image

image

image

:cl: Danger! Revolution!
- add: Added sprites for Syndicate Listener's Headsets

### CODE REVIEW

**Comment by leonardo-dabepis** [comment]
The sprite doesn't pass the 360 test (changes size when the character rotates, getting notably taller when viewed from the left side). Other than that I think it looks fine 👍

**Comment by DangerRevolution** [comment]
updated, pictures are up-to-date

**Comment by DebugOk** [comment]
@leonardo-dabepis Is it good to go now?

**Comment by leonardo-dabepis** [comment]
> @leonardo-dabepis Is it good to go now?

yup it's good

**Pull request merged**
