### PR TITLE
Hair!

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Things are about to get hairy.

This PR is for adding the hairstyles that were "modernized" that look subjectively better than their replacements.

~~It is intended that this PR remains a draft until players are able to play on the rebase version, and they are then able to point out which hairstyles should make a return. (either in a PR comment, in the Discord, or otherwise)~~ yeah that didn't happen lol

## Technical details

Prettified the human_hair.rsi `meta.json` so it doesn't look terrible.

## Media

image
image
image
image

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
Fade (None)
nofade.png

**Comment by Colin-Tel** [comment]
this meta file *SUCKS*

**Comment by DebugOk** [comment]
You ever gonna finish this? Or do we close it for now

**Comment by Colin-Tel** [comment]
I was intending on keeping it open until people find more hairstyles, so it could all be in one PR, but I think I'll just send it with the few hairstyles we've found so far. I'll fix it before Monday

**Review by FluffiestFloof — COMMENTED** [review]
Looks good except the fact that they don't follow the same naming convention?
HumanHairBobClassic = Bob Hair Classic
HumanHairClassicGentle = Classic Gentle

**Comment by Colin-Tel** [comment]
> Looks good except the fact that they don't follow the same naming convention? HumanHairBobClassic = Bog Hair Classic HumanHairClassicGentle = Classic Gentle

lol that is true, because I merged the PR that added those hairstyles like 10 minutes before I finished this PR, and prior to that there *was* no precedent set.

**Comment by Colin-Tel** [comment]
I'm fine with having Classic Gentle becoming Gentle Classic, but Classic Fade (Medium) into Fade Classic (Medium) just rubs me the wrong way.

**Comment by Colin-Tel** [comment]
image
nvm this is best

**Pull request merged**
