### PR TITLE
make lathe items worthless

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

reduces the price of all printed items to 40%
doesn't affect loot, salvage crates full of random shit to sell are back on the menu
can be set per lathe, affects all for now

## Why / Balance

image

## Breaking changes

**Changelog**

:cl:
- tweak: Reduced the price of all items printed from the lathes by 60%

### CODE REVIEW

**Comment by Colin-Tel** [comment]
IMO this is a pretty great idea; it solves the problem of people mass producing items via lathes for profit, but still allows people to sell stuff they find on wrecks or from disassembling.

**Comment by Unkn0wnGh0st333** [comment]
The sweatshop days are over 😔

**Comment by Bonktrauma** [comment]
@MilonPL  is it 60% or 40%

**Comment by dvir001** [comment]
> @MilonPL is it 60% or 40%

Worth 40%

**Review by deltanedas — APPROVED** [review]

**Comment by fow111** [comment]
Colon Three.

**Pull request merged**
