### PR TITLE
New Lobby Track "Undefined Theory" by A-Guy

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
New lobby track, "Undefined Theory" by A-Guy

## Why / Balance
MUSIC!!!!!

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: New Lobby Track: "Undefined Theory" by A-Guy

### CODE REVIEW

**Comment by deltanedas** [comment]
whats the source on CC0-1.0

**Comment by therealDLondon** [comment]
> whats the source on CC0-1.0

Youtube video just says its creative commons and free use

**Comment by deltanedas** [comment]
creative commons is a whole category and free use can mean gratis, please contact the artist for an exact license to use

**Comment by CopperCrow9** [comment]
Imagine if his alternate version, Chaos Theory, became the ambience for high glimmer stations...

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
