### PR TITLE
remove tech anomalies

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR

removes tech anoms from random spawner
## Why / Balance

have you seen these things?? they're a fucking epileptic hazard what the fuck
## Technical details

n/a
## Media

n/a
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

n/a
**Changelog**

:cl:
- remove: Removed tech anoms until we pull upstream fixes for superfast flicker.

### CODE REVIEW

**Comment by Avalon-Proto** [comment]
Maybe we just remove the ability to toggle lights? They are interesting anoms after all

**Comment by TadJohnson00** [comment]
I just want this live ASAP. WizDen's apparently got fixes either merged or in the works, so it really isn't a big deal to me, we can re-enable them when we pull upstream

**Comment by Avalon-Proto** [comment]
Ahh fair enough, didn't know if they did or not

**Comment by Radezolid** [comment]
> Maybe we just remove the ability to toggle lights? They are interesting anoms after all

It can happen to doors too, which makes a extremely loud noise of constant bolting/unbolting.

**Review by ghost — APPROVED** [review]
Simple commenting out.

**Comment by ghost** [comment]
(This will come back in an upstream merge, trust.)

**Pull request merged**
