### PR TITLE
Salvage Wreck Overhaul & New Salvage Mobs

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR
Uses #526 as a Dependency
TODO:

- [ ] Run every wreck in the entire game, both lists, through a quality check and balance pass
- [ ] Make new salvage mobs based around Hostile Humanoid NPCs
- [ ] Add Spawners for these new hostile humanoids, and make use of them in wrecks
- [ ] Somehow fix/get fixed the AI inability to bolt guns
- [ ] Stranded Nukie miniboss

## Why / Balance
A lot of new salvage wreckages have been added back into the game recently, however these were just done via porting the old Nyano era wrecks back to the list. The actual quality of wrecks varies wildly, with both the Wizden and Nyano lists having a few really terrible examples mixed in with some outstanding ones. A consistent issue seen is that wrecks do not often have their potential rewards balanced by risk. With some of the most egregious examples being a wreck that contains zero hazards of any kind, but rewards the players with two C-20r SMGs and two retro laser guns that are just sitting on a table, and the opposite having a reinforced vault guarded by multiple space bears and turrets, which contains solely a single retro laser with no other loot. 

I have a pretty decent amount of experience with design philosophy, and one such philosophy I intend to follow here is that the game needs to interact with the players. Instead of players simply getting loot for free because they know how to juke a carp, the loot needs to fight them. For a bloodred headset to exist on a wreckage, it needs to be worn by a hostile NPC. If salvage wants to loot a gun, that gun must first be fired at salvage. In the most extreme example possible, to get a C-20r, salvage must first fight someone who has a C-20r, kill him, and take his gun. Yes, that will introduce an extraordinary amount of risk to salvage, but the rewards must in turn match the risk. It may very well be that experienced salvagers could encounter a wreckage, and then turn away from it because they know they simply aren't equipped to handle fighting something like a stranded nukie.

## Technical details
TODO

## Media
The barge returns, but it won't be something cargo buys. 
image

## Breaking changes

**Changelog**

:cl: VMSolidus and DangerRevolution
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

### CODE REVIEW

**Comment by DebugOk** [comment]
Pull requests shouldn't be trying to do this much at once, as it just makes it harder to revert stuff if it breaks

**Comment by VMSolidus** [comment]
Yea all of those commits came from a PR526, which is this PR's dependency. All that's going away.

**Comment by DebugOk** [comment]
> * [ ]  Run every wreck in the entire game, both lists, through a quality check and balance pass
> * [x]  Most likely _move_ the entire list of wizden wrecks to our own variations
> * [ ]  Somehow fix/get fixed the AI inability to bolt guns
> * [ ]  Stranded Nukie miniboss
> * [ ]  Gorlex Pirate King midround event
> * [ ]  Salvage megadungeons as midround events
> * [ ]  Reimplement the Shipyard Console

Still too much for one pr

**Comment by VMSolidus** [comment]
Fine I'll split off the midround events to their own PRs. But I'm still going to do the wrecks with this PR.

**Comment by IamVelcroboy** [comment]
We'll need to look at this if/when it is merged and see how it affects our plans here and our goal moving forward. 
[#23752](https://github.com/space-wizards/space-station-14/pull/23752)

**Comment by VMSolidus** [comment]
I needed to remake this PR anyway due to some fun issues. But we're also currently focused on updates and support for the Listening Outpost, while I also have my own PRs. Going forward, I still intend to do a "Salvage Midround Event", but it's likely that the midround event will take the form of the first major update to the Listening Outpost. We essentially want to make the Listening Outpost midround event into being its originally intended "Salvage Encounter Hybrid". It'll spawn as one of the entities that appears in an "Asteroid migration", roughly a kilometer away from the station, with a patch of mixed asteroids and wrecks. Which will help since the outpost would spoof the mass scanner signature of an asteroid. That only makes sense ingame if it had asteroids/wrecks to hide amongst.

**Comment by IamVelcroboy** [comment]
> I needed to remake this PR anyway due to some fun issues. But we're also currently focused on updates and support for the Listening Outpost, while I also have my own PRs. Going forward, I still intend to do a "Salvage Midround Event", but it's likely that the midround event will take the form of the first major update to the Listening Outpost. We essentially want to make the Listening Outpost midround event into being its originally intended "Salvage Encounter Hybrid". It'll spawn as one of the entities that appears in an "Asteroid migration", roughly a kilometer away from the station, with a patch of mixed asteroids and wrecks. Which will help since the outpost would spoof the mass scanner signature of an asteroid. That only makes sense ingame if it had asteroids/wrecks to hide amongst.

Yep, that sounds perfect. I can start mapping some decoys and other debris for it when I finish the Hammurabi rebase.

**Comment by IamVelcroboy** [comment]
All advanced machine parts were removed which were part of what we were rewarding players with in more challenging maps. This means there is less or weaker rewards on these maps. We'll need to consider this while rebalancing.

**Pull request closed without merging**
