### PR TITLE
Add Interdyne clothes + contraband to the chemdrobe

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
Title.

## Why / Balance
Clothes for the interdyne seller shuttle role + a way to obtain it in game for chemists to use.

## Technical details
YAML changes + new sprites.

## Media

https://github.com/user-attachments/assets/1581623a-4a4d-4e63-809c-deb04d768205

https://github.com/user-attachments/assets/570ac009-4faf-492e-aa5f-9c1195abc5f1

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None.

**Changelog**

:cl: JustAnOrange, Radezolid
- add: Added Interdyne chemistry clothes, obtain them at your nearest hacked ChemDrobe!

### CODE REVIEW

**Review by Lyndomen — APPROVED** [review]
Great sprites, good shit. I personally want may more corpo specific shit rather than le evil black and red valids

**Review by deltanedas — APPROVED** [review]

**Comment by Avalon-Proto** [comment]
Hey I just wanted to say. I both emagged and hacked a chemvend the either day for these clothes but the special chem goggles were not in it. Might wanna look into that

**Comment by Radezolid** [comment]
guh

**Comment by Radezolid** [comment]
Wait no, i never added it because it was meant to be for the ghost role. It's both a medhud and chem goggles

**Comment by Avalon-Proto** [comment]
> Wait no, i never added it because it was meant to be for the ghost role. It's both a medhud and chem goggles

I mean. You only said you were adding it to the vendor so I thought it would be in the chemvend too, just because these would be *so nice* to get as a standard chemist. Buuuut, you *could* swap the chem analysis goggles in the Vestine kit to be the Interdyne goggles

**Comment by Radezolid** [comment]
Fair enough, i won't PR them to the vendor tho, it will just become an extra step and everyone would use them

**Pull request merged**
