### PR TITLE
make ce require whitelist

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
we have the means

## Why / Balance
citing countless shitce rounds that cant even set up power let alone *distro* or teg
or ones that go out of their way to break a perfectly fine teg, or let singulo loose

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Chief Engineer is now whitelisted.

### CODE REVIEW

**Comment by MilonPL** [comment]
The round #14291 TEG incident.

**Comment by perryprog** [comment]
This is a bit of a bummer considering I’m a bit of an engineer main and don’t use discord so I don’t have access to request whitelist. Is there any chance we could have this on a more informal basis than, e.g., captain whitelist?

I also don’t totally disagree with the reasoning here, but as a peri main I think I’ve only seen a CE who wasn’t like… perfect at TEG once? So I’m not sure just how needed this is.

**Comment by Lyndomen** [comment]
> This is a bit of a bummer considering I’m a bit of an engineer main and don’t use discord so I don’t have access to request whitelist. Is there any chance we could have this on a more informal basis than, e.g., captain whitelist?
> 
> I also don’t totally disagree with the reasoning here, but as a peri main I think I’ve only seen a CE who wasn’t like… perfect at TEG once? So I’m not sure just how needed this is.

Howdy, I totally hear you not wanting to use discord, and we're setting up an alternative.

**Comment by therealDLondon** [comment]
We're looking into an overhaul of the WL system especially now we have role specific whitelisting UI real. Closing this for now

**Comment by deltanedas** [comment]
> now we have role specific whitelisting UI real

thats what this uses, requiring blanket whitelist would be the job requirement

**Pull request closed without merging**
