### PR TITLE
Submarine Station

### PR DESCRIPTION
**Pull request by UnicornOnLSD**
## About the PR
'Have YOU ever gotten space herpes, have YOU ever had a sick family member that needed the BEST treatment ? Then Submarine station is the place for YOU and your loved ones !' NT Advertisment (publicity campaign n°8)

Submarine station is a high-pop map designed with an extensive medical department at the center of it, expensive maintenance tunnels, a luxurious permabrig and a zoo for the animal lovers !
Adjusted for rebase and tweaked to the bone for everyone's convenience and fun.

## Why / Balance
More station, more submarine, more medical, yes.

## Technical details
N/A

## Media
womp
woomper
womperrerr
fefefefe

And here's a free picture of bridge for being that well made by Rose
fefefeffeeff

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A
**Changelog**
A lot was tweaked since the last submarine station change made by Rose, here are the following I've done:
Major tweaks:
-Fixed atmos layout (scrubbers and vents shouldn't overlap the main pipes anymore).
-APCs are now split more fairly to prevent power issues in the later run.

Minor tweaks:
-fixed the zookeeper's accesses
-added shutters to warden's office
-added jani lights to each department's entrances
-added shuttle timers around the station
-added the new chemistry gear in chemistry
-reinforced a few walls around substations and airlocks
-added a few dispensers for the cleaners and welders of the station
-added ID cabinet in bridge
-clownies and mimers have their own room with own locker and accesses
-added a high security door to access communications.
-added service room
-fixed the belts in logistics

-more things I cannot remember, likely.
:cl: Rose and Unicorn On LSD
- add: Added Submarine Station. A new map with a heavy emphasis on the medical dept. Features also include a full zoo, park with an ice rink, and some sort of experiment-gone-bad deep within the epistemics labs.

### CODE REVIEW

**Review by DebugOk — CHANGES_REQUESTED** [review]
Why is the solution getting modified?

This is also lacking everything required for a map to run in game. I'll be changing it to a draft.

**Comment by UnicornOnLSD** [comment]
hm, sol being updated since I updated my visual, I do believe, the rest I'll see with velcro

**Review by UnicornOnLSD — COMMENTED** [review]
final fix, reverted the SLN change after visual studio did me an auto update, other stuff is goon, should be all clean from now

**Comment by IamVelcroboy** [comment]
Mapinittest needs a comma after Hammurabi

**Comment by UnicornOnLSD** [comment]
fixed, yes, mbad

**Comment by IamVelcroboy** [comment]
OK, remove the medical borg from the prototype file. That one's on me. Didn't realize the job doesn't exist. Maybe a leftover Nyano thing 🤷

**Comment by IamVelcroboy** [comment]
Use the Seal for Evac

**Comment by IamVelcroboy** [comment]
> Use the Seal for Evac

You could also use the NTES_BC20, it was just ported from Nyano. I just don't think the Centipede is designed for this map, or visa versa

**Comment by UnicornOnLSD** [comment]
gotcha, last fixes doing now, I'll take the NTES_BC20 for 'em looks, fixing cryo pods and last things, I'll post a comment once it's fully ready imo

**Comment by UnicornOnLSD** [comment]
if this commit passes the check, map is done and ready to be sent, cheers.

**Review by DebugOk — APPROVED** [review]

**Pull request merged**
