### PR TITLE
Sec Outerclothing Update

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR

Adds a new armour for future use, intended to be exclusive to the HoS and warden.
Adds winter coats for general security, warden, and HoS.
Adds greatcoats that can be unbuttoned for general security, warden, and HoS.
## Why / Balance

Intent to remove some armour from security coats in future, reducing it from ~30% flat reductions to 25% brute/slash/heat and 15% pierce. This affects both the head of security, who has previously used a trench coat "enhanced with a special alloy", and the warden, whose coat was simply described as "sturdy". As a result, they will be receiving an advanced plate carrier that also features storage space.
## Technical details

n/a
## Media

image
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n/a
**Changelog**

Doesn't touch anything in active play yet.

### CODE REVIEW

**Comment by TadJohnson00** [comment]
rrready to merge if it doesn't break code

**Comment by TadJohnson00** [comment]
turns out I borked it but shoul be fix now :point_right: :point_left:

**Comment by TadJohnson00** [comment]
hatred.

**Review by ghost — APPROVED** [review]
Seems fine to me as far as YAML goes. Replaces coats. Resprites them, renames them. My head hurts. If you have anything you intend to fix from this do it in a future PR, though that often goes unsaid, haha.

**Pull request merged**
