### PR TITLE
Shoukou: Station Anchor

### LINKED ISSUE #1853: Shoko pumps missing LV
## Description

PR [#28995](https://github.com/space-wizards/space-station-14/pull/28995) got merged upstream meaning we will probably get it here soon. All pumps now require power, but Shoko is missing LV in two places, see media. I went over every other map and it seems like this is the only one with this issue.

**Screenshots**

TEG cold loop
image

Recycler radiators
image

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

Apparently he couldn't just break it into two pieces, goddamn.
Does a few things:
- Addresses bugs reported by players (mainly an unpowered bridge machine, and the accidental reversion of deltanedas' shoukou futureproofing. Therefore, fixes #1853
- Addresses Velcro's review (I hope I did things properly!)
- Adds the Station Anchor to a room between the burn chambers in atmos. It's CE only access, and is kinda like a gravgen - if this makes things bad, I have no idea how to map a station anchor and this is my first time, so I'm learning.
- Puts a bathroom in front of the bridge, millions must shit.
- Puts the AI in the AI sat, for AI testing, and AI things. I saw Velcro was considering mapping AI into his stations and so I give you this early PR.
## Why / Balance

- I didn't mean to do things that were in the review that I missed
- I didn't mean to accidentally revert Deltanedas' changes to Shoko-mos approved by Fish Inc.
- This shit needs a station anchor and I didn't do it last time because I wasn't really feeling up to it given the uh. More pressing modifications of moving Epistemics and everything around.
## Technical details

Map YAML, map prototype yaml.
## Media

Will send some when I get this out of draft. I forgot Fixgridatmos.
image
Shifted around AI sat.
Not pictured - station anchor room or bathroom.
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- tweak: Updated Shoko to have an anchor, and fixed bugs. Enjoy Little Port!

### CODE REVIEW

**Comment by MilonPL** [comment]
pro didn't link the issue

**Comment by ghost** [comment]
I forgot a seed extractor and have been told to rework the AI sat once more, so it's gonna happen

**Comment by deltanedas** [comment]
if you want to add the job youll have to remove the `setPreference: false` line in Roles/Jobs/Science/borg.yml so players can actually ready up for it

**Comment by IamVelcroboy** [comment]
> if you want to add the job youll have to remove the `setPreference: false` line in Roles/Jobs/Science/borg.yml so players can actually ready up for it

That could be done in its own PR. Because all the maps have borg slots. Apparently, no one has been able to ready for them the whole time?

**Comment by deltanedas** [comment]
the StationAi job to be clear, for whatever reason its in the same file as borg

**Comment by IamVelcroboy** [comment]
Oh... That makes more sense

**Comment by IamVelcroboy** [comment]
In map file change
```yml
    - type: Physics
      bodyStatus: InAir
      angularDamping: 10000
      linearDamping: 10000
      fixedRotation: False
      bodyType: Dynamic
 ```
 to
```yml
    - type: Physics
      bodyStatus: InAir
      angularDamping: 0.05
      linearDamping: 0.05
      fixedRotation: False
      bodyType: Dynamic
 ```

**Comment by deltanedas** [comment]
same for shuttle component

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
