### PR TITLE
Re-enable senior roles

### PR DESCRIPTION
**Pull request by redmushie**
# Please discuss [in the Discord thread](https://discord.com/channels/968983104247185448/1239984114916921394).

## About the PR
Re-enabled Senior roles for selection at round start. Also added missing localization keys.

Few points of note:

- ~~Yes, I know loadouts will break this. I will fix it when it's merged.~~ **Fixed!**
- You cannot select these roles unless individual maps specify them as selectable. I have not included those changes yet, though I'd be happy to do so.

## Why / Balance
Full details are [in the Discord thread](https://discord.com/channels/968983104247185448/1239984114916921394).

Copy-pasted OP from there:

> Howdy,
> 
> I would like to suggest re-enabling Senior roles at round start. My understanding is that:
> 
> 1. Upstream removed it;
> 2. Delta-V disabled it in favor of letting Heads promote at will instead.
> 
> My personal opinion is that they should be re-enabled. To me they make a great deal of sense from a Roleplay point of view. They let Heads know who they can expect more from (remember that it's opt-in!) and also give beginners a more clear direction of who to ask for help from and expect coaching from.
> 
> Personally I've experienced countless times that experience levels can vary WILDLY from one [person playing a non-beginner role] to the next, with no clear distinction if someone is a 100+ hour expert or has *just* unlocked a role.
> 
> From the people I've talked to, I found most people agree with them being valuable in MRP, and liking them to be re-enabled. But naturally I'm posting this to gauge interest and opinions.
> 
> Regarding the current implementation, I've to this day *never* seen any Head make use of this capability, nor seen anyone on the Crew Manifest with any role starting with "Senior" during my time on Delta-V. I think from an MRP point of view the vision made sense, but practicality means it just never happens.
> 
> Since the role prototypes are still in the source code, re-enabling them is as simple as changing four "false"s to "true"s, so practical feasability seems of no concern.
> 
> I want to hear what you think! I'm happy to open the PR if this is received positively.
> 
> # EDIT: Some clarifications
> - Apparently the box that was supposed to also contain Senior PDAs did not contain any, but that is being fixed in by <https://github.com/DeltaV-Station/Delta-v/pull/1196>. However, that would only contain *one* Senior PDA. Note also that the PDA **does not** actually set the role title for someone.
> - Several times I've read "Loadouts readd seniors": yes and no. They add senior COSMETICS, not Senior ROLES. I'm petitioning for entire ROLES here so that they are also clearly visible on the Crew Manifest.

## Technical details
I've simply set the prototypes to be enabled again, and added four missing localization keys.

### Engineering

<details>
<summary>Collapsed images</summary>

Content Client_OKp1Y4LQvK
Content Client_ScM06UzDVW
Content Client_xb4q7TVn5p
Content Client_mzDZhgCeXS
Content Client_h6QNeX1G4I

</details>

### Security

<details>
<summary>Collapsed images</summary>

Content Client_JhITehQTiV
image
Content Client_WeAsTmJCKT
Content Client_d3vBgBujo6
Content Client_3sarm1zhMH

</details>

### Epistemics

<details>
<summary>Collapsed images</summary>

Content Client_qsAZaWWMM3
Content Client_ix7emw39GH
Content Client_ydsmDquWHo
Content Client_UyWgEoj9T3
Content Client_wN8Vf1biUF

</details>

### Medical

<details>
<summary>Collapsed images</summary>

Content Client_exIl8kSs5i
Content Client_umxAwx4ppS
Content Client_fZ3PXhqJKc
Content Client_g6BGrPy8k8
Content Client_PiqvcI9bn9
Content Client_rNgGj9He5M

</details>

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None.

**Changelog**

:cl:
- tweak: Re-enabled Senior roles in Engineering, Security, Medical and Epistemic departments

### CODE REVIEW

**Comment by redmushie** [comment]
Added full loadout support. The post in wyci-suggestions seems largely positive so as far as I'm concerned it's ready for review!

**Comment by Axionyxx** [comment]
At this time, with the addition of loadouts and the incoming #1196 pr, I do not see a reason we need to bloat up playtime trackers, the lobby screen and force mappers to add additional slots.

Because of this, I'll reject this pr entirely at this time until we've seen how loadouts go in game.

**Comment by redmushie** [comment]
Hi Null, I ask you to reconsider. As your closing statement was quite brief I find it difficult to tell if you understood the PR and/or gameplay implications of loadouts and senior PDAs correctly, but it seems as there might be some misunderstandings. Allow me to try and clear some things up.

Senior roles have a few key purposes (I'm keeping these short for brevity's sake):
1. Teaching players new to a department;
2. Acting as middle management in the affected departments.

As someone who plays a Command role regularly, on high pop rounds it's practically impossible to lead a department by most metrics. Without going into too much detail, you're basically required for many high-stakes events and/or decisions, and are generally busy full-time **even without teaching rookies, which you are also expected to do.**

In addition, as a Command role it's incredibly difficult to reliably delegate tasks to your subordinates. In my experience, the main cause of this is simply inexperience on the subordinate's part. (Consider a "Station Engineer": they may have JUST promoted from Technical Assistant, or have 400 hours in the role. There is no way to tell.) There is simply no surefire way for you to know who you can rely on to handle advanced tasks in your department. Senior cosmetics can *aid* in this, but only if these "seniors" are _standing right next to you_, which rarely if ever happens.

My proposed solution is to all of these problems add Senior roles. They stand out visually (cosmetics), on the manifest (since they have a unique role), and have **full** departmental access (minus the Command-role exlusive rooms ofcourse). For example, a Senior Physician (Medical department) can also teach new Chemists. (This is also why they have playtime requirements in every sub-department before being unlocked.) And, as a result of being visible on the manifest with their unique job title, it makes it easy for both the department head **and** everyone else to identify these people as go-to's for handling advanced tasks that normally the department head is directly asked for, effectively offloading even more of the department head's too-great workload.

To address the things in your statement:
- Loadouts re-enable senior cosmetics. This does not give them meaningful access, and does not give them a unique title on the manifest. As a result, most of the advantages I described are not achieved via this method.
- #1196 adds a single Senior PDA to the PDA box. PDA's are also cosmetic items, and are **not visible** to anyone but the holder. They also do not dictate access or role title -- the ID card contained within PDA's do.
- Yes, mappers will have to update their maps at some point. While I agree this isn't ideal, it doesn't seems like a showstopper of any kind given that with the Shipyard merge several mappers updated their maps _within hours_ of you merging it.
- I can't judge the playtime trackers being "bloat" or not, but if they are in some way or another please provide it as review feedback with context to explain why that is.

I hope that clears things up, and you will reconsider. Thanks!

**Comment by Timemaster99** [comment]
Having both senior roles and available senior clothing would be redundant. A more streamlined solution would be to update loadouts such that choosing a Senior PDA would update your job title

**Comment by DangerRevolution** [comment]
> Hi Null, I ask you to reconsider. As your closing statement was quite brief I find it difficult to tell if you understood the PR and/or gameplay implications of loadouts and senior PDAs correctly, but it seems as there might be some misunderstandings. Allow me to try and clear some things up.
> 
> Senior roles have a few key purposes (I'm keeping these short for brevity's sake):
> 
> 1. Teaching players new to a department;
> 2. Acting as middle management in the affected departments.
> 
> As someone who plays a Command role regularly, on high pop rounds it's practically impossible to lead a department by most metrics. Without going into too much detail, you're basically required for many high-stakes events and/or decisions, and are generally busy full-time **even without teaching rookies, which you are also expected to do.**
> 
> In addition, as a Command role it's incredibly difficult to reliably delegate tasks to your subordinates. In my experience, the main cause of this is simply inexperience on the subordinate's part. (Consider a "Station Engineer": they may have JUST promoted from Technical Assistant, or have 400 hours in the role. There is no way to tell.) There is simply no surefire way for you to know who you can rely on to handle advanced tasks in your department. Senior cosmetics can _aid_ in this, but only if these "seniors" are _standing right next to you_, which rarely if ever happens.
> 
> My proposed solution is to all of these problems add Senior roles. They stand out visually (cosmetics), on the manifest (since they have a unique role), and have **full** departmental access (minus the Command-role exlusive rooms ofcourse). For example, a Senior Physician (Medical department) can also teach new Chemists. (This is also why they have playtime requirements in every sub-department before being unlocked.) And, as a result of being visible on the manifest with their unique job title, it makes it easy for both the department head **and** everyone else to identify these people as go-to's for handling advanced tasks that normally the department head is directly asked for, effectively offloading even more of the department head's too-great workload.
> 
> To address the things in your statement:
> 
> * Loadouts re-enable senior cosmetics. This does not give them meaningful access, and does not give them a unique title on the manifest. As a result, most of the advantages I described are not achieved via this method.
> * [Re-adds PDA variety to PDA boxes #1196](https://github.com/DeltaV-Station/Delta-v/pull/1196) adds a single Senior PDA to the PDA box. PDA's are also cosmetic items, and are **not visible** to anyone but the holder. They also do not dictate access or role title -- the ID card contained within PDA's do.
> * Yes, mappers will have to update their maps at some point. While I agree this isn't ideal, it doesn't seems like a showstopper of any kind given that with the Shipyard merge several mappers updated their maps _within hours_ of you merging it.
> * I can't judge the playtime trackers being "bloat" or not, but if they are in some way or another please provide it as review feedback with context to explain why that is.
> 
> I hope that clears things up, and you will reconsider. Thanks!

Loadouts will let you pick senior clothing after X amount of hours is reached, and changing the PDA would update your ID.

**Comment by TheJacken** [comment]
I personally would love to see this reconsidered, as someone who probably has most of their playtime as engie, i have access to CE but in all that time i still cannot reliably do a TEG which is critical for all maps except two on the server i play on, as i need something i can look back on most of the time to remember. having someone that is a very clear "senior" in that area would alleviate a lot of stress for me to either have them over from me to do the TEG themselves or take the time with me to teach me proper and have something reliable to look back on if able.

I also agree with the last two comments, where using a senior loadout would change the players ID role would not bloat the in game UI with serval different roles.

I do hope the staff that reviewed this or any other staff that may look on this would reconsider, as it would not just help struggling regulars but also help keep new players in as they will not be as intimidated by Deltas systems as they have a clear teacher that is willing to help if asked.

**Comment by redmushie** [comment]
> Having both senior roles and available senior clothing would be redundant. A more streamlined solution would be to update loadouts such that choosing a Senior PDA would update your job title

The PR clearly makes senior clothing only available for the senior role. Also, that would not be a "more streamlined", it rather introduces several problems:
- Making a PDA magically alter an ID implicitly adds for massive risk as it basically turns into a portable ID card computer that instantly gives someone full departmental access, even after a Command role has revoked it.
- If you choose Station Engineer and forget you have a senior PDA selected, you are suddenly a Senior Engineer with vastly different responsibilities.
- You could have a Senior PDA selected but not a Senior outfit, causing confusion.
- This would require custom code rather than just adding a few YML files like this PR does.

**Comment by redmushie** [comment]
> > *snip*
> 
> Loadouts will let you pick senior clothing after X amount of hours is reached, and changing the PDA would update your ID.

Yes, you can have cosmetics. No, cosmetics solve virtually none of the problems I've brought up. Please read my post reacting to the closing of the PR fully before reacting.

**Comment by redmushie** [comment]
Also, PDA does not change your ID or access, as shown here: 
image

**Pull request closed without merging**
