### PR TITLE
Rebalance Changes For Desword

### PR DESCRIPTION
**Pull request by Tryded**
## About the PR

Lower Attack Rate to the same as Esword
Heightened the reflection chance for Energy shots to 90%
No more structural damage
## Why / Balance

Was originally way too OP to have high damage and high attack speed (Kill time is now 3 seconds instead of 2 seconds which is difference between countering with a gun/calling for help and dying
Can't upstream because upstream straight up removed it
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Tryded** [comment]
The reflection rate *can* be lowered

**Comment by Tryded** [comment]
> The reflection rate _can_ be lowered

However again, this can be easily countered by a ballistic weapon of any sort or literally a bar of soap if they didn't buy no slips.

As for nukies, I'm unsure of exactly what caused it to be unbalanced due to me not knowing what round it is, however hearing from others I think it was because the nukie was either holding normal eswords in their pockets (Potentially being able to reflect even in pockets causing ballistics to be reflected), or there might just be some large oversight that I didn't think of. 

Another easy way to counter people with deswords is to use bolas, or to use explosives/chems

**Comment by DangerRevolution** [comment]
> The reflection rate *can* be lowered

Why is the reflect going to 90%?

**Comment by DebugOk** [comment]
This item is disabled in an upcoming update, and no balance changes will be accepted

**Pull request closed without merging**
