### PR TITLE
some small pebble changes, as well as a christmas variation of pebble

### PR DESCRIPTION
**Pull request by Carolyn3114**
## About the PR

mainly adds a christmas version of pebble into the map files, titled "pebble_christmas", for easy use to swap between 

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Check out issue [#508](https://github.com/DeltaV-Station/Delta-v/issues/508)

Also, remove the xmas file and just send it to me in Discord. I'll add it to the PR of other maps.

**Comment by Carolyn3114** [comment]
> Check out issue [#508](https://github.com/DeltaV-Station/Delta-v/issues/508)
> 
> Also, remove the xmas file and just send it to me in Discord. I'll add it to the PR of other maps.

okay

**Comment by Colin-Tel** [comment]
the last action on this PR was like a week ago, why the heck are tests still not done?

**Comment by IamVelcroboy** [comment]
Weird. At this point just merge the xmas maps, or it will conflict. I thought this had already been merged 🤷‍♂️

**Pull request closed without merging**
