### PR TITLE
Adds Chibi Station

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Adds a teeny-tiny pipsqueak station for crew of at most 10 in number.

## Why / Balance

This map addresses the need for a very-low population map that can be played with very few players. It aims to achieve this goal by reducing excess jobs that don't have a real use in very-low-pop games, instead focusing on the core departments and the minimum of what they really need.

The soft cap of this map is 10 players, but there are 20 total job slots (not including passenger) in case of additional players.

## Media

Chibi-0

**Changelog**

:cl:
- add: Chibi station is now available for play with a soft population cap of 10!

### CODE REVIEW

**Comment by jimmy12or** [comment]
As a botany player, I would request that if we can only have 2 vending machines, that you replace the clothing one with the one that gives tools. it's much more useful especially with loadouts added on now.

**Comment by Colin-Tel** [comment]
> As a botany player, I would request that if we can only have 2 vending machines, that you replace the clothing one with the one that gives tools. it's much more useful especially with loadouts added on now.

Works for me

**Comment by deltanedas** [comment]
some things i noticed:
- salv airlock need or gates so it doesnt get trolled like every round on a map that doesnt use them
- salv doesnt refill spaced rooms they dont need an air canister, replace with oxygen and nitrogen cans
- missing cmo, mysta, lo lockers for when it rolls traitor and they physically cant do their objectives
- teg could do with another plasma can so you dont need to split it really thin, realistically there should be 1 port that you can pump into mixer and loops if you want to reduce wasted plasma never being used in the hot loops port
- teg cold loop does basically nothing, replace with either a freezer or parallel pumped setup like on some other maps

an idea i had was have engi start on EA, vving it should stay active when it gets loaded. so if theres no engi they get power and if there is they can use remote or bolt it closed depending on ce/engi

**Comment by Bonktrauma** [comment]
80 pop on chibi when?

**Comment by Colin-Tel** [comment]
> * salv airlock need or gates so it doesnt get trolled like every round on a map that doesnt use them

I’m sorry, I have no idea what this means.

> * salv doesnt refill spaced rooms they dont need an air canister, replace with oxygen and nitrogen cans

My line of reasoning was using it for the jet pack, but you’re right, I could just give them N2 and O2
> * missing cmo, mysta, lo lockers for when it rolls traitor and they physically cant do their objectives

Counter points:
1. The map’s max pop is too low for the gamemode.
2. I would rather simply map the items in as opposed to having a bunch of lockers and dressers for absent roles.

> * teg could do with another plasma can so you dont need to split it really thin, realistically there should be 1 port that you can pump into mixer and loops if you want to reduce wasted plasma never being used in the hot loops port

Sure I could give them another plasma can.

> * teg cold loop does basically nothing, replace with either a freezer or parallel pumped setup like on some other maps

I don’t understand this.

> an idea i had was have engi start on EA, vving it should stay active when it gets loaded. so if theres no engi they get power and if there is they can use remote or bolt it closed depending on ce/engi

I’ve messed around with this, and the last time I tried, loading a map that has a door with EMAC enabled via either vv or the remote cannot be un-EMACd, so I won’t be doing that.

**Comment by deltanedas** [comment]
> I’m sorry, I have no idea what this means.

2 logic gates, wire each side's doors status ports to logic gates input and its outputs to the opposite side's bolt ports

>  using it for the jet pack

jetpack gas has nothing to do with thrust it makes, being pure oxy or nitrogen just lets you breathe it optimally

> The map’s max pop is too low for the gamemode.

i thought its like 5 minimum for traitor

> I don’t understand this.

just copy shoukou

> loading a map that has a door with EMAC enabled via either vv or the remote cannot be un-EMACd, so I won’t be doing that.

try having it bolted open then, that should work

**Comment by Colin-Tel** [comment]
> 2 logic gates, wire each side's doors status ports to logic gates input and its outputs to the opposite side's bolt ports

My bad, yeah I've had that done before you brought it up.

> jetpack gas has nothing to do with thrust it makes, being pure oxy or nitrogen just lets you breathe it optimally

addressed

> i thought its like 5 minimum for traitor

I forgot where to check 😭 

> just copy shoukou

Got it.
image

> try having it bolted open then, that should work

It does!
image

**Comment by Colin-Tel** [comment]
@deltanedas I believe I addressed the lack of traitor/thief objectives, and thankfully I did it without mapping in all the dressers/lockers

**Comment by deltanedas** [comment]
lgtm then :trollface:

**Comment by Bonktrauma** [comment]
Please tell me the evac shuttle is tiny

**Comment by Colin-Tel** [comment]
> Please tell me the evac shuttle is tiny

It's huge :trollface:

**Comment by Bonktrauma** [comment]
> > Please tell me the evac shuttle is tiny
> 
> It's huge :trollface: 

Noooo

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
