### PR TITLE
Completely rework Lighthouse Medbay

### PR DESCRIPTION
**Pull request by SaphireLattice**
## About the PR
The entirety of Lighthouse's Medbay. Also a bit of outside, because the boxing arena area felt like a dead end

## Why / Balance
The medbay felt weirdly wasteful in terms of space while at the same time being cramped. Practically every room was shaped very oddly. There was a really frustrating doorway to chemistry that always caused one to miss the door. Also there was only one chemist workstation despite it being a station way bigger than Shoukou, etc.

## Technical details
Mapping only.

## Media
Autogenerated preview should pop up?

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Completely rework Lighthouse's Medbay

### CODE REVIEW

**Comment by Radezolid** [comment]
If I'm not wrong the map render bot is broken so no map generated.

**Comment by SaphireLattice** [comment]
Noted, will provide screenshots later!

Also realized I might have went a bit quickly with all of this and didn't quite ask the map maintainer if I could do a full rework. Oops. Would really like a confirmation or denial on this eventually!

Current checklist of things to do:
- Remove some morgues, add details (locker)
- DRAINS, MORGUE AND CHEM
- Something about firelocks, escape routes? 
- Remove maints firelock
- Remove one of the firelock sets in reception/on-call room, as that might be over the top?
- Nudge vent & scrubber around in the patient ward, fix up the isolation of the yellow area
- Add tables in yellow area? 
- Add details to surgery
- Trim the cameras, too redundant right now, too many
- Actually set up the cameras (right click > "setup")

**Comment by SaphireLattice** [comment]
Haven't touched the firelocks in reception/rest area as I honestly like them. Removed the maints one though. 

Morgue's still untouched, as this map is 20-65 pop so I think it's a pretty good size

I think it's ready enough?

Screenshots of changes (not map renderer, just aghost on the map):
image
image

**Comment by deltanedas** [comment]
does cryo even have a distro pump anywhere??? also those filters arent inline so they will overpressurize it

**Comment by SaphireLattice** [comment]
The distro pump decided to get hidden by the catwalk. I have no clue how to drag the damn thing out from under it.

Uh, don't get the filter thing? Oh yeah I can always flip them around here

Badly sketched piping diagram with mouse in a screenshot tool. (Actually I lied here, the pipes merge into waste under that catwalk, rather than under the wall. Also there's a scrubber under the closet that connects to them)
image

**Comment by deltanedas** [comment]
filters being inline means that the inlet and outlet is the same pipe network, it prevents them overpressurizing due to atmos speedup

**Comment by SaphireLattice** [comment]
Got it. I *think* this should be a valid configuration matching every other cryo around, and not have it overpressurize?

**Comment by Radezolid** [comment]
Mat movement

Maybe move the materials to the storage and the plasma to chemistry.

image

You could also remove the second filter and make the cryogenics person switch according to what species is being treated.

**Comment by SaphireLattice** [comment]
The plasma and metal/glass are "misplaced" as a mapped in joke, but if it's too much, can put them in proper enough place.

Dual filter cryo setup seems to be a thing on almost every map: Shoukou, Arena, Pebble (which has volume pump input so *that*'s for sure overpressurized), Hammurabi has *three* filters, etc. Glacier seems to be the only one that has them parallel. And I have *no clue* what's going on with Hive's cryo at all.

**Comment by deltanedas** [comment]
glaciers cryo and current lighthouse cryo have filters like that so they never overpressurize thats why

**Comment by SaphireLattice** [comment]
Will test the filter setup as is, and if it overpressurizes, will try to fix.

Can I keep the swapped around materials or should I remove that joke?

Any other outstanding issues? Specifically want to know what stuff might be blocking a green light and merge.

Current list: 
- Cryo setup overpressure check/fix. Hope that I can keep dual filter (as a lot of maps have it, again), but worst case I'll just put a single filter in instead. Rearranging cryo for parallel filter setup would require putting the distro pump outside, or expanding the cryo itself.
- Bring back the welding fuel dispenser to chemistry
- See if I can fit in a chemistry wall locker, in a spot where it will actually get used
- *Maybe* rearrange chem so that a hotplate is reachable by either chemist? Not sure I want to optimize that is already a rather stationary job
- Touch up marking in chemistry under the sink as there was a feedback of being annoyed by the marking in question on Discord. Maybe.

**Comment by Radezolid** [comment]
I just pointed the mats in case of error, I think CMOs can just grab them shift start and place the mats in the fab but i'm not a maptainer. Just giving my toughts.

**Comment by Colin-Tel** [comment]
> The distro pump decided to get hidden by the catwalk. I have no clue how to drag the damn thing out from under it.

pumps will always display beneath catwalk, the solution is to not have catwalk on the same tile

**Comment by SaphireLattice** [comment]
image
"Oh hey the cryo loop is at 101 kpa, that's not bad!"
"Wait how much- what the fuck"

So uh... does that... happen with every single dual filter setup that is currently mapped in? If yes, oh fuck, ow.

**Comment by MilonPL** [comment]
> So uh... does that... happen with every single dual filter setup that is currently mapped in? If yes, oh fuck, ow.

1000L/s noobtrap
99% of doctors fail to set up cryo because of this one simple thing!!

**Review by IamVelcroboy — APPROVED** [review]

**Comment by Eagle0600** [comment]
> So uh... does that... happen with every single dual filter setup that is currently mapped in? If yes, oh fuck, ow.

Yes, it does. Set the filters to something low, like 50 litres per second, and it'll be fine.

**Pull request merged**
