### PR TITLE
Dreammyrr patch 3

### PR DESCRIPTION
**Pull request by Dreammyrr**
## Requirements

- [ ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by therealDLondon** [comment]
I dont mean this to come across as rude, but what is all this?

**Comment by Colin-Tel** [comment]
idk why you opened like 5 PRs for this, but please keep it to one.

Also what the heck is this

**Comment by deltanedas** [comment]
please stop

**Comment by Tropica1Owl** [comment]
I'm sorry for everyone involved 

> I dont mean this to come across as rude, but what is all this?

Brazilian songs, portuguese translation, and surgery
I had no hand in this other than the surgery, and it's really funny that he just tried pr'ing his whole fork from top to bottom.

**Pull request closed without merging**
