### PR TITLE
Implmement trading post and finish shuttle refactor cherry-pick

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
See https://discord.com/channels/968983104247185448/976726219875831828/1215605251885899796

WIP, I still need to clean the trading post code

**Changelog**
:cl:
- add: Added the trading post, cargo technicians will now have to travel on the shuttle to collect their goodies
- add: Merged the shuttle console refactor. This may bring some bugs
- tweak: The trading post will give you cash instead of directly adding funds to the stations account. To turn this into money you can spend, click the cargo requests computer while holding the spesos

### CODE REVIEW

**Comment by DebugOk** [comment]
I'll end up squashing all my changes together so I can merge commit this

**Comment by DebugOk** [comment]
Its missing markers pretty much everywhere but in this case its whatever, these files will probably always conflict, and require manual merging.

I might add them if I feel like it, but I dunno

**Comment by DebugOk** [comment]
I'll need to check over my changes again later, but I'm marking it as ready so tests run and stuff

**Review by VMSolidus — COMMENTED** [review]
I'm not exactly going to approve or deny this, since it's a Wizden kinda thing upstream. My own review would just be does it work or not, and does it break anything? Whether it breaks things isn't something I can easily test.

**Comment by DebugOk** [comment]
The only thing that matters are changes done in commit 76d0641 as those aren't original

**Pull request merged**
