### PR TITLE
Add new lobby art

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Adds the Delta V lobby art contest winning pieces. 

Note: not sure who to attribute to and what specific license to give them. Will un-draft when I have that info

## Why / Balance
We cool like that.

## Technical details
n/a

## Media
station-crew_template-ver
DELTAVCONTEST
Corporate_Rats

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
n/a

**Changelog**
n/a

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Un-drafted. Someone contact the lawyer and tell them review the license part

**Comment by BlitzTheSquishy** [comment]
> Un-drafted. Someone contact the lawyer and tell them review the license part

find a way to ping ryan

**Comment by Aikakakah** [comment]
I'll be going CC-BY-4.0. for Corporate Rats, but I'm asking the other two winners what they want for theirs before I request changes.

**Comment by Colin-Tel** [comment]
So if this is undrafted, is this ready to go, @IamVelcroboy ?

**Comment by Colin-Tel** [comment]
wait nvm I thought this was someone saying "we need to get Ryan's opinion before merging" lol

> find a way to ping ryan

**Review by Colin-Tel — APPROVED** [review]

**Comment by Aikakakah** [comment]
The other art winners are fine with going CC-BY-4.0. for the record.

**Pull request merged**
