### PR TITLE
Robotics Airlock

### PR DESCRIPTION
**Pull request by Unkn0wnGh0st333**
## About the PR
Adds the Roboticist Airlock

## Why / Balance
Was requested due to https://github.com/DeltaV-Station/Delta-v/pull/2029 being PRed and https://github.com/DeltaV-Station/Delta-v/pull/2028 merged

## Technical details
Yaml and Spriting

## Media
image

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
The door instantly gibs you 😈
Also slightly rushed to do yaml due to dental appointment

**Changelog**
🆑 
add: Added Robotics Airlocks, one step closer to the Roboticist Job.

### CODE REVIEW

**Review by deltanedas — APPROVED** [review]
the shadow factory rises

**Comment by Unkn0wnGh0st333** [comment]
> the shadow factory rises

damn son this has to be my personal record of fastest merged pr

**Comment by BlitzTheSquishy** [comment]
The pain of them using the cyborg icon and not the robotics one

**Comment by deltanedas** [comment]
robotics icon is a settings icon, this is completely unambiguous

**Comment by Unkn0wnGh0st333** [comment]
> The pain of them using the cyborg icon and not the robotics one

I was told cyborg icon better, yell at deltanerdas

**Pull request merged**
