### PR TITLE
add prison headsets to secdrobe and prison lockers

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
3 of them

## Why / Balance
theres no actual way to get them before this

## Technical details
no

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: The SecDrobe now has Prison Headsets. Prisoners have rights too!

### CODE REVIEW

**Comment by Bonktrauma** [comment]
the encryption keys come in a box in wardens locker , but the headsets themselves are not, just like every other headset

**Comment by deltanedas** [comment]
having to either:
- get a screwdriver to take out keys of a sec headset
- wait 5 minutes for hop to get one, if theyre alive
- not give a headset

are all not ideal

**Comment by Bonktrauma** [comment]
> having to either:
> - get a screwdriver to take out keys of a sec headset
> - wait 5 minutes for hop to get one, if theyre alive
> - not give a headset
> 
> are all not ideal

Warden has an entire box of prisoner encryption keys

**Comment by deltanedas** [comment]
thats just for the prison key it doesnt have any headsets specifically

**Comment by Bonktrauma** [comment]
> thats just for the prison key it doesnt have any headsets specifically

Most headsets are unobtainable unless you spawn with one

**Comment by deltanedas** [comment]
almost every headset is either in a vending machine or locker

**Comment by Bonktrauma** [comment]
> almost every headset is either in a vending machine or locker

Uhh, add them to prison lockers?

**Review by IamVelcroboy — APPROVED** [review]
Sure, why not

**Pull request merged**
