### PR TITLE
add 1h requirement to cargo tech

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
pro raiders keep using cargo as a means to get free salv shit and bomb med etc
also they should know controls and stuff before demanding epi fill out a 8 page request form

### CODE REVIEW

**Comment by Lyndomen** [comment]
Sounds good to me. Waiting on @therealDLondon

**Review by Lyndomen — COMMENTED** [review]
Great

**Review by Lyndomen — APPROVED** [review]
Approved by both of us.

**Comment by deltanedas** [comment]
your review isnt real so someone else still has to approve :trollface:

**Review by Colin-Tel — APPROVED** [review]
I'm real, and I say merge it!

**Pull request merged**
