### PR TITLE
make wrecks cost mining points to pull

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
wrecks now cost 1000 mining points to pull
it also means borgs cant pull wrecks :trollface:
could let mining borgs store mining points on their chassis in the future

## Why / Balance
you can easily get 2-3k points from 1 asteroid pull so this isnt a serious nerf to real gamers, just shitters that only pull wrecks to try get funny gamer loot and let the station starve, now they are actually forced to mine :smiling_imp:  :smiling_imp:  :smiling_imp:  :smiling_imp: :trollface:

## Technical details
Cost field on ISalvageMagnetOffering that makes it remove mining points when you pull it

## Media
too broke...

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- tweak: Pulling wrecks on the salvage magnet now costs mining points. GO MINE!!!

### CODE REVIEW

**Comment by Avalon-Proto** [comment]
Evil but effective. granted they dont even need to pull a rock they can just hit the shuttle

**Review by Lyndomen — APPROVED** [review]
Direction approved for a test merge, want to see how it plays out over 24 hours.

**Comment by fow111** [comment]
why not space debris too?

**Comment by Avalon-Proto** [comment]
> why not space debris too?

Cause space debris have material useful to the station in the form of scrap etc while wrecks are *purely*.loot

**Pull request merged**
