### PR TITLE
ENTITY WHITELIST TYPO OPS TAKE 9

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

FUCK

## Why / Balance

IF YOU IGNORE THE 95% OF THREAD TIME SPENT WAITING ON LOW LEVEL SEMAPHORES IT'S THE FUCKING ENTITYWHITELIST FROZEN DICTS AND FINDVALUE DOGSHIT HOLY FUCK

image

image

### CODE REVIEW

**Comment by MilonPL** [comment]
I REALLY HOPE THIS IS THE LAST ONE

**Comment by Stop-Signs** [comment]
are....are you ok milon?

**Comment by sleepyyapril** [comment]
Yeah... are you okay?

**Review by deltanedas — APPROVED** [review]

**Comment by deltanedas** [comment]
DR ANIMAL says, "THIS NORMAL."

**Pull request merged**
