### PR TITLE
Fixes missing harpy hardsuits

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

Fixes issue #1751 (when I get it out of draft.) At least it is intended to do that.
## Why / Balance

Adds Harpy versions of suits for specific edge-case usage (ERT, being Santa, using the CC hardsuit, being a mime, wearing an NTSRA suit instead of a salv suit because they're out of normal spationaut suits, doing fishops.)
No I am not doing this for the ling suit, the pirate suits, wizden sec suits, the RE machine suits or the wizard. (Well, the wizard might be done later but not in this PR.) The majority of those are not seen in game except for the RE machine suits - and those I'm not sure how I feel about them.
## Technical details

Sprites and meta.jsons and a touch of yaml. Just a dash. A little bit.
## Media
image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Wing covers have been installed on various ERT suits and some others, and they now fit harpies.

### CODE REVIEW

**Comment by ghost** [comment]
NTRSA suit is animated and that gave me less motivation to touch that, so they can be sleeveless and not fit 😿 So now it's just santa and the mime I have left
I also fixed the RSI issue (I love accidentally putting png at the end of the name.)

**Comment by ghost** [comment]
Fuck Santa. My wrists hurt.

**Comment by ghost** [comment]
Okay now it just needs a review and it's good to go. PR has media now.

**Review by deltanedas — APPROVED** [review]

**Comment by ghost** [comment]
Yippee!

**Pull request merged**
