### PR TITLE
Update micro.yml

### LINKED ISSUE #1747: micro kitchen freezer isnt a freezer
## Description
- no directional fans so you cant keep cold in
- no freezer for cooling the room
- no freezer locker either

all meat will rot here

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Fixes #1747 

## Media

image

**Changelog**

no cl no fun

### CODE REVIEW

**Comment by deltanedas** [comment]
use freezer atmos fix markers and fixgridatmos

**Comment by Colin-Tel** [comment]
> use freezer atmos fix markers and fixgridatmos

the confusing part is that it has always had freezer markers, and I'm certain I've used fixgridatmos after rearranging the hallway.

I'll double check

**Comment by Colin-Tel** [comment]
image

it cold

**Comment by deltanedas** [comment]
lgtm then

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
