### PR TITLE
job whitelists panel !!!

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
biggest admin update since bwoink.ogg

you can use the `jobwhitelists` command with a username/guid or use the Job Whitelists button in their player panel

toggling a department sets all roles in it to whatever the department checkbox is changed to

## Why / Balance
:fish: :coin:

## Technical details
- JobPrototype's Whitelisted field changed to take blanket whitelist into account so all the bozos who are whitelisted get grandfathered in to every role
- WhitelistRequirement removed from all jobs and replaced with `whitelisted: true`

## Media
player panel

job whitelist panel

not whitelisted so no hossing

whitelisted so it lets me see requirements

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
DELTAVADMIN:
- add: Added the Job Whitelists panel for managing individual job whitelists.

### CODE REVIEW

**Comment by Axionyxx** [comment]
DELTAVADMIN or merge conflict :trollface:

**Comment by BlitzTheSquishy** [comment]
big if true

**Comment by noctyrnal** [comment]
Merge for fish ops token :blunt:

**Comment by MilonPL** [comment]
HOLY SHIT IT'S FINALLY REAL

**Comment by Piras314** [comment]
:superhero:

**Pull request merged**
