### PR TITLE
Prober and Drainer crafting + Prober sounds

### PR DESCRIPTION
**Pull request by FluffiestFloof**
## About the PR

Brings back the ability to craft probers and drainers.
Drainers are made at a lower cost until golemancy is brought back.
Probers now makes their funny sounds once again.
Probers/Drainer now have their damageset back.
Also re adds the psionic guidebook which mentions how to make normality crystals.
Also adds normality crystals back at a lower cost until golemancy is brought back.

## Why / Balance

Bluespace crystal had pretty much no use and probers/drainers are quite useful to be able to be crafted.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Glimmer Prober and Drainer are craftable once again.
- fix: Fix Probers not making sounds depending on the glimmer levels.
- add: Adds back the Psionic guidebook.

### CODE REVIEW

**Comment by VMSolidus** [comment]
I do recall having a rather lengthy discussion about removing the Glimmer drainer entirely. When talking with JJ during the rebase psionics development, the main solution we came up with was having "defeating" glimmer events as the main mechanic for reducing glimmer. Because lets be honest, when was the last time you saw someone make a prober?

**Comment by deltanedas** [comment]
never saw a drainer get built once, at least when you could just craft normality crystals in the techfab youd see them getting some use by smart mystas

**Comment by IamVelcroboy** [comment]
> when was the last time you saw someone make a prober?

Antags can make hidden probers when they have the glimmer objective. I've seen probers constructed to bypass the research limit or just speed it up early game.

**Comment by deltanedas** [comment]
i think evilexecutive meant drain, rogue probers are very common

**Comment by IamVelcroboy** [comment]
> i think evilexecutive meant drain, rogue probers are very common

Ahh, are drains not a good method of combating rogue probers? It's been a while since I played Epi but I remember building them when glimmer was sort of new.

**Comment by deltanedas** [comment]
they were back in the day but now you have to 1) find and kill a glimmer mob like a revenant 2) do a very complicated chemistry reaction with a bunch of stuff including ectoplasm to only get like 1 crystal??? (might be wrong but if im not thatd mean killing ~3 revs to make a single drain)

instead the much prefered method is just rpging the prober(s)

**Review by DebugOk — DISMISSED** [review]
Imo drainers are stupid expensive, but eh

**Comment by FluffiestFloof** [comment]
> Imo drainers are stupid expensive, but eh

We could always make it slightly less expensive.

**Comment by DebugOk** [comment]
> > Imo drainers are stupid expensive, but eh
> 
> We could always make it slightly less expensive.

I think they should be constructable without killing 50000 revenants, but still expensive enough that they cant build 6 at roundstart

**Comment by FluffiestFloof** [comment]
> > > Imo drainers are stupid expensive, but eh
> > 
> > 
> > We could always make it slightly less expensive.
> 
> I think they should be constructable without killing 50000 revenants, but still expensive enough that they cant build 6 at roundstart

AFAIK, revenant only spawns 1 Ectoplasm and you need 10 ectoplasm for 1 normality crystal. Since we don't have the ability to create soulcrystals (golemnization, they are 50 ectoplasm each) yet, to get 1 drainer you need to kill 50 Revenant.

I think until golems, making the Normality Crystals cheaper (1 ectoplasm) so you'd _only_ have to kill 5 Revenant for one Drainer could be less of a grind.

**Review by Colin-Tel — APPROVED** [review]
Looks good to me, let's see how it pans out.

**Pull request merged**
