### PR TITLE
Fluffy tail for felinids

### PR DESCRIPTION
**Pull request by Adrian16199**
After 9 years. I finished it.

(Requires Phil's approval, will put it to ready for review as soon as he gets to see fully the fully finished PR)

## About the PR

Adds a fluffy tail for felinids

## Why / Balance

Because Fluffy tails and lack of love for felinids

## Technical details

adds 5 files = 2 pngs, meta.json, ftl and yml.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added a fluffy tail for the felinids.

### CODE REVIEW

**Comment by DebugOk** [comment]
> Resources/Textures/DeltaV/Mobs/Customization/felinid_tails.rsi: felinid_fluffy_tail_rings: mismatching total durations between state directions: 2.4, 2.4, 1.8, 1.8

Make sure to fix your timing before marking it as ready

**Comment by Adrian16199** [comment]
> > Resources/Textures/DeltaV/Mobs/Customization/felinid_tails.rsi: felinid_fluffy_tail_rings: mismatching total durations between state directions: 2.4, 2.4, 1.8, 1.8
> 
> Make sure to fix your timing before marking it as ready

Thing is, if im lookin at this right, then its the fact that half of it dont have the same amount of numbers and that was kinda intentional, the side sprites have less animations compared to the back sprites which is why I have given less numbers so it loops correctly thus why they are diferent, will it be an issue? I havent noticed any issues ingame when I was testing it. Unless its completely about somethin else that went over my head.

**Comment by DebugOk** [comment]
> > > Resources/Textures/DeltaV/Mobs/Customization/felinid_tails.rsi: felinid_fluffy_tail_rings: mismatching total durations between state directions: 2.4, 2.4, 1.8, 1.8
> > 
> > 
> > Make sure to fix your timing before marking it as ready
> 
> Thing is, if im lookin at this right, then its the fact that half of it dont have the same amount of numbers and that was kinda intentional, the side sprites have less animations compared to the back sprites which is why I have given less numbers so it loops correctly thus why they are diferent, will it be an issue? I havent noticed any issues ingame when I was testing it. Unless its completely about somethin else that went over my head.

It's a test fail so yes, it's an issue.

Just have the speeds be consistent, use the same sprite several times for all I care

**Comment by Adrian16199** [comment]
Well hoppity damn, understandable. 👍

**Comment by DebugOk** [comment]
> Well hoppity damn, understandable. 👍

I'm not too familiar with the sprite system without looking at the code, but I suppose they wouldn't have that check without reason

**Comment by leonardo-dabepis** [comment]
in terms of sprite work, I'm having a hard time seeing what the sprites look like. I would like to see a screenshot of these in the dev environment and animated before I approve. It's good to make more customization options for felinids though

**Comment by leonardo-dabepis** [comment]
After seeing a clip of the tail and markings animated on Discord, I would like the stripes animation to be changed. Particularly from the back view of it, the stripes look visually unclear while animated. The baseline fluffy tail sprite looks fine though. If you want, I can help you out with making the stripes look clearer on Discord.

**Comment by Adrian16199** [comment]
It would be my pleasure if you could help truly.

**Pull request merged**
