### PR TITLE
Removes the "Raise Glimmer" objective

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Comments out the "Raise Glimmer" objective.
## Why / Balance

This objective is historically a bore for people. It's not easily completed, and it has sort of existed just for the sake of giving antagonists an objective that has something to do with the glimmer system. 
## Technical details

YAML
## Media

N/A
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

N/A
**Changelog**

:cl:
- remove: Removed the "Raise Glimmer" objective for traitors.

### CODE REVIEW

**Comment by SolStar2** [comment]
I think instead of removing raise glimmer objective I would give more tools to be able to do it. Like buying rouge probers or make a way to do sacrifices that raise glimmer instead of lower glimmer.

**Comment by Monotheonist** [comment]
> I think instead of removing raise glimmer objective I would give more tools to be able to do it. Like buying rouge probers or make a way to do sacrifices that raise glimmer instead of lower glimmer.

I'm gonna agree on that one, I feel like there's some interesting interactions that can be had with the Glimmer Prober, but also it literally has nothing but an antagonistic purpose. I feel like the entirety of this discussion comes with a greater conversation about what we wanna do about psionics, really, since currently the prober exists to probe the noosphere and then blow up when it can't handle the mind energy, and building spares of it gives it an antagonistic purpose that's this objective.

I'd love to see a sacrifice based objective, but like most novice contributors, I have no idea how that'd logistically work in terms of like. Coding it. It's also something that'd suit cultists or something and would be a good gateway to roleplaying one until that gamemode becomes a thing, *if* it does.

**Comment by Radezolid** [comment]
> I think instead of removing raise glimmer objective I would give more tools to be able to do it. Like buying rouge probers or make a way to do sacrifices that raise glimmer instead of lower glimmer.

Sacrifices are usually public. "Chaplain sacrificed someone and glimmer went up, they are valid".

The rogue probers it's easy, just do the oracle's tasks and build one hidden behind reinforced walls.

**Comment by Avalon-Proto** [comment]
> Sacrifices are usually public. "Chaplain sacrificed someone and glimmer went up, they are valid".

A lot of maps have altars hidden away in other areas of the station

> The rogue probers it's easy, just do the oracle's tasks and build one hidden behind reinforced walls.

It's easy to do as epi but sec is gonna wonder why some random person is asking for a single bullet from the oracle. Or epi is gonna wonder why you are asking for x for the oracle

**Comment by Radezolid** [comment]
> A lot of maps have altars hidden away in other areas of the station

I mean, you would be RRing someone in maints or some other weird place that people are most likely not going to follow you.

> It's easy to do as epi but sec is gonna wonder why some random person is asking for a single bullet from the oracle. Or epi is gonna wonder why you are asking for x for the oracle

EPI gives away anything you ask as long as you got the mats for it.

**Comment by deltanedas** [comment]
the biggest factor in glimmer objective isnt what the traitor does, but rather what epi does. if they leave prober on roundstart it makes it 10x easier to get 500 glimmer compared to turning it off. this objective is basically an anti objective for epi that they cant see

**Comment by beck-thompson** [comment]
I think the reason the glimmer objective is not fun is because it is a very low roleplay objective. All the other objectives require some level of player interaction, but for raise glimmer you really don't need to interact with anyone (And this won't really change even if they get more tools).

**Review by deltanedas — CHANGES_REQUESTED** [review]
dont comment them out just remove them

**Review by deltanedas — DISMISSED** [review]

**Comment by Colin-Tel** [comment]
Wrong PR >w<

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
