### PR TITLE
Shoukou maintenance update.

### PR DESCRIPTION
**Pull request by Adrian16199**
Also yes, I would like someone to review the map while im doin the finishing touches as it changes quite a bit.
Maintenance expanded in security (Yes, i did move the entire prison[pain]) and logistics 
Powercell recharger in robotics
Redid piping in logistics.
Shuttle timer in both evac and arrivals
Removed laika
Fixed logistic's intercom being wrong way.
Redid wiring in security to go thro new maintenance.
EVA has been added to evacuation
Evacuation pod has been moved bit to the right.
Moved slimy to engineering instead of CE's office
Moved Shiva to security to proudly guard the HoS's office.
Upper solar's became a bit more broken
Added janitorial service lights
>engineering
>security
>medical
>Epistemics

Filling cabinet for detective
Janitorial service lights
Changes disposal pipe in bar to go different way
Changes piping 
Man im tired.

## About the PR

Security/logistic's maintenance with bit of other stuff.
## Why / Balance

Because pain and misery, also people not tellin mappers whats the problem with the map but still talk about it publicly.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image

## Breaking changes

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Changed shoukou, you will see bigger maintenance in logistics and security.

### CODE REVIEW

**Comment by deltanedas** [comment]
> Removed laika

why? is it the ear powergaming

**Comment by Adrian16199** [comment]
> > Removed laika
> 
> why? is it the ear powergaming

I simply wasnt allowed to keep both laika and shiva.

**Comment by deltanedas** [comment]
laikaloose < shivaloose

**Comment by Adrian16199** [comment]
> laikaloose < shivaloose

You mind elaborating the opinion?

**Comment by Adrian16199** [comment]
Ready for review, need velcroboy's seal of approval and I have no idea how to request it so uh. yeah.

**Comment by Adrian16199** [comment]
Why does it fail that one test tho >_>

**Comment by IamVelcroboy** [comment]
Broken/bugged link

**Comment by Adrian16199** [comment]
> Broken/bugged link

How one would fix it because I assume that It is my issue and not the code issue.

**Comment by IamVelcroboy** [comment]
It has to do with what we talked about last week with buttons/levers and whatever they're linked to being deleted. 

Also, alarm linking is bugged right now too. So, if you changed/moved/added any alarm or anything linked to an alarm(vents, scrubbers, firelocks, sensors), it will cause as an error.

**Comment by Adrian16199** [comment]
> It has to do with what we talked about last week with buttons/levers and whatever they're linked to being deleted.
> 
> Also, alarm linking is bugged right now too. Do, if you changed/moved/added any alarm or anything linked to an alarm(vents, scrubbers, firelocks, sensors), it will cause as an error.

Oh god. I mean, regardin the first one then it wouldnt even let me save but the second one concerns me currently the most. I presume deleting the air alarm would solve it?

**Comment by IamVelcroboy** [comment]
But then you'd have no air alarm. There is a way to fix it. I'm just not at my computer today. I'll help with it tomorrow.

**Comment by Adrian16199** [comment]
Im just going to redo this PR because github is just acting dumb as all hell. Constantly pulling "7" commits out of nowhere.

**Pull request closed without merging**
