### PR TITLE
Add Laika and security dogs

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR

Adds Laika and security dogs to the codebase; security dogs are NT-aligned and will attack pests on sight, are ghost roles by default
Adds sec dog crate to cargo for 3500 spesos
Adds new tag: SecDogWearable
Adds new secdog sprites to upstream RSI's
Fixes description for Mark 1 rifles crate cargo entry
Slightly changes arctic fox prototype to be updated for rebase
Properly references warden hat in sprite
## Why / Balance

Pugi said we could get a new sec dog, current code is just a stand-in for when I figure out how to code dog handling for secoffs
## Technical details

N/A
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: TJohnson
- add: Added Laika and her crew, security working dogs that are aligned with the station. Best watch your step, citizens, lest your heels be nipped!

### CODE REVIEW

**Comment by TadJohnson00** [comment]
Works on my machine - and, if I'm not mistaken, should all be commented properly in all the right files.

**Comment by Carolyn3114** [comment]
mcgriff and shiva already exist as the HOS and warden's pets :((( can't believe you wanna replace them...,.,.,

**Comment by IamVelcroboy** [comment]
McGriff really should be a bloodhound. But, these look pretty dope.

**Comment by TadJohnson00** [comment]
schmerge crisis averted

**Review by DebugOk — DISMISSED** [review]
Looks good to me

**Comment by DebugOk** [comment]
@Colin-Tel review was requested, but I think this'll be good enough as is

**Comment by TadJohnson00** [comment]
the fuck??? Laika doesn't even have hands, why am I getting an error with detaching hands??

**Pull request merged**
