### PR TITLE
Finish Security Resprite

### PR DESCRIPTION
**Pull request by TadJohnson00**
The long-awaited second half should make Delta-V security almost fully distinct from WizDen.

## About the PR

Finished respriting security, including detective, warden, cadets, senior officers - etc.
## Why / Balance

Was always intended from the first resprite, in an attempt to make Delta-V security more visually distinct, interesting, and **g r i t t i e r**.

Some mild changes to balance with the coats, other than that should all be normal.
## Media

image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: TJohnson
- tweak: Security uniforms have received their second awaited update. Old-pattern uniforms are almost fully phased out.

### CODE REVIEW

**Comment by Timemaster99** [comment]
Does this include the senior officer gear coming up in the loadouts merge?

**Comment by TadJohnson00** [comment]
ehh? fuck's with the central package version manager??

**Comment by TadJohnson00** [comment]
> Does this include the senior officer gear coming up in the loadouts merge?

It does include senior officer gear, which will need to be incorporated into the loadouts merge.

When this PR goes through I'll address security's loadouts.

**Comment by DangerRevolution** [comment]
> ehh? fuck's with the central package version manager??

wizden issue, if you see all the items appear in game it's a good sign

**Comment by TadJohnson00** [comment]
Well, I can give you the classic "works on my machine lol"

**Comment by TadJohnson00** [comment]
winning a little too hard today

**Comment by TadJohnson00** [comment]
More wizden based issues?

**Comment by TadJohnson00** [comment]
Yep, looks like they're the same errors as on the vulp overlay removal. Works fine on my machine.

Sooner this gets merged, sooner I can fix other parts of the loadout system (mostly deprecated wizden items being used instead of delta-v items)

**Comment by TadJohnson00** [comment]
Just let me know if this needs discussion or changes prior to merge, I can address both as necessary.

**Comment by Axionyxx** [comment]
This will be reviewed when someone gets to it

**Review by Axionyxx — COMMENTED** [review]
The yaml changes seem fine so far, I'll do a more in depth review in a few days if no other maintainer gets it done first

**Review by ghost — COMMENTED** [review]
Took a look at this even though it's closed (AND!! I'm not a maintainer, just some random fucking contrib), most of the changes themselves are to sprites and YML files. This is good to merge as it appears on the surface and most of the new files it introduces and integrates, AND changes are sprites. You are free to un-close it and merge it.
One thing that I will note is it does get rid of the detective clothes and greatcoat as gear from the DetDrobe and SecDrobe as an option in favor of the Forensic Specialist gear added in this PR, so if anyone wants them back there, they'll have to add them alongside the stuff here.

**Comment by TadJohnson00** [comment]
Trench coats + noir suits + fedoras were intended to be removed in favour of detectives having actual uniforms that make sense. As for the greatcoat, it's still in the sec drobe, just locked behind the manager wire.

**Comment by rosieposieeee** [comment]
at least keep the old det stuff for loadouts :( its fun

**Comment by TadJohnson00** [comment]
If it was possible to sign comments on GitHub mine would be "TJ, Antithesis of Fun"

**Comment by Timemaster99** [comment]
Why was this closed? Is it still going to be reviewed?

**Comment by TadJohnson00** [comment]
If this isn't reopened by the time I get around to it, I'll just open a new PR from the same branch. This change does need to get merged eventually, having it closed contributes nothing.

**Pull request closed without merging**
