### PR TITLE
Personal Protective Equipment

### PR DESCRIPTION
**Pull request by Bribrooo**
## About the PR
This adds 6 new items promoting Personal Protective Equipment for chemists or other jobs I may have not thought of.

## Why / Balance
This would increase realism and features a nice little touch for roleplay, and seeing maybe more tidy chemists worrying about getting protected from dangers of some reagents.

## Technical details
None.

## Media
chempres

- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

## Breaking changes
Not groundbreaking changes...

**Changelog**
-add: safety glasses
-add: heavy resistant chemical gloves
-add: protective chemical apron
-add: enclosed shoes
-add: formal chemist suit
-add: chemistry tie

### CODE REVIEW

**Comment by leonardo-dabepis** [comment]
The spritework looks better after discussion on Discord. I do need to point out the stray yellow pixel on the shoes icon, and I think also the icon sprite for the goggles could do with a similarly transparent outline (I think there may also be a stray pixel there too on the stem of the goggles). Also there is something weird going on with the tie icon.
image

**Comment by Bribrooo** [comment]
The yellow dot on the shoes was actually deliberate, as enclosed shoes got a little button (often yellow/golden) to close the shoe, but if you want it removed it's also fine
I'll fix the icons though thank you

**Comment by leonardo-dabepis** [comment]
> The yellow dot on the shoes was actually deliberate, as enclosed shoes got a little button (often yellow/golden) to close the shoe, but if you want it removed it's also fine I'll fix the icons though thank you

I think if the yellow dot is intentional, it should be on both shoes in the icon sprite

**Comment by Bribrooo** [comment]
> > The yellow dot on the shoes was actually deliberate, as enclosed shoes got a little button (often yellow/golden) to close the shoe, but if you want it removed it's also fine I'll fix the icons though thank you
> 
> I think if the yellow dot is intentional, it should be on both shoes in the icon sprite

I've tried making adding it to both, looks bad, I'll just go ahead and remove it in my next commit, and fix the tie and glasses icon.

**Comment by Bribrooo** [comment]
Changes were made with Phil;
The tie "weird" feature is apparently totally normal
The enclosed shoes had their button removed
The safety goggles were updated to have an outline.

image

**Comment by Bribrooo** [comment]
I modified the safety glasses so they have a reflection (suggested by ps3moira)
image

Also it is planned to modify the ChemDrobe to be able to distribute those items for those wondering...
referencing this:
image

**Pull request closed without merging**
