### PR TITLE
Buff the damn shuttle cannons

### PR DESCRIPTION
**Pull request by Stop-Signs**
## About the PR
Shuttle cannons damage is VERY powerful
## Why / Balance
Any gun that is used to shoot other shuttles SHOULD ABSOLUTELY melt a standard person.
## Technical details
Perferator damage buffed to 70 heat and 30 structural. cage recharger now charges power cages 4x faster than a turbocharger would (seriously made no sense for the cage recharger to be as slow as it was and cost what it does). The cage recharger takes ~15 seconds to fully charge a high capacity cage, which should be fine balance wise.

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The perferator does heaps more damage
- tweak: The cage recharger is no longer worse than a basic recharger

### CODE REVIEW

**Comment by deltanedas** [comment]
closing because theyre broken and you can drag them around with a signaller and they still work, this would be op as hell

**Comment by dvir001** [comment]
> closing because theyre broken and you can drag them around with a signaller and they still work, this would be op as hell

Most of the changes we made on frontier are on this PR and will fix your issue:
https://github.com/new-frontiers-14/frontier-station-14/pull/1621

Feel free to merge frontier changed to shuttle guns.
We made them require power + wrench

**Comment by deltanedas** [comment]
it also applies to svallin and other ones not just the ptk

**Comment by dvir001** [comment]
> it also applies to svallin and other ones not just the ptk

The code actually is for all of them, just made sure PTK need power also.

**Pull request closed without merging**
