### PR TITLE
port saucer real

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- removed le trit miner
- ame is 1 core, engi also gets suppermatter roundstart and a solar array to build
- clown and mime get a room in maints
- epi gaming, has robo gear but no dedicated room
- sec greatly expanded:
  - hos actually has a room now
  - it has a perma
- cameras everywhere fnaf at fredy
- salv moved to logi, old place expanded into engi
- med has proper chem stuff and stasis bed
- cryosleepers
- no reporter or corpsman, its a tiny station
- comms/camera "pill" outside engi
- a few borg chargers
- random updating stuff
- darker maints
- less gamer loot in dorms, dont need random tiders with body armour roundstart on lowpop

todo:
- more test

## Why / Balance
- 25p max so no worrying about the fishops on periapsis
- saucer numero uno

## Media
Saucer-0

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Saucer station has been added for ultra lowpop rounds. Saucer #1!

### CODE REVIEW

**Comment by Bonktrauma** [comment]
Supermatter? Is that even in the game yet

**Comment by IamVelcroboy** [comment]
Haha Wow Saucer # 1

**Comment by deltanedas** [comment]
suppermatter not supermatter, radioactive thing and collectors

**Comment by IamVelcroboy** [comment]
I just realized this is *actual* Saucer not Ovni. Curious about that decision?

**Comment by deltanedas** [comment]
real saucer feels more authentic to me i guess, having a nice center park area with all the service stuff around it defines it (besides just being small which ovni also has)

**Comment by IamVelcroboy** [comment]
I feel like this might need to be some combination of the two maps. Take what is good about Saucer and combine it with some of the things that Ovni fixed. Such as an almost complete lack of maints. I don't remember all of the issues the 2 maps had off the top of my head but I'm sure I could dig stuff up in Discord when I have ore time. 

I do find the original Saucer quite charming but it did get pulled form rotation for a reason. 

I likely won't have time to review this for a few weeks anyway because IRL. But I am open to this map's return if it can improve on its previous iterations.

**Comment by deltanedas** [comment]
from a proper look over of ovni it seems better to port that than try to move every department around to have good maints on saucer

**Pull request closed without merging**
