### PR TITLE
Gun Overhaul

### PR DESCRIPTION
**Pull request by WarMechanic**
An overhaul of gun mechanics and interaction aimed at improving the tactility of guns and investigating gun confrontations in an MRP setting.

Started a thread of gun discussion because I didn't like how I couldn't cycle shotguns like I could rifles. I'm more active on discord, but feel free to comment here. Going down the WYCI rabbit hole due to positive reception.
https://discord.com/channels/968983104247185448/1231098216364113990/1231098216364113990
Gun serial numbers will be done in a separate PR due to continuity/persistence mechanics.

## About the PR

Rewriting how gun entities are composed and extending gun functionality. Also rebalancing ballistic and energy weapons to have more tactical distinction and to shift the pacing of ranged firefights to be more cover centric and slower overall - creating more room for text chat.

## Roadmap
Mechanical Guns
[ ] Separate a 'ChamberAmmoProvider' component from 'ChamberMagazineAmmoProvider' component. Replace 'BallisticAmmoProvider' component on pump action shotguns with 'ChamberAmmoProvider' and 'Magazine' components.
[ ] Allow every gun to be wielded such that interacting with a wielded gun open/closes the bolt rather than unwielding it (see L6 saw for poor interaction)
[ ] Improve gun accuracy and incur a movement penalty while wielding a gun. Movement penalties do not apply to space combat.
[ ] Shoving a gun wielder will immediately unwield their gun.
[ ] Implement gun modification by allowing players to deconstruct and swap parts in slots (barrel, stock, power cell etc) on guns which then modifies its properties, like how players can wear clothes with components.
[ ] Greyscale gun components so they're recolourable.
[ ] Implement the concept of part condition and providing means for players to clean their firearms. Using a gun with lower condition will lead to mechanical malfunctions.
[ ] Implement the concept of magazine-stripping for firearms and the double feed malfunction.
[ ] Implement the concept of magazine-seating for firearms and extraction failure.
[ ] Implement the concept of weapon heat for laser weapons which ties to the condition system, and barrel melting.
[ ] Implement the concept of gun safety and accidental discharges, which are incurred when taking damage or exposed to explosions while a gun is in your inventory.
[ ] Implement the concept of deviation, which is inaccuracy separate from a gun's mechanical spread.
[ ] Disable the ammo UI for all guns (except the WT550) to encourage mechanically diagnosing your gun.
[ ] Add configuration for condition and jamming mechanics.

Ammo Belt system
[ ] Implement the concept of bullet stacks and belts. Bullet stacks will always have worse storage efficiency when compared to ammo boxes.
[ ] Conceptualise inventory interactions with bullet stacks and belts such that you can 'hold an infinite number of bullets in your hand' - hold a bullet heap that links to nearby bullets. Cook and send inventory transactions to the server only when needed. 
[ ] Implement belt linking, turning the bullet heap in your hand into multiple linked bullet stacks.
[ ] Implement belt merging, which allows you to evenly mix bullets of different belts together into your bullet heap.
[ ] Implement fast and precise bullet un/loading of magazines.
[ ] Implement belt-fed weapons, which arbitrarily link to a belt within a certain radius.

Ballistic Weapon changes
[ ] Add a verb to magazines that inserts it into a gun in your offhand.
[ ] Increase the fire-rate and bullet velocity of ballistics across the board. Configurable via parts.
[ ] Zero or significantly reduce the damage that ballistic weapons do to metal or reinforced structures.
[ ] Remove fully loaded magazines from fabrication and instead rely on printing of ammo boxes.
[ ] Change all guns in the armory to start unloaded, and relocate missing ammunition to a separate safe.
[ ] Change the colour of .50 slugs to green

Laser Weapon changes
[ ] Allow lasers to be blocked by smoke.
[ ] Allow invisible entities to ignore lasers.
[ ] Entire laser guns can no longer be placed in rechargers, power cells need to be stripped to be recharged/replaced.
[ ] Double the fire rate and halve the damage of laser rifles to improve their suppression ability.
[ ] Change the laser rifle's firing sound, and the beam colour to green.

Additions
[ ] Add a .50 door breaching charge that breaks open doors and lockers.
[ ] Add higher capacity magazine options to research that have lesser storage efficiency.
[ ] Add a pistol grip for the Kammerer that is made with plastic.
[ ] Add a side saddle compatible with all shotguns that has an inventory for shotgun shells.
[ ] Add a gun modification that re-adds the ammo UI.
[ ] Add tools specific to cleaning guns, or a generic gun cleaning kit.
[ ] Add parts relevant to stripping guns.
[ ] Add barrels of various lengths.

Other stuff
[ ] Expose impulseStrength variable in CauseImpulse such that gun recoil is not hard coded.
[ ] Potentially animate in-hand icons to better represent gun interactions, improving tactility.
[ ] Replace the sprites of bullets to solid bullets rather than bright tracers, and add a displacement map to them for a supersonic effect. 
[ ] Add tracer bullets to replace the above, allow them to be recoloured.

## Media

[ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Will cause compatibility issues regarding changes to guns upstream, or implementations of new guns upstream as those will need to have their components converted to work with new systems.

**Changelog**

### CODE REVIEW

**Comment by WarMechanic** [comment]
i might want to pull some spritework for the other wielding large guns pr but i dunno what the etiquette for using someone elses stuff
https://github.com/space-wizards/space-station-14/pull/26970

**Comment by DangerRevolution** [comment]
Colonial Marines tackled this recently iirc:
>[ ] Separate a 'ChamberAmmoProvider' component from 'ChamberMagazineAmmoProvider' component. Replace 'BallisticAmmoProvider' component on pump action shotguns with 'ChamberAmmoProvider' and 'Magazine' components.
[ ] Allow every gun to be wielded such that interacting with a wielded gun open/closes the bolt rather than unwielding it (see L6 saw for poor interaction)

also to add on a "wyci"; every gun should be wieldable for extra accuracy (i'm referring to pistols etc)

**Comment by WarMechanic** [comment]
> Colonial Marines tackled this recently iirc:
> 
> > [ ] Separate a 'ChamberAmmoProvider' component from 'ChamberMagazineAmmoProvider' component. Replace 'BallisticAmmoProvider' component on pump action shotguns with 'ChamberAmmoProvider' and 'Magazine' components.
> > [ ] Allow every gun to be wielded such that interacting with a wielded gun open/closes the bolt rather than unwielding it (see L6 saw for poor interaction)
> 
> also to add on a "wyci"; every gun should be wieldable for extra accuracy (i'm referring to pistols etc)

good to know, maybe i should look at the code there. also i have every intention of letting pistols be wielded

**Comment by WarMechanic** [comment]
the cm14 shotgun pumping system doesn't align with my wants of being able to insert specialist shells directly into the chamber, it also looks fairly clunky.

**Comment by Axionyxx** [comment]
Pull requests aren't for initial design/rebalance discussions. Either make a forum post/thread on Discord, create an issue or use GitHub's [Discussions](https://github.com/DeltaV-Station/Delta-v/discussions) feature

**Comment by DangerRevolution** [comment]
> the cm14 shotgun pumping system doesn't align with my wants of being able to insert specialist shells directly into the chamber, it also looks fairly clunky.

CM13 allows you to, although it's bound to space by default which CM copied, and I assume CM will also copy the shell --> chamber concept.

**Pull request closed without merging**
