### PR TITLE
Asterisk AI Update 2

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

I fucked up #2049 and I'm not recovering it.

## Requirements

- [ ] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Bonktrauma** [comment]
Wth did you do to the old one

**Comment by IamVelcroboy** [comment]
Add StationAi to proto too and it's good to merge

**Review by IamVelcroboy — APPROVED** [review]
Ready for merge

**Comment by Colin-Tel** [comment]
btw I can't test this, as the game throws this error when I attempt to load any map.
image

**Comment by IamVelcroboy** [comment]
I've seen this before....

**Comment by IamVelcroboy** [comment]
> btw I can't test this, as the game throws this error when I attempt to load any map. 

Pulled master after merge and it's loading in fine for me

**Pull request merged**
