### PR TITLE
Adjusts playtime requirements

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

New players will have access to a decent selection of jobs from the start, and unlock two departments after one hour of playtime (or three departments after two hours of playtime).

Adds playtime requirements to Medical Intern and Research Assistant, and removes playtime requirements for Cargo Technician, Courier. Also somewhat lowers the Technical Assistant requirement.

## Why / Balance

Long story short, Intern and RA have some level of grief ability that can be somewhat dissuaded with the addition of a modest playtime requirement, while intro roles in Logistics are getting the green light for newer players.

After a good deal of feedback on this PR and in Discord, I collaborated with players to redo this PR to a place where I think is most reasonable to all of us. 

## Technical details

YAML only.

## Media

N/A

## Breaking changes

N/A
**Changelog**

:cl:
- tweak: Playtime requirements across "newbie jobs" have been adjusted.

### CODE REVIEW

**Comment by therealDLondon** [comment]
I'm the other headmin and I approve this message

**Comment by Bonktrauma** [comment]
I guarantee atleast one long time player who never plays passenger, will be confused why they suddenly can't play anything

**Comment by LadyDanger2743** [comment]
Hi! Yeah I agree with Bonktrauma- but overall it's just *thirty minutes* Passenger time. Not the end of the world- plus I know plenty of long time players who've chosen Passenger out of sheer boredom.

**Comment by deltanedas** [comment]
its overall playtime not specifically passenger

**Comment by Colin-Tel** [comment]
> I guarantee atleast one long time player who never plays passenger, will be confused why they suddenly can't play anything

A long time player *by definition* has played at least 30 to 60 minutes LOL

**Comment by Bonktrauma** [comment]
> its overall playtime not specifically passenger

No, it says it requires PASSENGER

**Comment by Bonktrauma** [comment]
> > I guarantee atleast one long time player who never plays passenger, will be confused why they suddenly can't play anything
> 
> A long time player *by definition* has played at least 30 to 60 minutes LOL

Not always passenger

**Comment by Timemaster99** [comment]
> > its overall playtime not specifically passenger
> 
> No, it says it requires PASSENGER

It does not. Please point to the code you're looking at

**Comment by Bonktrauma** [comment]
> > > its overall playtime not specifically passenger
> > 
> > No, it says it requires PASSENGER
> 
> It does not. Please point to the code you're looking at

I'm not looking at the code, I'm just reading off the description

**Comment by Bonktrauma** [comment]
""Would require  you to join as passenger for atleast 30 minutes""

**Comment by Bonktrauma** [comment]
Looked at the code, description and actual code are telling two very different stories

**Comment by Timemaster99** [comment]
colin fix description and cl plz

**Comment by Bonktrauma** [comment]
Description and code are telling two very different stories, I just looked

**Comment by Colin-Tel** [comment]
> colin fix description and cl plz

cl is accurate, adjusted description

**Comment by Bonktrauma** [comment]
> colin fix description and cl plz

He did, pinged him on discord

**Comment by deltanedas** [comment]
desc was wrong read the actual pr before coping :trollface:

**Review by DangerRevolution — COMMENTED** [review]
This is kinda weird; what is a new player meant to do as passenger? They join, walk around, find nothing to do because Passenger is a ""roleplay role"" and leave?

There's pretty specifically several roles open to new players to allow them to pick what they're interested in and to give them something to do while learning (and also to learn mechanics that isn't walking around as a passenger)

Just anecdotally that the new players I always see SSD are Passengers and Janitors; as they're the least interesting new player roles.

**Comment by Colin-Tel** [comment]
> This is kinda weird; what is a new player meant to do as passenger? They join, walk around, find nothing to do because Passenger is a ""roleplay role"" and leave?

You could ask people for a job or to provide assistance; you could walk around aimlessly (something they will likely do even with a role); you could participate in RP without any real responsibilities for a round (or a quarter of one), which isn't that bad of a thing considering it's an MRP server.

> There's pretty specifically several roles open to new players to allow them to pick what they're interested in and to give them something to do while learning (and also to learn mechanics that isn't walking around as a passenger)

Of course, and those roles will be there after they mess around as a passenger and get the gist of the server for a bit.

> Just anecdotally that the new players I always see SSD are Passengers and Janitors; as they're the least interesting new player roles.

Ironically enough, Janitor was brought up as a role we could potentially let fresh players have access to. I think it's simpler to just have everything behind a very short playtime req.

**Comment by DangerRevolution** [comment]
> You could ask people for a job or to provide assistance; you could walk around aimlessly (something they will likely do even with a role); you could participate in RP without any real responsibilities for a round (or a quarter of one), which isn't that bad of a thing considering it's an MRP server.

A) People very rarely give work to Passengers; as they're seen as greytide shitters and so aren't trusted with anything. (Source: I tried to play Passenger)

> Of course, and those roles will be there after they mess around as a passenger and get the gist of the server for a bit.

All I'm gonna say is uh; if I had to play Passenger for my first round I would've never played Delta again, especially if I latejoin and have to play it for two rounds just to unlock any interesting role.

> Ironically enough, Janitor was brought up as a role we could potentially let fresh players have access to. I think it's simpler to just have everything behind a very short playtime req.

At least walking back the Janitor playtime; to both encourage players to pick Janitor (so the station gets some care) and to give more options for a player.

**Comment by Colin-Tel** [comment]
Ok, what about 15 minutes for Janitor, Service Worker, Botanist, and Medical Intern?

**Comment by Colin-Tel** [comment]
Going to redo some of this. It's obviously not very popular, and I think it'll likely be that intro service roles can be without a playtime associated with it, while things like med intern or research assistant could be behind an hour or so.

**Comment by DangerRevolution** [comment]
> Ok, what about 15 minutes for Janitor, Service Worker, Botanist, and Medical Intern?

Never saw this until rn, still a bad idea

**Comment by DangerRevolution** [comment]
You doubted *ME*?

**Comment by IamVelcroboy** [comment]
> Ok, what about 15 minutes for Janitor, Service Worker, Botanist, and Medical Intern?

Isn't anything under like 90 mins basically pointless? I guess you could play a round for 15 mins and then leave. But....Seems better, imo, to encourage they play a full round.

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
