### PR TITLE
Give Central Command more Hallways

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
Addresses https://github.com/DeltaV-Station/Delta-v/issues/1685. Made each department-ish have a cool hallway to their respective area. Most of it is optional, people can go where they want except like, engi. 

## Why / Balance
EORG bad, crowd of people makes people a bit crazy, so we split them up into 4 smaller crowds. People who want to RP at AME can do so i guess.

## Technical details
YAML map 

## Media
image

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**

:cl:
- tweak: Central Command got a tiny renovation

### CODE REVIEW

**Comment by Colin-Tel** [comment]
Neat!

**Comment by Unkn0wnGh0st333** [comment]
Wait this is actually fire

Wait I just realized it separated by department, this is not so fire.

**Comment by IAmNotGray** [comment]
I see an Epi sign on the window there. Keep cooking...

**Comment by Lyndomen** [comment]
> Wait this is actually fire
> 
> Wait I just realized it separated by department, this is not so fire.

the doors are not locked, it is just a suggestion

**Comment by Lyndomen** [comment]
new doors just dropped 
image

**Comment by MilonPL** [comment]
don't tell me you nuked the tomb of the unknown employee....

**Comment by Lyndomen** [comment]
> don't tell me you nuked the tomb of the unknown employee....

Forgor

**Comment by perryprog** [comment]
This is slightly unrelated to the point of this PR (which I strongly agree with), but a question that's been on my mind for a while now is what _should_ we be doing at CentComm. We're done with our shift: why should we immediately be going to our normal department as if we're about to start a shift at a new station? Shouldn't we be heading to some dorms, a bar, and winding down from the shift?

Currently, at least for those who don't hang out in the square EORG room, people tend to just head to their department's area, and this flow change would at least encourage that. It would make more sense to me to have CentComm (as a whole) be much more service focused. In other words, I feel like bars, dining, and dorms feels like it should be the first thing people are encouraged to head towards, with probably medical and security being the exception.

This is obviously super overthought but it is a discrepancy with my expectation of what CentComm as a mini-station is _for_ that it's continually bothered me.

**Comment by Lyndomen** [comment]
> This is slightly unrelated to the point of this PR (which I strongly agree with), but a question that's been on my mind for a while now is what _should_ we be doing at CentComm. We're done with our shift: why should we immediately be going to our normal department as if we're about to start a shift at a new station? Shouldn't we be heading to some dorms, a bar, and winding down from the shift?
> 
> Currently, at least for those who don't hang out in the square EORG room, people tend to just head to their department's area, and this flow change would at least encourage that. It would make more sense to me to have CentComm (as a whole) be much more service focused. In other words, I feel like bars, dining, and dorms feels like it should be the first thing people are encouraged to head towards, with probably medical and security being the exception.
> 
> This is obviously super overthought but it is a discrepancy with my expectation of what CentComm as a mini-station is _for_ that it's continually bothered me.

 Honestly I 100% concur with you here. CC itself isn't super conducive to being <<interesting>>, I really like your idea of making it Service first & foremost. Outside the scope of this PR tho :)

**Comment by perryprog** [comment]
And to add on one more detail that's even further out of scope... currently we don't have a solution to make CentComm not have an honestly creepy ghost town vibe due to the lack of anyone being there in the first place. If this really is a "home base" of sorts there should be some sort of NPC staffing that is perennially present. I do have to wonder how people would behave with honest-to-goodness NPCs that would really just be some folks in green gear and a good ol' RandomWalkComponent. (Yes I know that's not the actual component for a random walk like I'm talking about.)

**Review by IamVelcroboy — APPROVED** [review]
A couple missing tiles that can be hotfixed. Otherwise, I am going to temporarily instate this change pending a full WIP remake.

**Pull request merged**
