### PR TITLE
Anti EORG update

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
Based on discussions held.

This will
* Make most grenades useless
* Make everything with the ability to harm mode a pacifist
* Break all uplinks

**Changelog**

:cl:
- tweak: Central command has installed new experimental tech for preventing harm.

### CODE REVIEW

**Comment by OCOtheOmega** [comment]
https://github.com/space-syndicate/space-station-14/pull/761

**Comment by DebugOk** [comment]
> [space-syndicate/space-station-14#761](https://github.com/space-syndicate/space-station-14/pull/761)

And?

**Comment by OCOtheOmega** [comment]
> > [space-syndicate/space-station-14#761](https://github.com/space-syndicate/space-station-14/pull/761)
> 
> And?

I threw it down to show that this has already made, you don't always have to reinvent the wheel, you just have to look it up

**Comment by Tryded** [comment]
I believe you still can throw spears at people, unless that was also addressed in this pr?

**Comment by DebugOk** [comment]
> > > [space-syndicate/space-station-14#761](https://github.com/space-syndicate/space-station-14/pull/761)
> > 
> > 
> > And?
> 
> I threw it down to show that this has already made, you don't always have to reinvent the wheel, you just have to look it up

Not in the way we're doing it. This method doesn't care if something is player controlled or not, and also takes additional steps.

**Comment by DebugOk** [comment]
> I believe you still can throw spears at people, unless that was also addressed in this pr?

Easy way to just get a ban with the new incoming rules

**Comment by DebugOk** [comment]
This code isn't working as intended, and might need to be reverted if it causes actual issues, but for now, it should be fine?

**Pull request merged**
