### PR TITLE
submarine atmosia update real

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- teg good and not a meme:
  - cooling loop that a. has radiators b. uses radiators properly
  - burn chamber that has mix injector and not just being extra volume for hot loop real
  - everything set to correct values by default so pros dont have to guess what each pump should be set to
- added comprehensive guide for new players to use
- removed useless mixers in atmos room
- moved pumps and filters up a tile, replaced space valve with gas pump
- waste has a pump now real
- distro has a pump now real
- chef freezer is done properly and preset to a cold temperature

## Media
whole teg setup

peak output ~2.2mw with not much cooling loop plasma (and it maintains good temperature at extreme output then recovers back below 0 shortly after smeses fill)

## Hall of shame
this "cooling loop" with no radiators literally does nothing

i have no idea what the hell this is but i left it in

## Changelog
:cl:
- tweak: Reworked Submarine's atmos, notably the TEG is now good, easy to set up and has a guide next to it.

### CODE REVIEW

**Comment by rosieposieeee** [comment]
> i have no idea what the hell this is but i left it in

i wanted a wall there (so it feels like a proper entrance) but didn't want to cover up the pipe... i dont know why it leads into the wall(?) probably a holdover from moving the scrubbers over a tile lol

anyway THANK YOU!!!!!!

**Comment by IamVelcroboy** [comment]
Awesome! Thanks for the update!

**Comment by rosieposieeee** [comment]
@deltanedas Any chance we could get this PR and [this one](https://github.com/DeltaV-Station/Delta-v/pull/1265) released as MIT, to free up original-flavor Submarine for some other forks?

**Comment by deltanedas** [comment]
i dont care its your map not mine

**Comment by rosieposieeee** [comment]
thanks, I think! ^_^

**Pull request merged**
