### PR TITLE
Update all DeltaV files to have the AGPL header

### PR DESCRIPTION
**Pull request by FluffiestFloof**
I think that's all of them.
Yes I added it to all of the files. I love all of them equally. ❤️ 
This really only affect future changes but at least it's there.

### CODE REVIEW

**Comment by DebugOk** [comment]
Quick fix

**Comment by DEATHB4DEFEAT** [comment]
hey that's my image :)

**Comment by DEATHB4DEFEAT** [comment]
QuickFixs

**Comment by deltanedas** [comment]
This pull request has conflicts, please resolve those before we can evaluate the pull request.

**Pull request closed without merging**
