### PR TITLE
Shiva as ghost role

### PR DESCRIPTION
**Pull request by CodedCrow**
## About the PR

Added Shiva as a playable ghost role

## Why / Balance

Because it could be fun to play as Shiva. I opened it as a discussion in the discord server and nobody opposed. 

## Technical details

It adds GhostRole and GhostTakeoverAvailable components to Shiva

## Media

https://github.com/DeltaV-Station/Delta-v/assets/114866135/a0e0fd1d-7649-4ea5-9fb8-2b27f0f637c2

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

add: Shiva as playable ghost role

### CODE REVIEW

**Comment by Colin-Tel** [comment]
Seems good to me at first glance.

The ghost role should however state some stuff about rules, rather than just give the generic ghost role rules. Probably something that details what you can/can't do as Shiva.

**Comment by CodedCrow** [comment]
> Seems good to me at first glance.
> 
> The ghost role should however state some stuff about rules, rather than just give the generic ghost role rules. Probably something that details what you can/can't do as Shiva.

Alright, I'm not completely sure how to do that, I'll work on it, I'll also work on figuring out what to put, i.e. what rules Shiva should follow

**Comment by Colin-Tel** [comment]
> Alright, I'm not completely sure how to do that, I'll work on it, I'll also work on figuring out what to put, i.e. what rules Shiva should follow

I'd say take a look at #172 and see how I did it. All you're doing is adding a rule to an .ftl file and specifying the rule on the GhostRole component Shiva gets.

As far as the rules go, probably just something along the lines of "Protect security staff and the crew from danger, Stay with Security staff or around the Security department, try to disable criminals and not kill them if the situation allows for it."

**Comment by CodedCrow** [comment]
image

Eyyyy!!

Thanks Colin

**Comment by deltanedas** [comment]
just use their

**Comment by CodedCrow** [comment]
> just use their

good idea, should've thought of it

**Pull request merged**
