### PR TITLE
Welcome to Port Royale!

### PR DESCRIPTION
**Pull request by DangerRevolution**
## About the PR

*Nanotrasen welcomes you to Port Royale! This state-of-the-art tourist destination offers endless exploration opportunities, limitless relaxation and a safe retreat from pesky saboteurs! Unwind, explore, and escape reality! We await your arrival at Port Royale!* 

Evac Dock is still low-key fucked but the map is otherwise done and it's 2 am right now, aside from Velcro's review it would be *really* appreciated to get someone Atmos-knowledgeable to have a look at my Atmos set-ups. Otherwise, all reviews are welcome :)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

PortRoyale-0

**Changelog**

:cl:
- add: Port Royale Resort Station has now opened for business! A top-of-the-line tourist destination is all yours to explore!

### CODE REVIEW

**Comment by deltanedas** [comment]
my observations:
- south atmos is floored which is bad just have plating where the pipes are
- artifact lab has *nothing* for handling gases not even a blast door
- there is no secondary power source which will be an issue once 1 core ops is killed
  i suggest replacing the (useless) gas recycler setup with a teg
  also remove the doors from the plasma and nitrous chambers big bad

**Comment by DangerRevolution** [comment]
> my observations:
>
>  south atmos is floored which is bad just have plating where the pipes are

Will fix. Meant to for a long time but forgot 💀 

>  artifact lab has _nothing_ for handling gases not even a blast door

Will fix.

>  there is no secondary power source which will be an issue once 1 core ops is killed

Top left of the map is the Singulo
one core AME is removed on Delta

>TEG

Delta maps don't have more than 2 power sources, so atm for us it's AME + TEG or AME + Singulo

**Comment by DangerRevolution** [comment]
TODO atm just so I can stop forgetting shit:

- [ ] Make Evac WORK
- [X] Atmos Floor
- [X] EPI needs Blast Doors to stop them being gassed
- [ ] Rebalance External Points of Interest
- [ ] (Optional) Add LORE and HRP to External Points of Interest
- [ ] (Optional) Beacons to Points of Interest?

**Comment by deltanedas** [comment]
> Top left of the map is the Singulo

ok im just blind disregard teg bit entirely

**Pull request closed without merging**
