### PR TITLE
Security Can Roll Sleeves

### PR DESCRIPTION
**Pull request by TadJohnson00**
Tweaks several Delta V security uniforms, adds some others, and adds sleeve-rolling functionality to majority of them.

## About the PR

Created a new uniform base entity that gives its children folding capabilities, as seen in the bandana hats/masks.
Reparented the majority of security's uniforms to this folding uniform base entity.
Tweaked several uniform sprites.
Added some new uniforms - forensic specialist (not in use yet), senior officer (also not in use yet), and formal dress.
## Why / Balance

Sleeve-rolling is cool. Security sprites otherwise needed to be tweaked and added onto.
## Technical details

n/a
## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n/a
**Changelog**

:cl: TJohnson
- tweak: Station Security uniform standards have been relaxed, and officers may now roll their sleeves on-duty.

### CODE REVIEW

**Comment by ghost** [comment]
Holy shit, new TJ sprite PR. Gotta review it when I'm done with the things I'm doing, give me like two hours.

**Review by ghost — DISMISSED** [review]
I dunno how I feel about turning senior officer's outfit into a onesie but you explained it before, it's an art thing, and I support that. 
Anyways, cool functionality,,, Upset it's just on sec clothing and not on all clothing. 
I'd say make an upstream PR to add it to all jumpsuits but: 
1. that might be a difficult ask and a really long side quest that honestly might suit me 
2. you also have to take into account how many sleeves you'd have to roll up locally with nyano / deltaV jumpsuits.

Anyways, yaml looks fine, sprites look good, can any maintainer or contributor sanity check me before I merge this?

**Review by MilonPL — APPROVED** [review]
Yaml looks good.

**Comment by TadJohnson00** [comment]
:imcry: sorry I had to fix the detective arm flash colours it was bugging me
executive decision made, future detective accent colour now light plum

**Review by ghost — APPROVED** [review]
Once again I am repeating the last review but this time it has a checkmark next to it before it becomes purple

**Comment by ghost** [comment]
Surely this won't be something I regret pushing the funny button on later :godo:

**Pull request merged**
