### PR TITLE
Micro station

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Adds Micro station.

Micro station is a small map intended for lower populations. It was made with the intent of having a lot of maintenance tunnels and many paths to take. Its kitchen, botany, and janitor office are made with Service accesses so that the 3 service worker slots can be used to cover multiple bases.

While this map is made with Supermatter in mind, it is also made to run off of a one-core AME, solars, and a few fueled generators with extra fuel.

This map has a full-fledged Legal department ready for the legal department PR's completion.

TO DO:

- [X] Add parallax
- [x] Add intercoms
- [X] Add warp points
~~Add justice department roles/equipment (pending #660 )~~
~~Add and test supermatter (pending https://github.com/Simple-Station/Einstein-Engines/pull/341 )~~
~~Link airlocks and brig timers (unable due to upstream bug)~~

The last three can simply be dealt with when they come, the map is otherwise ready to be played on and tested.

## Media

Micro-0

**Changelog**

:cl:
- add: Added Micro station! It can appear in lobbies no larger than 35.

### CODE REVIEW

**Comment by Carolyn3114** [comment]
supoper

**Comment by Bonktrauma** [comment]
Is there a secondary power system unyill super?

**Comment by DangerRevolution** [comment]
>> Is there a secondary power system unyill super?

> it is also made to run off of a one-core AME, solars, and a few fueled generators with extra fuel.

yes, solars; AME and generators

**Comment by Colin-Tel** [comment]
> Is there a secondary power system unyill super?

Crew round-start has access to:
2 Super PACMANS
2 PACMANS
4 stacks of uranium
4 stacks of plasma
a solar array that generates between 20 and 50 kW
a one core AME and controller
one AME fuel jar

not to mention at least a few Jr PACMANS spread around the station
(and the AI satellite has an RTG that keeps it fueled independently)

**Comment by Bonktrauma** [comment]
> > Is there a secondary power system unyill super?
> 
> Crew round-start has access to:
> 2 Super PACMANS
> 2 PACMANS
> 4 stacks of uranium
> 4 stacks of plasma
> a solar array that generates between 20 and 50 kW
> a one core AME and controller
> one AME fuel jar
> 
> (and the AI satellite has an RTG that keeps it fueled independently)

Got it

**Review by IamVelcroboy — APPROVED** [review]

**Comment by IamVelcroboy** [comment]
😳

**Comment by deltanedas** [comment]
lets get that supper

**Pull request merged**
