### PR TITLE
fix mass sleep

### PR DESCRIPTION
**Pull request by TadJohnson00**
...because Milon fucked it up

## About the PR

Change forced sleep duration from 30s to 5s
## Why / Balance

30s of honk shoo despite taking damage? Muy bien balance
## Technical details

n/a
## Media

n/a
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n/a
**Changelog**

:cl:
- tweak: Mass sleep duration reduced from 30s to 5s.

### CODE REVIEW

**Comment by deltanedas** [comment]
you can just wake up after 5 seconds because theres a 1 second cooldown on the wake up action

**Comment by TadJohnson00** [comment]
> you can just wake up after 5 seconds because theres a 1 second cooldown on the wake up action

Erm the button doesn't work

**Comment by deltanedas** [comment]
when forcedsleep is active, yes

**Comment by TadJohnson00** [comment]
And the forced sleep seems to be active for the whole duration of 30s

**Comment by deltanedas** [comment]
because if its not forced they can immediately wake up since the action has no delay

**Comment by TadJohnson00** [comment]
Hence the change from 30s to 5s

**Comment by Sifb26** [comment]
5 seconds feels short, I feel like 10-15 seconds would be better but that’s my opinion

**Comment by UnicornOnLSD** [comment]
> 5 seconds feels short, I feel like 10-15 seconds would be better but that’s my opinion

Considering it's an instant click concealed way to stun someone, 5 seconds is already plenty, hell that is easier to pull off than a slip and cuff and the victim won't be able to do anything for 5 seconds.

TL:DR, nah it's fine, 5 seconds is still PLENTY

**Review by ghost — APPROVED** [review]
Single number change, sure, let's see how it goes?

**Pull request merged**
