### PR TITLE
Vulpkanin mask and helmet custom sprites

### PR DESCRIPTION
**Pull request by FluffiestFloof**
Inspired by the Frontier one.

## About the PR

Decided to do like Frontier's PR and give them speshal mask and helmet sprites.
The issue is that most of the one that can be found in the ss13 codebases aren't the correct colors/style or don't exist.
So I'm just doing those by hand 🦊 

## Why / Balance

I don't know why.
Since there's a lot of ear styles, it still won't covers 20% of the ear styles.

## Technical details

Buh

## Media

eventually

## Breaking changes

**Changelog**

:cl:
- tweak: Vulpkanin now have a decent amount of special helmet and mask sprites.

### CODE REVIEW

**Comment by TadJohnson00** [comment]
"Helmets only; Captain's hardsuit, The Luxury cargo hardsuit, CBURN (not really that important), all the syndicate/nukie hardsuit helmets, juggernaut hardsuit, the blukies variants for those
I guess our custom new helmet for sec might need a vulp variant too :v"

Leaving this here so I can remember to sprite them later :3

**Comment by DebugOk** [comment]
Closing as derelict

**Comment by VMSolidus** [comment]
Wait what the heck was wrong with this? I looked at the code and there wasn't much wrong with it, only a merge conflict that went unaddressed. I could clone this branch, fix the merge conflict myself, and put it back in. This PR was basically done.

**Comment by FluffiestFloof** [comment]
> Wait what the heck was wrong with this? I looked at the code and there wasn't much wrong with it, only a merge conflict that went unaddressed. I could clone this branch, fix the merge conflict myself, and put it back in. This PR was basically done.

Not much is wrong, the merge conflict was addressed, it's mostly due to missing sprite that were never made I suppose.
It also adds a lot of extra sprites to base games folders, resulting in a lot of changed meta.json files so it might've been not wanted due to this.

**Comment by DebugOk** [comment]
> > Wait what the heck was wrong with this? I looked at the code and there wasn't much wrong with it, only a merge conflict that went unaddressed. I could clone this branch, fix the merge conflict myself, and put it back in. This PR was basically done.
> 
> Not much is wrong, the merge conflict was addressed, it's mostly due to missing sprite that were never made I suppose. It also adds a lot of extra sprites to base games folders, resulting in a lot of changed meta.json files so it might've been not wanted due to this.

It was never removed from draft status and hasn't had activity in a while

**Comment by FluffiestFloof** [comment]
> It was never removed from draft status and hasn't had activity in a while

Oh yeah I was waiting for TJohnson sprites for the missing helmets to undraft it.
Will reopen when the missing sprites are acquired.

**Comment by DebugOk** [comment]
Feel free to reopen if you're still interested in this

**Comment by VMSolidus** [comment]
Yea, I'm pretty interested in seeing this finished. What helmets are you missing? I might be able to make them for you using the others as reference.

**Comment by FluffiestFloof** [comment]
> Yea, I'm pretty interested in seeing this finished. What helmets are you missing? I might be able to make them for you using the others as reference.

Captain's hardsuit, The Luxury cargo hardsuit, CBURN, all the syndicate/nukie hardsuit helmets, juggernaut hardsuit, the blukies variants for those, the new paramedic one, probably more that I don't remember right now

**Pull request closed without merging**
