### PR TITLE
add tape recorder

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
tape recorder for recording people and then either using it in court, taking it out of context and/or blackmailing them :trollface:

you can get it:
- in an autolathe
- from detectives locker
- by being a reporter
- taking the trinket

## Why / Balance
interrogation rp is so back

## Technical details
code from https://github.com/space-wizards/space-station-14/pull/32234 with a fresh coat of paint and in deltav folders

## Media
funny box detective gets

loadout is real

:trollface:

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl: BombasterDS, deltanedas
- add: Tape recorders and cassettes can now be crafted in autolathes for recording crew speech.
- add: Reporters, detectives start with a tape recorder and cassettes.
- add: Added tape recorders to loadout trinkets.

### CODE REVIEW

**Comment by rosieposieeee** [comment]
fuck. yesssssss.

**Comment by Avalon-Proto** [comment]
I can only imagine the tomfoolery that will come with one if these and a few voice masks

**Comment by ThataKat** [comment]
Direction reviewing is real, 1-2 days o7

**Review by Lyndomen — APPROVED** [review]
good shit, voice mask gaming just got op

**Comment by TheRealSlimRedwoods** [comment]
Now do you remember, who you are, what you are meant to do?

**Comment by Centronias** [comment]
@deltanedas , considering this was originally PR'd to Wizden, would you mind dual-licensing the content of this PR under an MIT license so we can use it on https://github.com/moff-station/moff-station-14/ ?

**Comment by deltanedas** [comment]
Go ahead @Centronias

**Pull request merged**
