### PR TITLE
Add a new janitor PDA - Hygiene technician

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
Title.

## Why / Balance
Funny title and a bit more variety.

## Technical details
YAML changes + locale.

## Media
image

image

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added a new janitorial job title, select it from your loadout.!

### CODE REVIEW

**Comment by deltanedas** [comment]
gta:sa jeffrey reference?!"?!

**Comment by Colin-Tel** [comment]
love it 👍

**Comment by Radezolid** [comment]
> gta:sa jeffrey reference?!"?!

Merge it, I need a syndie janitor make steal the musician's rhyme book.

**Review by deltanedas — APPROVED** [review]

**Review by Lyndomen — APPROVED** [review]

**Comment by HTMLSystem** [comment]
HUGE WIN FOR JANITOR MAINS EVERYWHERE YEAAHHHH

**Pull request merged**
