### PR TITLE
Edge Station - Returned box evac & small changes

### LINKED ISSUE #1135: Edge evac doesn't dock at primary evac
## Description

Upon shuttle arrival on Edge station, the evac never targets the primary evac location on the west side of the station. It always resorts to docking at secondary evac on the east side.

**Reproduction**

Start a game with Edge station
`callshuttle 0:05`
it docks on the east side

**Screenshots**

N/A

**Additional context**

Gonna try moving the primary evac's docks up one tile, as the dimensions of the evac shuttle have not changed.

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Fixes #1135 

~~Re-adds `emergency_box.yml` to the `Maps/Shuttles` directory.~~

Small adjustments made to the map, in addition to resolving issue with improperly docking evac shuttle.

## Why / Balance

Primary evac wasn't being utilized and the alternate evac that was being used was docking weirdly.

**Changelog**

No.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Box needs to be remapped. It;s so far off center it was causing escape pods to spawn inside it.

**Comment by IamVelcroboy** [comment]
Also we have a DV version already, it's the NTES_Box. It already has the alterations we make to upstream shuttles. It just needs to be centered.

**Comment by Colin-Tel** [comment]
> Also we have a DV version already, it's the NTES_Box. It already has the alterations we make to upstream shuttles. It just needs to be centered.

So both the DeltaV one and the old one need to be recentered? Isn't that as simple as changing the following line:
```
    - type: Transform
      pos: 0.06253052,0.58707
```

Also, how is it causing escape pods to spawn in it?

**Comment by IamVelcroboy** [comment]
> So both the DeltaV one and the old one need to be recentered? Isn't that as simple as changing the following line:> 
> ```
>     - type: Transform
>       pos: 0.06253052,0.58707
> ```

Yeah, that might work. Just test it I guess.

> Also, how is it causing escape pods to spawn in it?

 I guess because `0,0` was so far off, It's not even on the shuttle iirc, the pods at take off would be *inside* of it. 🤷‍♂️

**Comment by Colin-Tel** [comment]
Hmm, I haven't really even adjusted it, and it seems to work alright.

image

**Comment by IamVelcroboy** [comment]
It's possible there was an upstream fix that snuck through at some point. We can try it again and see what happens.

**Comment by IamVelcroboy** [comment]
A couple things that were reported on Discord, don't remember if they were addressed yet...
- Sec needs a criminal records comp at front desk(or somewhere accessible)
- top right cryopod sending people into the walls

**Comment by Colin-Tel** [comment]
> A couple things that were reported on Discord, don't remember if they were addressed yet...
> 
> * Sec needs a criminal records comp at front desk(or somewhere accessible)
> * top right cryopod sending people into the walls

will do

**Comment by Colin-Tel** [comment]
image
can't duplicate the upper right cryo putting people into walls: you just spawn in the center of the cryo's tile

**Comment by IamVelcroboy** [comment]
>can't duplicate the upper right cryo putting people into walls: you just spawn in the center of the cryo's tile

Fair enough, it's possible that was fixed at some point too. I know at first direction of placement mattered. 🤷‍♂️

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
