### PR TITLE
Shoukou maintenance update.... again.

### PR DESCRIPTION
**Pull request by Adrian16199**
Fixes camera in cryo
Added a techmaint floor under Armoury level 2 door. 
Adds mirror to cloning.
Adds maintenance behind robotics, giving access to atmos if someone wanted to break in. 
Adds a TV in bar.

second patch
Adds extinguisher in medical, cargo's loading bay.
Adds atmos maintenance door to the new maints.
Adds couple of signs to help move around.
Adds additional places for navigation map (Bar, court)
Adds janitorial service light to command, logistics.
Adjusted the engineering's janitorial service light

## About the PR

Map
## Why / Balance

Just heard some complaints, might aswell fix em.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image
image
image

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Might as well give atmos access to maints too. Somewhere on this wall. 
image

**Comment by Adrian16199** [comment]
> Might as well give atmos access to maints too. Somewhere on this wall. image

Thats a fair point.

**Comment by IamVelcroboy** [comment]
This is approved to merge when upstream stuff is settled.

**Comment by Adrian16199** [comment]
"These conflicts are too complex to fix in the web editor"

Oh boy!

**Pull request merged**
