### PR TITLE
Butlertron Rebalance

### PR DESCRIPTION
**Pull request by Stop-Signs**
## About the PR
This adds more reward for turning in meals to our friendly little robot friend, the minimum reward you would claim is now 1200 spessos! This will also move some items to and from the butlertron blacklist and rearrange the value of harder-to-obtain items.

## Why / Balance
Butlertron is currently neglected about 99% of the time, these changes will allow chefs to work more with cargo and raise their own money for restocks, the items that have more complicated have been moved to the T3 category, meaning they have a bigger reward multiplier, items that are unobtainable and/or unrealistically obtainable have been moved to the blacklist. a few of the simpler recipes in the T3 category have been demoted to T2.
## Technical details
Not much technical details Disclaimer: this is my first time coding and I am trying my best (please don't smite me)

- [ x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- tweak: The Butlertron now gives you a bigger reward for fulfilling its food requests (1200 spesos is the lowest payout).
- tweak: The list of foods that the Butlertron demands has been adjusted to remove some practically unobtainable foods. New and more common foods have been added, and the reward amount for certain foods has been changed.

### CODE REVIEW

**Comment by pissdemon** [comment]
Good PR! However, I think the changelog needs to be fixed. There is a formatting issue, the changelog is read by a bot so formatting is important. You can also remove "fix: N/A" since there is no use to an empty changelog entry. The "add/remove/tweak/fix" don't all need to be filled out, instead the list is to set which icon to show in the changelog. You can have e.g. multiple "remove" entries and nothing else and it will show each entry with ❌  in the changelog. 

The changelog is also player facing (it's shown on the Discord and in game), in this case it doesn't really explain to players what changed. Maybe go with this instead:

```
- tweak: The Butlertron now gives you a bigger reward for fulfilling its food requests (1200 spesos is the lowest payout).
- tweak: The list of foods that the Butlertron demands has been adjusted to remove some practically unobtainable foods. New and more common foods have been added, and the reward amount for certain foods has been changed.
```

**Review by ghost — COMMENTED** [review]
Finally, a buff to the silly robot that everyone wants to throw out of the airlock and blow up.
I'm gonna suggest the same thing as vanilla about the changelog.

**Comment by Stop-Signs** [comment]
> Finally, a buff to the silly robot that everyone wants to throw out of the airlock and blow up. I'm gonna suggest the same thing as vanilla about the changelog.

Changelog should be fixed, I hope.

**Comment by Stop-Signs** [comment]
> Good PR! However, I think the changelog needs to be fixed. There is a formatting issue, the changelog is read by a bot so formatting is important. You can also remove "fix: N/A" since there is no use to an empty changelog entry. The "add/remove/tweak/fix" don't all need to be filled out, instead the list is to set which icon to show in the changelog. You can have e.g. multiple "remove" entries and nothing else and it will show each entry with ❌ in the changelog.
> 
> The changelog is also player facing (it's shown on the Discord and in game), in this case it doesn't really explain to players what changed. Maybe go with this instead:
> 
> ```
> - tweak: The Butlertron now gives you a bigger reward for fulfilling its food requests (1200 spesos is the lowest payout).
> - tweak: The list of foods that the Butlertron demands has been adjusted to remove some practically unobtainable foods. New and more common foods have been added, and the reward amount for certain foods has been changed.
> ```

Thanks for the advice, I was under the impression that management made those little quips in the changelog, I'm still new to this so any and all help is welcome!

**Review by TadJohnson00 — APPROVED** [review]
Looks good to me, approved by Game Director. Adei can take a quick peep through and merge it if he's happy with it all.

**Comment by ghost** [comment]
This is C# (relatively simple C#, mind you) and I'm a yamltainer. First I merge a map PR, then I merge a C# PR, I'm breakin' the lawwww!!! 😎

**Pull request merged**
