### PR TITLE
Message rate limiter

### PR DESCRIPTION
**Pull request by OCOtheOmega**
## About the PR
is an addition to the general topic of dealing with very unpleasant people. (https://github.com/DeltaV-Station/Delta-v/pull/392)
A very simple system that allows you to limit spam in the chat.

## Why / Balance
No more spam from bad ppl

## Technical details
Now chat messages have rate limiter.

## Media
https://github.com/DeltaV-Station/Delta-v/assets/42233446/175773e2-c87f-4631-86ef-f834458f35c4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- add: Message rate limiter.

### CODE REVIEW

**Comment by DEATHB4DEFEAT** [comment]
Should be something like "3 messages every 3 seconds" like Discord instead of "1 message every 0.75 seconds" because there can be good reason to send multiple messages shortly after each other.

**Comment by OCOtheOmega** [comment]
After a little bit of thought, and also finding https://github.com/space-wizards/space-station-14/issues/20845#issue-1932083623 I've come to the conclusion that it must be upstream, because it's more of a global problem than an individual fork server problem.

**Comment by DebugOk** [comment]
Did you ever work on getting this upstreamed or was it already being worked on

**Comment by OCOtheOmega** [comment]
> Did you ever work on getting this upstreamed or was it already being worked on

PJB already made a similar decision when I started talking to him about it. (soo just wait upstream)

**Comment by DebugOk** [comment]
> > Did you ever work on getting this upstreamed or was it already being worked on
> 
> PJB already made a similar decision when I started talking to him about it. (soo just wait upstream)

We're having a lot of issues with it right now and don't really have the time to wait on a fix from them

**Comment by OCOtheOmega** [comment]
> > > Did you ever work on getting this upstreamed or was it already being worked on
> > 
> > 
> > PJB already made a similar decision when I started talking to him about it. (soo just wait upstream)
> 
> We're having a lot of issues with it right now and don't really have the time to wait on a fix from them

In that case, you can use this as a temporary solution. What will be in upstream is similar to what is here, but they system lil better and have more configs.

**Comment by DebugOk** [comment]
Closing in favor of https://github.com/space-wizards/space-station-14/pull/21907, thanks anyways

**Pull request closed without merging**
