### PR TITLE
New Glacier Sec

### PR DESCRIPTION
**Pull request by noctyrnal**
## About the PR

Changes Glacier's Security to better handle the station.

## Why / Balance

Only one brig cell makes HOS very sad. Makes security all around more competent with handling things.

## Requirements

- [ X ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image
image
image

## Breaking changes

**Changelog**

:cl: noctyrnal
- tweak: Changed Glacier's Security.

### CODE REVIEW

**Comment by TadJohnson00** [comment]
but do it power doe

**Comment by noctyrnal** [comment]
Oh my god I forgot APCS

**Comment by dekigangsta** [comment]
not including the lobby part feels super lame ngl, there have been constant funny moments in the sec lobby but making yet another closed off sec building is zz. otherwise it looks ok but still current sec glacier is good nuff

**Comment by TadJohnson00** [comment]
This is a Velcro concern but I'll take a quick peek to make sure all the doors are powered an shit

**Comment by TadJohnson00** [comment]
List of issues:
- no tiny fans??
- Det's APC isn't wired with LV
- Det's fax isn't named
- why is there a crate of mothroaches in perma :imcry: I got jumpscared and they ate everyfuckinthing
- please don't give the permas a box of lights. this is the equivalent to twelve glass shards.
- perma fax isn't named (actually, just gonna assume none of the faxes are named)
- no prisoner spawners?
- you can still see the shitser in holding if you sit in the chair directly opposite :blimpse:
- the sec maints APC is also missing an LV wire
- labeler in the armoury would be very cool
- armoury APC should be facing inside not outside.
- corpsman's office has no defib cabinet? unsure if this is an issue or I'm just crazy
- I know this is up to mapper discretion for now but I prefer it when the secfab is in armoury so that the warden can keep tabs on it.
- the security east entrance doors are fucked. the ones going _into_ security, as well as the interrogation door, are fucked for an unknown reason, the ones going _out_ of security are fucked because they're "powered" by an LV cable that doesn't link with any APCs. there's a wholeass stretch of LV linked to nothin.
- oh and the air alarms/firelocks are fucked. I dunno if that's to do with fixed atmos or just the fact that you have no tiny fans, but the pressure is lower than it should be - and so is the temperature.
  - addendum: what the fuck are these air alarm thresholds
image
- oh and there's no cameras.

**Comment by deltanedas** [comment]
> labeler in the armoury would be very cool

detdrobe has a labeler for labelling evidence now

**Pull request closed without merging**
