### PR TITLE
Adds Cybersun Attorney Jumpsuit

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
Per request from gamer JustAnOrange, who cannot figure out git, adds in Cybersun Attorney Jumpsuit. Not acquirable, except through the Syndicate Recruiter who now starts with it. 

## Why / Balance
its neat

## Technical details
yaml

## Media
image

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl: JustAnOrange, Lyndomen
- add: Syndicate recruiters arrive with more swagger

### CODE REVIEW

**Comment by DisposableCrewmember42** [comment]
this contains #2214 

you can fix it using
```sh
$ git reset 3d142d2a73ede683234f916c519734aa9f4b16e3
$ git stash
$ git reset --hard master
$ git stash apply
$ git commit -m "feat: cybersun attorney jumpsuit"
$ git push -f
```
i haven't tested this but it should work, check before forcepushing :blunt:

**Comment by Lyndomen** [comment]
> this contains #2214
> 
> you can fix it using
> 
> ```shell
> $ git reset 3d142d2a73ede683234f916c519734aa9f4b16e3
> $ git stash
> $ git reset --hard master
> $ git stash apply
> $ git commit -m "feat: cybersun attorney jumpsuit"
> $ git push -f
> ```
> 
> i haven't tested this but it should work, check before forcepushing :blunt:

Agony, gonna just close and redo

**Comment by JustAnOrng** [comment]
this is hype.

**Comment by JustAnOrng** [comment]
I think it is cool enough to be aquirable through regular means, but not like. Super easy. Hacked Lawdrobe?

**Comment by Lyndomen** [comment]
ok we pretend this one didnt exist. the real one is 2217

**Pull request closed without merging**
