### PR TITLE
Homerun bat 2

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
revival of #823 with small balance changes:
- nerfed its structural damage from 15 to 10
- made 16 TC since its not as op and so more roles can buy it not just passenger

also just inherits baseball bat now to not copy paste *everything*

## Why / Balance
it was too op for breaking down doors and shit now its more a funny spaceman launcher

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl: musicmanvr
- add: Added the Home Run Bat for Syndicate operatives. Send your foes flying!

### CODE REVIEW

**Comment by dvir001** [comment]
Why do I feel this should have the ``G.O.R.I.L.L.A. gauntlet`` unanchorOnHit on it?

**Comment by deltanedas** [comment]
oh real that was never added

**Review by ghost — APPROVED** [review]
From my look at this, this seems normal, and fine to merge. Didn't see any mistakes, everything's in DeltaV folders, all that good stuff. One day I should actually PR a baseball so the existence of baseball bats makes sense though that's a note to self 

Dvir poses a good point about that component, I'd love to fling Butlertron across the room with this but what's already here is alright.

**Comment by deltanedas** [comment]
> baseball

already exists upstream just nothing uses it + you cant hit it with bat

**Comment by deltanedas** [comment]
also the reason it cant unanchor on hit is you could use it to troll glimmer probers at 500

**Comment by ghost** [comment]
> > baseball
> 
> already exists upstream just nothing uses it + you cant hit it with bat

Messed up.

**Comment by dvir001** [comment]
> also the reason it cant unanchor on hit is you could use it to troll glimmer probers at 500

https://github.com/new-frontiers-14/frontier-station-14/pull/1368/files

Could consider adding a Whitelist / Blacklist on the ``unanchorOnHit`` so it can be added without too many issues.

**Comment by musicmanvr** [comment]
this pleases me

**Pull request merged**
