### PR TITLE
Address some fried food issues

### PR DESCRIPTION
**Pull request by jzburda**
I'm new to this, did I do this right? 

## About the PR

Changed a variable from "deep-fried-burnt-item" to "deep-fried-burned-item".
Calls the SliceFoodEvent again in case it generates another slice.

## Why / Balance

Part 1 "[Fix unlocalized entry due to miswording of variable]" solves problem 1 of issue #439, and should in theory fix deep fried burned items from not having an empty examine text
Part 2 addresses problem 2 of #439 but is more iffy. This is untested, but what if, we just simply... call the SliceFoodEvent again that only goes to DeepFryerSystem.cs
## Media

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

fix a variable to fix the examine text.
Attempted to make the last slice of a sliceable food item crispy
**Changelog**

:cl:
- fix: Fixed the unlocalization of deep fried burned items.
- fix: Last slices of a food item no longer decrispify.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
Change the changelog part of your description to:
```
**Changelog**

:cl:
- fix: Fixed the unlocalization of deep fried burned items.
```
If you want to actually show up in the changelog

**Comment by jzburda** [comment]
> Change the changelog part of your description to:
> 
> ```
> **Changelog**
> 
> :cl:
> - fix: Fixed the unlocalization of deep fried burned items.
> ```
> 
> If you want to actually show up in the changelog

done ty

**Review by luringens — COMMENTED** [review]
Looks great!

**Comment by deltanedas** [comment]
this seems ultra sus

**Comment by jzburda** [comment]
> this seems ultra sus

You're right, I'll revert it if that isn't the solution.

**Comment by deltanedas** [comment]
ill investigate better solution in the morning :trollface:

**Comment by jzburda** [comment]
I'm going to wipe this and restart fresh git is giving me shit

**Pull request closed without merging**
