### PR TITLE
Locked arrivals & Shipyard

### PR DESCRIPTION
**Pull request by CometVoid**
sorry for the PR spam. should work now after quadruple checking it

## About the PR

added locked variation of arrivals and shipyard airlocks

## Why / Balance

tinyfans can be removed from most docking ports, as docking ports don't leak into space when a shuttle is docked to them. However if we just remove tinyfans and see what happens, mass spacing will occur due to everyone being able to open those airlocks

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
 shouldn't be any, as these are new variations and don't touch the old airlocks

**Changelog**

:cl:
- add: Added locked variations of arrivals and shipyard airlocks that require externals access to open

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
You don't have to open/close a new PR every time you make an edit. You can push additional commits to your branch.

**Comment by CometVoid** [comment]
> You don't have to open/close a new PR every time you make an edit. You can push additional commits to your branch.

oh really? that would've been nice to know

**Comment by Colin-Tel** [comment]
> tinyfans can be removed from most docking ports, as docking ports don't leak into space when a shuttle is docked to them.

I'm going to contest this, because Micro station upon release was lacking tiny fans at evac because I shared the same line of reasoning you currently have.

It's not the case.

I had to add tiny fans on Micro station because of it.

**Comment by deltanedas** [comment]
docking airlocks without tiny fans block air only when docked, so you can dock to a fully spaced lattice with a docking airlock just fine, but they space if opened when not docked.

adding access wont prevent spacing just lock it behind a few roles, they should still have either directional fans or xor logic gate for `status ^ docked` to bolt another airlock closed if it gets opened while undocked

**Comment by deltanedas** [comment]
also there is a pr upstream to make arrivals+evac locked so this should just be shipyard

**Comment by IamVelcroboy** [comment]
> also there is a pr upstream to make arrivals+evac locked so this should just be shipyard

Looking at inheritance, Shipyard will also be covered by the upstream PR

**Comment by IamVelcroboy** [comment]
Locked this pending upstream PR

**Comment by ghost** [comment]
Was this done upstream and have we merged that? If so, should this be closed or merged?

**Comment by IamVelcroboy** [comment]
> Was this done upstream and have we merged that? If so, should this be closed or merged?

It was done upstream but it hasn't been reviewed yet.

**Comment by ghost** [comment]
Damn :pensive:

**Pull request closed without merging**
