### PR TITLE
Hwid ops

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
@MilonPL merge when ss14.admin and db are updated/migrated

### CODE REVIEW

**Comment by MilonPL** [comment]
@deltanedas did we not merge https://github.com/space-wizards/space-station-14/pull/30827 or what

image

**Comment by deltanedas** [comment]
real

**Comment by MilonPL** [comment]
db migrated, ss14 admin updated
needs netserializer updated even though it should be?

**Comment by deltanedas** [comment]
is it that fucked

**Comment by MilonPL** [comment]
fuck if i squash it we wont get merge history and if i commit it then we will have the `merge branch 'master' into hwid-ops` agony

**Comment by deltanedas** [comment]
rebase then :trollface:

also tests are fucked from it

**Comment by MilonPL** [comment]
yes lemme figure out why

**Comment by MilonPL** [comment]
you missed a commit goober

**Review by MilonPL — APPROVED** [review]

**Pull request merged**
