### PR TITLE
Update asterisk.yml

### LINKED ISSUE #389: asterisk atmos has no axe
## Description
title

**Reproduction**
1. ask ce for axe 3 times
2. dont get axe
3. atmos is 100C
4. spiders spawn and you cant defend yourself
5. almost die and go to med
6. get gibbed by a nazi on the way to med (real)

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Added meteor netting to prevent evac from docking at cargo 
Changed layout of Epi's park to prevent getting stuck 
Added a plasma canister to TEG area
Named all substations and SMESs
Minor changes to courtroom
Changed Command maintenance hatch at EVA room to EVA airlock 
Moved CE's fireaxe into TEG area for more use ( fixes #389 )
Fixed lack of power to alternate evac

**Changelog**

:cl:
- fix: Fixed a few issues with Asterisk, including getting stuck on Epi's park tree and evac docking at cargo.

### CODE REVIEW

**Comment by deltanedas** [comment]
just south of engi there are 2 command doors that arent locked is that fixed
i know i didnt report :trollface:

**Comment by Colin-Tel** [comment]
> just south of engi there are 2 command doors that arent locked is that fixed i know i didnt report :trollface:

You mean the first two airlocks of the bridge? That's intentional.

**Comment by deltanedas** [comment]
oh good it was just a little weird on every other map every layer of doors going into the bridge are locked :trollface:

**Comment by Colin-Tel** [comment]
> oh good it was just a little weird on every other map every layer of doors going into the bridge are locked :trollface:

Yeah the purpose in this particular map case is in the event of a spacing, there is a path to a maintenance tunnel to get to safety via the bridge vestibule's hatch.

**Pull request merged**
