### PR TITLE
upstream merge 2/10

### PR DESCRIPTION
**Pull request by deltanedas**
## Notable additions
- ai door electrifying and console access panels
- traitors and nukies have evil lawset boards
- pais dont have binary anymore
- votekicking is real
- syndie business card
- that goddamn storage stack insertion bug is fixed
- hydroponics airlocks need respriting so they use old texture still

## Notable exclusions
- frezon nerf, nobody mass produces frezon here anyway :trollface:
- grey trenchcoat for detective loadout
- camera bug is disabled since we still have the funny observation kit
- disabled random ops shuttle (its already "disabled" because the gamerule never got added anyway big funny)

## Changes
- removed blanked whitelist requirement from cap i probably just forgot it
- syrinx implant chnaged to work with the voice mask refactor, its much simpler now and more robust
- updated aac tablet for voice mask refactor
- put airlock groups into deltav file so it doesnt giga conflict every time

**Changelog**
:cl:
- add: Merged last ~weeks changes from upstream.
- fix: Fixed captain requiring global whitelist instead of just the role whitelist.
- tweak: Frezon nerfed was reverted.

### CODE REVIEW

**Comment by MilonPL** [comment]
do we care about the binary channel at all? it was kinda fun to talk there as a pAI, and this also applies to PBs I'm pretty sure

**Comment by MilonPL** [comment]
also after talking to the headmins, in the presets disable votekicks for apo + for peri we're doing `eligible_number = 5`, `initiator_ghost_requirement = false`, `voter_ghost_requirement = false`

**Comment by perryprog** [comment]
Milon beat me to it but I was gonna suggest letting pAI's keep binary. At the least, we don't have AI yet so the motivation of pAI being lawless/familiar meaning it can narc on malf AI isn't valid here.

**Comment by deltanedas** [comment]
right now pais can snitch on the shadow factory and ai is just a week away, malf 2 weeks away

**Comment by perryprog** [comment]
Dunno what the shadow factory reference is, but fair point—plus pAI is getting more content with the software catalog PR on upstream which could give some better options for pAI's offering something besides someone to talk to (granted, when I play pAI it's just to talk to someone I know is a good roleplayer and I come away quite happy on those rounds).

Really only time I've seen binary be used by a pAI is to say "hey is there anyone there" and then never follow up or "yo my person is dead", and that only happened on like one round I've been on.

**Comment by deltanedas** [comment]
@MilonPL double check i have the votekick settings right please :trollface:

**Comment by MilonPL** [comment]
> @MilonPL double check i have the votekick settings right please :trollface:

i said PERIAPSIS istg

**Comment by deltanedas** [comment]
pro

**Comment by MilonPL** [comment]
yeah looks good now, test fail looks real probably because we nuked the wanted list app, other than that this seems good to merge

**Review by MilonPL — APPROVED** [review]

**Pull request merged**
