### PR TITLE
Harpy Can Now Mimic Harps!

### PR DESCRIPTION
**Pull request by TheOneWhoIsManyFrame**
It is weird this isn't already a thing, lol.

## About the PR

Harpy now have Harp as an instrument for mimic.

## Why / Balance

Does not affect gameplay balance.

**Changelog**

:cl:
- add: Harpies can now mimic harps!

### CODE REVIEW

**Comment by DangerRevolution** [comment]
Change log isn formatted correctly, try open a new PR to see the template or I can send it later

**Comment by TheOneWhoIsManyFrame** [comment]
> Change log isn formatted correctly, try open a new PR to see the template or I can send it later

I used the template though....weird...

**Comment by DangerRevolution** [comment]
**Changelog**
:cl: DangerRevolution
- add: ADDED SOMETHING

as an example:

image

**Comment by TheOneWhoIsManyFrame** [comment]
> **Changelog** 🆑 DangerRevolution
> 
>     * add: ADDED SOMETHING
> 
> 
> as an example:
> 
> image

done

**Comment by TheOneWhoIsManyFrame** [comment]
@NullWanderer Can this be reviewed and approved please? Id love to use Harps

**Comment by DangerRevolution** [comment]
Probably worth considering if this is power creep for Harpies; they shouldn't be able to replace every instrument

**Comment by WarMechanic** [comment]
> Probably worth considering if this is power creep for Harpies; they shouldn't be able to replace every instrument

i think harpies mimicing harps is good word play though, if anything it should take precedence over something else but it really isn't too big of a deal

**Review by Axionyxx — APPROVED** [review]

**Comment by Axionyxx** [comment]
> @NullWanderer Can this be reviewed and approved please? Id love to use Harps

Please do not ping me for reviews, I will not look at it any faster

**Comment by ShinAkumaXD** [comment]
my apologies

**Pull request merged**
