### PR TITLE
Rules update II

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
Added a couple more forgotten lines, that are important

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Added rules concerning the captain during NukeOps, and an expansion on rule E2

### CODE REVIEW

**Comment by therealDLondon** [comment]
What do you mean conflict-

**Comment by Axionyxx** [comment]
> What do you mean conflict-

You reused a branch, which you can't do

**Comment by Axionyxx** [comment]
Every pull request requires a new, clean branch

**Comment by therealDLondon** [comment]
See I told you im stupid

**Pull request closed without merging**
