### PR TITLE
Deep Fryer And Its Powers

### PR DESCRIPTION
**Pull request by PHCodes**
## About the PR

The Deep Fryer has been implemented. It uses Corn Oil, Ghee, and Olive Oil to fry. Other features include:
1. Mixing Oil and Water at a certain temperature causes smoke.
2. When throwing an object at the Deep Fryer, a Chef will *always* land the shot, but anyone else has a chance of missing.
3. When an item is sliced, an event is triggered that other items can see.

## Why / Balance

Delta-V uses a Deep Fryer to help mix up Kitchen's gameplay somewhat. It's much more appealing to hear the sizzle of a deep fryer and imagine something coming out with a golden, crispy texture. Mmmmmmmmmmmmmmmmmmmmm.

## Technical details

I tried to mark anywhere I edited existing code to make this work. Mostly I had to modify the Thrower and Slicing components. I also modified the Chef's definition to give them their Professional Chef component. I imagine this will be useful for other things in the future, as well.

## Media

Bear Cooking

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes. I hate changing from OilCorn to Cornoil.

**Changelog**

:cl:
- add: Added the Deep Fryer and related features.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
Can you deepfry the stun batons

**Comment by PHCodes** [comment]
Wrote a test for the Deep Fryer per Debug's suggestion. It is a dummy test because I have no experience with the test framework and would rather learn how to do it with something I create myself if given the choice.

**Review by DebugOk — APPROVED** [review]
Works on my machine:tm:

**Comment by beck-thompson** [comment]
Hey would you be OK if someone upstreamed some of this code (including the shader https://github.com/DeltaV-Station/Delta-v/pull/200)? It would be under the MIT license so you would need to give the go ahead and give permission

**Comment by deltanedas** [comment]
its utter shitcode you really shouldnt, and nyano was mit anyway

**Comment by beck-thompson** [comment]
> its utter shitcode you really shouldnt, and nyano was mit anyway

They mostly were interested in the shader! Thanks for the info on the license :saluting_face:

**Pull request merged**
