### PR TITLE
Lunchboxes!

### PR DESCRIPTION
**Pull request by DangerRevolution**
## About the PR

Added Lunchboxes
Added pre-filled Lunchboxes, containing a few snacks.

## Why / Balance

Variety, lets the chef pack meals for people that they can take with them, rather than leaving food on the kitchen counter!
Also a new storage item, for people to use nested inventory or for people to hide evil items in.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

image

**Changelog**
:cl: DangerRevolution and Noctis
- add: Added lunchboxes!
- add: Added lunchboxes to the chefvend and dinnerwarevend for the Chef to fill or hand out pre-made!

### CODE REVIEW

**Comment by deltanedas** [comment]
happy honk meals do this already :trollface:
grab burger put it in meal and leave at every dept front desk

**Comment by DangerRevolution** [comment]
> happy honk meals do this already :trollface: grab burger put it in meal and leave at every dept front desk

happy honk meal = corporate gift box with a toy inside
lunchbox = box designed to hold food & snacks for the chef to fill (maybe filled if mapper maps it in)

**Comment by DangerRevolution** [comment]
This is fully ready for review.

**Review by DebugOk — CHANGES_REQUESTED** [review]
Merge all the textures into a single RSI or I wont even look at this

**Pull request closed without merging**
