### PR TITLE
Submarine Patch - RE-TEG Edition

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

- completely redid engineering, to make it more cozy and efficient and because i...
- removed AME, replaced with TEG. between that and the singulo, it should be more interesting for engineers!
- added cell recharger to cargo
- remove anti anom zones for suspected lag spikes :(
- fixed blast doors that made doors harder to close manually
- fixed incorrect medical wall lockers
- fixed gas tank dispenser in singulo room (sigh)
- removed space tiles around nuke, removed mines until i PR ones that don't destroy blocks (easy comp change but im lazy)
- fixed some decals
- replaced some of the regular chairs that are bugged to not spawn with wooden ones
- modified armory contents a bit
- added an air scrubber to the engi outpost
- fixed warp points & beacons to comply with recent changes
- added even more station maps around the place

## Media

image

**Changelog**

:cl:
- tweak: Total re-make of Submarine's engineering department. Goodbye, AME!

### CODE REVIEW

**Comment by deltanedas** [comment]
maps shouldnt have teg and singulo have you checked with map man

**Comment by stellar-novas** [comment]
Maps are allowed to to have 2 of the 3 power sources (solars are fake)

Sub has no AME now so it's fine

**Comment by rosieposieeee** [comment]
this patch is ready, but i'd really like an atmos main to look over the TEG setup because i have no idea how the TEG works. tried to replicate more or less what i had previously, but its not identical

**Comment by Bonktrauma** [comment]
> maps shouldnt have teg and singulo have you checked with map man

Velcro said 2 power sources (solar not included). he said teg and singulo was an option, just no AME

**Comment by IamVelcroboy** [comment]
Well...this could be interesting. Let's see how they do...

**Pull request merged**
