### PR TITLE
Prosecutor and det switch positions ON SHOKO.

### LINKED ISSUE #1373: shoukou prosecutor office placement
## Description

Prosecutor doesn't have sec access anymore, their office behind sec access doors on shoukou, you can only get out of sec as prosecutor using the back door of your office.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

Doesn't fix other jarring map issues like the front door of sec on shoko but addresses the astro grass and exposed piping thing, the det office and the prosecutor, and the clerk maints being locked to justice because I forgot to replace that last go-through. Who would've thought.

## Why / Balance

I fucked up and then things got changed around with justice again!! :)
## Technical details

Fixes #1373 

Might get trolled by invalids because I had to do a lot of linking this go-around

**Changelog**

### CODE REVIEW

**Comment by Colin-Tel** [comment]
Error says there's no spawnpoint for the Prosecutor job.

**Comment by ghost** [comment]
I got trolled by the lack of a prosecutor spawn; also reworked the AI sat / some shielding, so, let's hope I don't get trolled again.

**Comment by IamVelcroboy** [comment]
Invalid error is valid

**Comment by IamVelcroboy** [comment]
If you're not sure how to fix the invalids there are people in mapping channel that can help you while I'm away. I will still merge when it's fixed though, as it's important to get the Prosecutor's access sorted

**Comment by ghost** [comment]
Mapserver, please. I needed to fix atmos and an invalid.

For all intents and purposes I think this PR is done unless the tests find some other issue. But yeah, it's merge-ready.

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
