### PR TITLE
Every syndicate agent can get a free radio implant

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

Syndicate agents now get a singular radio implanter for free from the uplink rather than having to spend 2tc.

## Why / Balance

I was bribed
image
noctis approved by the way

## Technical details

YAML warrior

## Media

pending
image

bought
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

no

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Syndicate agents can get one radio implanter for free.

### CODE REVIEW

**Comment by noctyrnal** [comment]
"noctis approved" means nothing sorgy :(

**Comment by WarMechanic** [comment]
this pr is not for me :trollface:

**Comment by Colin-Tel** [comment]
When this was talked about in admin channels, it was under the impression it would cost 1 less TC (aka cost 1 TC), not just free.

I disagree with the premise of it being free.

**Comment by therealDLondon** [comment]
This was discussed briefly among admins and the agreement is that this is not a balance change we would want, unfortunately, it removes too much guesswork from syndicate agents and invalidates codewords. Sorry

**Comment by Lyndomen** [comment]
I'll just chime in with more of an annecodatal idea: it might be cool to investigate this more broadly, perhaps by having various items on discount/free randomly per round, mirroring SS13's discount systems.

**Pull request closed without merging**
