### PR TITLE
Add awoo emote to vulps (and harpies)

### PR DESCRIPTION
**Pull request by pissdemon**
## About the PR
Vulpkanins can now awoo as God intended.

## Why / Balance
Awoo.

**Changelog**
If it were announced there would be too much awooing.

### CODE REVIEW

**Review by Axionyxx — DISMISSED** [review]

**Comment by Adrian16199** [comment]
Yes

**Comment by pissdemon** [comment]
Actually, this is gonna need re-review/re-approval or something because my dumb ass didn't pay attention and did this wrong :blunt:

**Comment by pissdemon** [comment]
Tested to actually work locally. Harpies being harpies can imitate it too.

**Review by Colin-Tel — APPROVED** [review]
It works!

**Pull request merged**
