### PR TITLE
Add "Deck the Halls" by Kevin Macleod

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
Draft PR, I havent purchased a license yet or uploaded anything. Do we want it on the jukebox:trollface: 

## Why / Balance
what a banger

## Technical details
yaml

## Media
image

## Requirements

- [ ] I have tested all added content and changes.
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: Added holiday cheer

### CODE REVIEW

**Comment by therealDLondon** [comment]
If you're willing to pay the 200 bucks I am 100% on board

**Comment by MilonPL** [comment]
it would be REALLY funny

**Comment by Lyndomen** [comment]
I am on record that I will pay $200

**Comment by Unkn0wnGh0st333** [comment]
The peak in question

**Comment by therealDLondon** [comment]
> I am on record that I will pay $200

Then do it, im using my 1 "merge this" token, do it
Add it to the lobby, and the jukebox, also make it a nuke countdown song :trollface:

**Comment by dvir001** [comment]
image

**Comment by ThataKat** [comment]
I would lose my shit if this was a nuke countdown song. Official opinion of Direction pending

**Comment by ThisIsIPat** [comment]
It could replace every single lobby song. That's the only song that plays.

**Comment by CybersunOperative** [comment]
hi official opinion of direction here (trust). If you can resolve the license, then by all means, add it to the jukebox. Might be funny, I would laugh.

**Comment by boogiebogus** [comment]
can we add a rule to make people who play it valid

**Comment by IamVelcroboy** [comment]
This is evil

**Comment by Lyndomen** [comment]
1984 so it turns out $200 is a scam or something and a real license for the OG shit would be thousands of dollars. i have a house to remodel so that aint it chief. 

in return we get 
image

deck the halls, royalty free and in public domain by kevin macleod king of all shitty youtube videos

im still looking into the legality of CC-BY covers, as someone  is sharing a "All I want for christmas is you" cover as CC-BY but that might not be real, idk

**Comment by Colin-Tel** [comment]
I dig it

**Comment by Lyndomen** [comment]
oh real not draft

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
