### PR TITLE
Added Three-Sword Style

### PR DESCRIPTION
**Pull request by ps3moira**
## About the PR

Made katana's able to be equipped in the mask-slot.
## Why / Balance

Because it's cool.
## Media
Screenshot 2023-12-20 193608
Screenshot 2023-12-20 192640
DULL VERSION.
Screenshot 2023-12-20 192658
REAL VERSION.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame
**Changelog**
:cl:
- add: Added Three-Sword Style. Katana's can now be equipped in the mask-slot.

### CODE REVIEW

**Review by DebugOk — COMMENTED** [review]
I think this looks ridiculous and doesn't fit at all, so consider this my disapproval of this. Unless Colin thinks otherwise

**Comment by DebugOk** [comment]
@VMSolidus You're the only other person I have to ask right now, since my older comment was made when Colin still had write access.

I think this sprite looks silly, and I dont like it. Whats your opinion on it?

**Comment by VMSolidus** [comment]
So I'll be honest, as much as I talk about using mecha anime for reference art, I'm not actually that big of an anime fan. I really don't like these sprites that much at all, not just because they're silly, but also on a technical level. I know this server likes to have the strange and unusual stuff, but carrying a sword in your mouth is a little too out there even for us, it's just having a one-piece reference for the sake of the reference.

**Comment by VMSolidus** [comment]
I'm going to close this as I do not feel that this feature is a good fit for this server.

**Pull request closed without merging**
