### PR TITLE
update pr labeler

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR
updates the pr labeler to include the brand new audio files label

## Technical details
checks for .ogg files

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

hopefully none, didn't test :blunt:

### CODE REVIEW

**Comment by TadJohnson00** [comment]
ah, my favourite smellymin. where's the CL :trollface:

**Comment by MilonPL** [comment]
> ah, my favourite smellymin. where's the CL :trollface:

no fun

test fail unrelated btw

**Comment by TadJohnson00** [comment]
"test fail unrelated"
\- a mf that never tried adding fun to the CL

**Review by ghost — APPROVED** [review]
I dunno how github labeler files work but this looks like yaml and seems to fit the format of the rest of them so, alright.

**Comment by ghost** [comment]
I sure hope this doesn't break the entire repo!!11!

**Pull request merged**
