### PR TITLE
Tourist

### PR DESCRIPTION
**Pull request by DangerRevolution**
## About the PR

Title.
## Why / Balance

A) I want this for a map in the works.
B) Useful for *other* maps
C) Again, provides a *reason* for someone to be on station more so than a miscellaneous "make your own, you're just someone on here" and Tourist is more of an `external` role; allowing for concepts such as "I don't know every single job on this station, what do you do here man dressed in yellows" which we normally can't RP. + can be given tours, the potential is higher and the requirement for someone to RP this; and for someone to understand IC that "hey, this person doesn't know the station inside and out" is more interesting.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
no changelog

### CODE REVIEW

**Comment by DangerRevolution** [comment]
also ready once i make something interesting for their job & PDA locale

**Comment by FluffiestFloof** [comment]
Mark it as draft if it isn't ready. Also this is literally Passenger but with a different name?

**Comment by DangerRevolution** [comment]
> this is literally Passenger but with a different name, icon (soon) and starting outfit

Yes

**Comment by rosieposieeee** [comment]
to be honest i think this is going to be the first time i ever say bloat. all of these extra passenger roles could just be handled through the loadout system. there was talk of letting people select different job titles too alongside that, i think that would be... better than adding a bunch of roles that do practically nothing

not to mention theres a really cool upstream pr for tourist as a minor "antag" which i think would be more interesting

**Comment by DangerRevolution** [comment]
> all of these extra passenger roles could just be handled through the loadout system

when loadout comes I'd be happy to merge these together into a Passenger megaclass along with the rest of the role bloat

**Comment by rosieposieeee** [comment]
> > all of these extra passenger roles could just be handled through the loadout system
> 
> when loadout comes I'd be happy to merge these together into a Passenger megaclass along with the rest of the role bloat

i think its a little silly to, in the meantime, add a bunch of roles that you KNOW are going to be removed, along with all the map edits itll require

**Comment by DangerRevolution** [comment]
> > > all of these extra passenger roles could just be handled through the loadout system
> > 
> > 
> > when loadout comes I'd be happy to merge these together into a Passenger megaclass along with the rest of the role bloat
> 
> i think its a little silly to, in the meantime, add a bunch of roles that you KNOW are going to be removed, 

I don't *know* they're going to be removed as I have no assurances that Loadouts will support manifest edits following ID changes; I don't even know if loadouts will be merged / finished and I don't know if we'll accept the amount of edits I want for loadouts.

> along with all the map edits itll require

This is optional for mappers; up to them if they want to have Tourists or not. I personally would want it for my map as a Passenger replacement, but other maps can not include them and it creates no extra burden for them.

**Comment by IamVelcroboy** [comment]
If this is for a specific map, I'd say add it along with the map PR. I didn't look too close at it but the tourist midround PR from upstream seems like it would be better than this. Or, when loadouts, I guess.

**Pull request closed without merging**
