### PR TITLE
Scav Ship & Meteors

### PR DESCRIPTION
**Pull request by CilliePaint**
## About the PR

Added 2 new Meteor Maps and 1 new Ship Map that can appear while Scavanging.

## Why / Balance

Mostly practicing mapping, plus it could be fun to have more variety to Scav!

## Media

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Screen shots would be helpful

**Comment by IamVelcroboy** [comment]
Maps also need to be added to `...\Resources\Prototypes\DeltaV\Maps\salvage.yml)`

**Review by DebugOk — COMMENTED** [review]
This needs to be added to the salvage thing too

**Comment by deltanedas** [comment]
above and tests probably fixed by pulling master

**Comment by IamVelcroboy** [comment]
Please send screenshots or I am going to close soon.

**Comment by IamVelcroboy** [comment]
Stale PR. Reopen if you come back to it.

**Pull request closed without merging**
