### PR TITLE
Shot-Gun Cabinet

### PR DESCRIPTION
**Pull request by ps3moira**
Adding a Shot-Gun Cabinet

## About the PR 
Added a Shotgun Cabinet

## Why / Balance

Something for sec outposts incase of an emergency and you have nothing else.

## Media
Screenshot 2023-11-02 001021

- [X] I have added a screenshot to this PR showcasing its changes ingame

**Changelog**

:cl:
- add: Added shotgun cabinets!

### CODE REVIEW

**Comment by DebugOk** [comment]
This shouldn't exist

**Comment by leonardo-dabepis** [comment]
> This shouldn't exist

why not? I think it would look cool in the armory. It shouldn't be outside the armory though.

**Comment by DebugOk** [comment]
> > This shouldn't exist
> 
> why not? I think it would look cool in the armory. It shouldn't be outside the armory though.

Because it's clearly intended to *not* be in the armory. __No guns should be naturally spawning outside the armory__. With very few exceptions.

**Comment by DebugOk** [comment]
> > > This shouldn't exist
> > 
> > 
> > why not? I think it would look cool in the armory. It shouldn't be outside the armory though.
> 
> Because it's clearly intended to _not_ be in the armory. **No guns should be naturally spawning outside the armory**. With very few exceptions.

Even just ignoring that,
```
  - type: AccessReader
    access: [["Security"], ["Command"]]
```
This is a gun that can just be accessed by anyone with security. I will not be giving my approval for this

**Comment by ps3moira** [comment]
> > > > This shouldn't exist
> > > 
> > > 
> > > why not? I think it would look cool in the armory. It shouldn't be outside the armory though.
> > 
> > 
> > Because it's clearly intended to _not_ be in the armory. **No guns should be naturally spawning outside the armory**. With very few exceptions.
> 
> Even just ignoring that,
> 
> ```
>   - type: AccessReader
>     access: [["Security"], ["Command"]]
> ```
> 
> This is a gun that can just be accessed by anyone with security. I will not be giving my approval for this

Would it be fine to changing it to just regular command and armory access?

**Comment by ps3moira** [comment]
> > > This shouldn't exist
> > 
> > 
> > why not? I think it would look cool in the armory. It shouldn't be outside the armory though.
> 
> Because it's clearly intended to _not_ be in the armory. **No guns should be naturally spawning outside the armory**. With very few exceptions.

It's not meant to be just out in the open, but reserved for Security Outposts and other things like that.

**Comment by DebugOk** [comment]
> > > > This shouldn't exist
> > > 
> > > 
> > > why not? I think it would look cool in the armory. It shouldn't be outside the armory though.
> > 
> > 
> > Because it's clearly intended to _not_ be in the armory. **No guns should be naturally spawning outside the armory**. With very few exceptions.
> 
> It's not meant to be just out in the open, but reserved for Security Outposts and other things like that.

Literally the exact same thing with these accesses

**Comment by ps3moira** [comment]
> > > > > This shouldn't exist
> > > > 
> > > > 
> > > > why not? I think it would look cool in the armory. It shouldn't be outside the armory though.
> > > 
> > > 
> > > Because it's clearly intended to _not_ be in the armory. **No guns should be naturally spawning outside the armory**. With very few exceptions.
> > 
> > 
> > It's not meant to be just out in the open, but reserved for Security Outposts and other things like that.
> 
> Literally the exact same thing with these accesses

I don't see the issue of having a cabinet, there's plenty of maps that have light-armory with sec officer access where people can grab shotguns, I don't see how adding a cabinet would be worse, if anything it'd be better to have a proper place to store it rather than on a rack.

**Comment by DebugOk** [comment]
> > Literally the exact same thing with these accesses
> 
> I don't see the issue of having a cabinet, there's plenty of maps that have light-armory with sec officer access where people can grab shotguns, I don't see how adding a cabinet would be worse, if anything it'd be better to have a proper place to store it rather than on a rack.

Name one. Because that shouldn't exist.

**Comment by deltanedas** [comment]
map named jackboots :trollface:

**Comment by ps3moira** [comment]
> > > Literally the exact same thing with these accesses
> > 
> > 
> > I don't see the issue of having a cabinet, there's plenty of maps that have light-armory with sec officer access where people can grab shotguns, I don't see how adding a cabinet would be worse, if anything it'd be better to have a proper place to store it rather than on a rack.
> 
> Name one. Because that shouldn't exist.

Why should it not exist? They're filled with non-lethals anyway and I've seen that they're almost never touched unless it's really needed.

**Comment by WakefieldLancer** [comment]
If I were Warden or HOS, I'd just grab the shotguns out of the cabinet on round start and bring them to armory.

As a sec officer I do NOT want a greytider getting weapons from somewhere that I don't know.

And I really don't want an antagonist having access to a place that may or may not be monitored that they can grab a locker or cabinet from and break it apart later. That's just asking for trouble IMO.

**Comment by DebugOk** [comment]
> > > > Literally the exact same thing with these accesses
> > > 
> > > 
> > > I don't see the issue of having a cabinet, there's plenty of maps that have light-armory with sec officer access where people can grab shotguns, I don't see how adding a cabinet would be worse, if anything it'd be better to have a proper place to store it rather than on a rack.
> > 
> > 
> > Name one. Because that shouldn't exist.
> 
> Why should it not exist? They're filled with non-lethals anyway and I've seen that they're almost never touched unless it's really needed.

So you can't name a single station with non-armory weapons in sec?

My original point stands. This will not be merged for its intended purpose, if at all

**Comment by ps3moira** [comment]
> > > > > Literally the exact same thing with these accesses
> > > > 
> > > > 
> > > > I don't see the issue of having a cabinet, there's plenty of maps that have light-armory with sec officer access where people can grab shotguns, I don't see how adding a cabinet would be worse, if anything it'd be better to have a proper place to store it rather than on a rack.
> > > 
> > > 
> > > Name one. Because that shouldn't exist.
> > 
> > 
> > Why should it not exist? They're filled with non-lethals anyway and I've seen that they're almost never touched unless it's really needed.
> 
> So you can't name a single station with non-armory weapons in sec?
> 
> My original point stands. This will not be merged for its intended purpose, if at all

Tortuga, Arena, Hammurabi, Edge (it used to at least)

**Comment by ps3moira** [comment]
> > > > > Literally the exact same thing with these accesses
> > > > 
> > > > 
> > > > I don't see the issue of having a cabinet, there's plenty of maps that have light-armory with sec officer access where people can grab shotguns, I don't see how adding a cabinet would be worse, if anything it'd be better to have a proper place to store it rather than on a rack.
> > > 
> > > 
> > > Name one. Because that shouldn't exist.
> > 
> > 
> > Why should it not exist? They're filled with non-lethals anyway and I've seen that they're almost never touched unless it's really needed.
> 
> So you can't name a single station with non-armory weapons in sec?
> 
> My original point stands. This will not be merged for its intended purpose, if at all

Your point is, "It shouldn't exist, name one station because that shouldn't exist, my point still stands."

**Comment by ps3moira** [comment]
> If I were Warden or HOS, I'd just grab the shotguns out of the cabinet on round start and bring them to armory.
> 
> As a sec officer I do NOT want a greytider getting weapons from somewhere that I don't know.
> 
> And I really don't want an antagonist having access to a place that may or may not be monitored that they can grab a locker or cabinet from and break it apart later. That's just asking for trouble IMO.

This isn't on just any wall or open area, it'd be placed typically at the very back of a Sec Outpost where they'd have to break into multiple doors then break the glass just to get a shotgun with non-lethal rounds. It'd be easier to just order a shotgun crate and break it open with a crowbar than do all of that.

**Review by DebugOk — CHANGES_REQUESTED** [review]
My point is I don't want this in game. It adds unsecured easily accessible weapons in places there shouldn't be weapons.

I'll use this review to make it even more clear that I do not want to see this merged for its intended purpose, as security officers shouldn't have easily accessible weapons, let alone outside of security.

**Comment by ps3moira** [comment]
> My point is I don't want this in game. It adds unsecured easily accessible weapons in places there shouldn't be weapons.
> 
> I'll use this review to make it even more clear that I do not want to see this merged for its intended purpose, as security officers shouldn't have easily accessible weapons, let alone outside of security.

Unsecured? Armory access for a non-lethal rounds shotgun in a Sec Outpost sounds pretty secure and not too easily accessible. It's also one of the most reasonable places where a emergency weapon would be when needed.

**Pull request closed without merging**
