### PR TITLE
Lowered the volume of the Femtanyl track

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Adjusted the gain by -10 dB.

## Why / Balance

It was loud.

### CODE REVIEW

**Comment by deltanedas** [comment]
is it not possible to adjust this in yml

**Comment by Colin-Tel** [comment]
> is it not possible to adjust this in yml

That's a damn good question.

**Review by ghost — APPROVED** [review]
Finally, Femtanyl at an acceptable volume instead of blasting it. Deltanedas poses a good point if that can be done in yaml but I'll accept the core file being lowered by like 10 decibels as a suitable fix for now.

Now only if Test Packaging would run...

**Comment by ghost** [comment]
Thanks Null!!!

**Pull request merged**
