### PR TITLE
Pebble maintenance

### PR DESCRIPTION
**Pull request by Bribrooo**
## About the PR
added metempsychosis machine, tropico in the detective's room, the 3 new machines for chems, dressers for heads

## Why / Balance
Pebble maintenance

## Technical details
None.

## Media
image
image
image
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**

- tweak: Reshaped the Chemistry department on Pebble to fit two new machines, alongside the Atmospheric department.
- tweak: Replaced the cloning pod for the metempsychosis machine on Pebble.
- add: Added Tropico for the Detective on Pebble.
- add: Added the heads' dressers (they get to have drip now)

### CODE REVIEW

**Comment by DangerRevolution** [comment]
#848 ? #731 ?

**Comment by DangerRevolution** [comment]
also the changelog is unnecessarily huge, "Tweak: Pebble has been updated to modern standards." would be more concise and still all-encompassing

**Comment by IamVelcroboy** [comment]
> also the changelog is unnecessarily huge, "Tweak: Pebble has been updated to modern standards." would be more concise and still all-encompassing

the `:cl:` was removed anyway so...it won't show up.

**Comment by DangerRevolution** [comment]
> > also the changelog is unnecessarily huge, "Tweak: Pebble has been updated to modern standards." would be more concise and still all-encompassing
> 
> the `:cl:` was removed anyway so...it won't show up.

:trollface:

**Comment by Bribrooo** [comment]
So just need to add a Pride-O-Mat then 😔

**Comment by IamVelcroboy** [comment]
> So just need to add a Pride-O-Mat then 😔

You've still got time if you want to add it. You did add the beacons?

**Comment by Bribrooo** [comment]
I have no idea how they work but I tried

**Comment by DangerRevolution** [comment]
> I have no idea how they work but I tried

Find any of the "Station Beacons", preferrably one that is tagged with whatever room you're putting them in. Place them down, right click --> View Variables --> Find their beacon component, change the location name to whatever location you're putting in. i.e don't put the Research Director beacon into Mystagogue's office.

You generally don't need them for pebble but it's good practice & there's new people coming in all the time.

**Review by IamVelcroboy — APPROVED** [review]

**Pull request merged**
