### PR TITLE
Halves Captain's Sabre bullet reflection

### PR DESCRIPTION
**Pull request by DangerRevolution**
## About the PR

Title.
Revival of #600 
## Why / Balance

I just watched a Felinid with nothing but the sabre and a gun duel several people and live because the Sabre was just reflecting their bullets

Delta also removed reflection for bullets from every item, except Cap's sabre. Even double e-sword doesn't have it.

**Changelog**
:cl: DangerRevolution
- tweak: Captain's Sabre reflection chance has been halved to match other Delta changes.

### CODE REVIEW

**Comment by Adrian16199** [comment]
Wasnt double esword just removed fully, even on wizden?
Same can be said about the reflective vest.
 but without counting these first two questions since they were only mentioned in the PR but nothin about them in the actual code.
 Technicly skeptical as captain will never have to deal with lasers unless nukies use lasers by raiding armoury and even then that is extremely rare but I digress, just my small grain of an opinion.
 If it was all about balance then I would just get rid of all reflection and just make the sabre deal more damage since the captain risks ALOT by going face to face compared to using glass doors with his laser (That technicly shouldnt even be carried at all times but nontheless)

**Comment by Adrian16199** [comment]
Or one can say, fuck it, we ball and just decrease the probability by half and just leave it at that, see how that will go instead of fully removing it, if its still a problem then remove it.

**Comment by DangerRevolution** [comment]
> ## About the PR
> Title.
> 
> ## Why / Balance
> I just watched a Felinid with nothing but the sabre and a gun duel several people and live because the Sabre was just reflecting their bullets
> 
> Delta also removed reflection for bullets from every item, except Cap's sabre. Even double e-sword doesn't have it.
> 
> **Changelog** 🆑 DangerRevolution
> 
> * tweak: Captain's Sabre can now only reflect lasers, similar to every other sword.



> Wasnt double esword just removed fully, even on wizden? Same can be said about the reflective vest. but without counting these first two questions since they were only mentioned in the PR but nothin about them in the actual code. Technicly skeptical as captain will never have to deal with lasers unless nukies use lasers by raiding armoury and even then that is extremely rare but I digress, just my small grain of an opinion. If it was all about balance then I would just get rid of all reflection and just make the sabre deal more damage since the captain risks ALOT by going face to face compared to using glass doors with his laser (That technicly shouldnt even be carried at all times but nontheless)

Double e-sword is still in, no idea if it's obtainable or if we merged it or not: Line 224 of e_sword.yml
The energy katana reflects, not sure what or what chance as it's set to the defaults from the component.
Captain's sabre still reflects, a damage boost could be considered.

When I was first making the change in #600, most swords reflect but that seems to have been changed. It's disabled on all the e-sword variants now:

```
- type: Reflect
    enabled: false
```

Not really sure what wizden are balancing but :shrug:

```
- type: entity
  name: double-bladed energy sword
  parent: EnergySword
  id: EnergySwordDouble
  description: Syndicate Command Interns thought that having one blade on the energy sword was not enough. This can be stored in pockets.
  components:
  - type: EnergySword
  - type: ItemToggle
    soundActivate:
      path: /Audio/Weapons/ebladeon.ogg
      params:
        volume: 3
    soundDeactivate:
      path: /Audio/Weapons/ebladeoff.ogg
      params:
        volume: 3
  - type: ItemToggleMeleeWeapon
    activatedSoundOnSwing:
      path: /Audio/Weapons/eblademiss.ogg
      params:
        volume: 3
        variation: 0.250
    activatedDamage:
        types:
            Slash: 12
            Heat: 12
            Structural: 15
  - type: ItemToggleActiveSound
    activeSound:
      path: /Audio/Weapons/ebladehum.ogg
      params:
        volume: 3
  - type: ItemToggleDisarmMalus
    activatedDisarmMalus: 0.7
  - type: Wieldable
  - type: MeleeWeapon
    wideAnimationRotation: -135
    attackRate: 1.5
    angle: 100
    damage:
      types:
        Blunt: 4.5
  - type: Sprite
    sprite: Objects/Weapons/Melee/e_sword_double.rsi
    layers:
      - state: e_sword_double
      - state: e_sword_double_blade
        color: "#FFFFFF"
        visible: false
        shader: unshaded
        map: [ "blade" ]
  - type: Item
    size: Small
    sprite: Objects/Weapons/Melee/e_sword_double-inhands.rsi
  - type: Reflect
    reflectProb: .80 #DeltaV: 80% Energy Reflection but no ballistics.
    spread: 75
    reflects:
      - Energy #DeltaV: 80% Energy Reflection but no ballistics.
  - type: UseDelay
    delay: 1
  - type: ToggleableLightVisuals
    spriteLayer: blade
    inhandVisuals:
      left:
      - state: inhand-left-blade
        shader: unshaded
      right:
      - state: inhand-right-blade
        shader: unshaded
```

**Comment by Adrian16199** [comment]
If a damage increase would be given, then I would just say to completely get rid of reflection...
We dont want a syndicate with double eswords that didnt even paid singular TC after murdering the captain. Again. (Mostly saying this because the double esword had stupid amount of damage and if we keep laser chance then any disabler shot would just ger reflected right into officer's face)
However I would still advise first just halfing the chance at first, there can always be another time where you could nerf it even more.

**Comment by DangerRevolution** [comment]
> If a damage increase would be given

Honestly a damage rebalance is long on the cards IMO for Delta, probably worth doing it there if that ever happens.

> However I would still advise first just halfing the chance at first, there can always be another time where you could nerf it even more.

I'll do that then.

**Comment by Adrian16199** [comment]
> > If a damage increase would be given
> 
> Honestly a damage rebalance is long on the cards IMO for Delta, probably worth doing it there if that ever happens.
> 
> > However I would still advise first just halfing the chance at first, there can always be another time where you could nerf it even more.
> 
> I'll do that then.

Its been 5 days and still wasnt done 😔

**Comment by DangerRevolution** [comment]
> > > If a damage increase would be given
> > 
> > 
> > Honestly a damage rebalance is long on the cards IMO for Delta, probably worth doing it there if that ever happens.
> > > However I would still advise first just halfing the chance at first, there can always be another time where you could nerf it even more.
> > 
> > 
> > I'll do that then.
> 
> Its been 5 days and still wasnt done 😔

real. hope this is finished.

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Comment by deltanedas** [comment]
good

**Comment by IamVelcroboy** [comment]
Upstream merge just reduced this to 10%. Technically, this would be a buff now. Is this still the change we want?

**Comment by DangerRevolution** [comment]
> Upstream merge just reduced this to 10%. Technically, this would be a buff now. Is this still the change we want?

no

**Comment by DangerRevolution** [comment]
only way to improve on upstream is to remove it outright

**Comment by DangerRevolution** [comment]
upstreams reflect chance is double the proposal here, reopening

**Comment by DangerRevolution** [comment]
wait no github lied to me

**Comment by DEATHB4DEFEAT** [comment]
> Upstream merge just reduced this to 10%. Technically, this would be a buff now. Is this still the change we want?

I like 25 more than 10, and was aware of WizDen's change at my approval time.

**Comment by DangerRevolution** [comment]
> > Upstream merge just reduced this to 10%. Technically, this would be a buff now. Is this still the change we want?
> 
> I like 25 more than 10, and was aware of WizDen's change at my approval time.

I *can* reopen it but I *personally* don't like reflect chance at all tbh for non-laser projectiles, if it's something we want I can just reopen it.

**Comment by deltanedas** [comment]
i would just wait for https://github.com/space-wizards/space-station-14/pull/27219

**Pull request closed without merging**
