### PR TITLE
Merge wizden up to 27/11

### PR DESCRIPTION
**Pull request by DebugOk**
Mostly because of the anti spam thing, also to fix a few bugs.

Finally replaces our mothroaches with wizdens ones, and also adds cockroaches as a result. Their AI now likes to nibble on discarded clothing :)

image

Last commit merged: https://github.com/space-wizards/space-station-14/commit/e0dd5e1b52641c0380889efb949b827aadaaaea7

### CODE REVIEW

**Comment by DebugOk** [comment]
@Colin-Tel I see errors related to edge and some other maps, if you have the time to take a look that'd be nice

**Comment by Colin-Tel** [comment]
image
tf is "Default"

**Comment by Colin-Tel** [comment]
image
This??

**Comment by IamVelcroboy** [comment]
Do other maps have that?

**Comment by Colin-Tel** [comment]
> Do other maps have that?

looks like all 2 entries under `DrinkGlass` get this. I'll test if removing these two entities will fix it.
image

**Comment by DebugOk** [comment]
> > Do other maps have that?
> 
> looks like all 2 entries under `DrinkGlass` get this. I'll test if removing these two entities will fix it. image

One sec

**Comment by DebugOk** [comment]
https://github.com/space-wizards/space-station-14/commit/269c93245d5b9eac71a0314a3b9a47411faafbb6#diff-e4f2550ad012db0f9154412198b8f53e86d0f2f45740ad3d7eba86448c52d13b

See Resources/Maps/atlas.yml

**Comment by Colin-Tel** [comment]
> [space-wizards/space-station-14@269c932#diff-e4f2550ad012db0f9154412198b8f53e86d0f2f45740ad3d7eba86448c52d13b](https://github.com/space-wizards/space-station-14/commit/269c93245d5b9eac71a0314a3b9a47411faafbb6#diff-e4f2550ad012db0f9154412198b8f53e86d0f2f45740ad3d7eba86448c52d13b)
> 
> See Resources/Maps/atlas.yml

So everything including and below `- thresholds:`
image

**Comment by DebugOk** [comment]
No idea, thats what they did. Right now I'd hold off on merging this as wizden is merging stuff right now that I'll also include

**Comment by Colin-Tel** [comment]
@DebugOk Velcro and I can make these changes to our maps in our map PRs we opened today, then merge them

**Comment by IamVelcroboy** [comment]
What changes? Just some new dirty data?

**Comment by Colin-Tel** [comment]
> What changes? Just some new dirty data?

The change we'd need to do, as it seems now, is to remove the `- thresholds:` component and its contents if they are present in any entity of `DrinkGlass`.

**Comment by IamVelcroboy** [comment]
Cool. Will be back at my pc in about 15

**Comment by Colin-Tel** [comment]
huh... wait. there is no "thresholds:" in Edge though

> image This??

**Comment by Colin-Tel** [comment]
it *looks* like some kind of audio parameters actually

**Comment by IamVelcroboy** [comment]
Should we run it through the cleaners? (Magil's tool)

**Comment by Colin-Tel** [comment]
Just to mention it here, I've committed the following change after testing it in the dev environment, and there's no negative aspect on the map's ability to run.

image

According to Velcro, apparently only Edge has this, so I'll merge it in #484 if tests are alright with it.

**Comment by DebugOk** [comment]
> Should we run it through the cleaners? (Magil's tool)

I'd have to update that

**Comment by DebugOk** [comment]
@Colin-Tel Try running the tidy tool after making this change

```diff
 # These components should be okay to remove entirely.
 REMOVE_COMPONENTS = [
     "AmbientSound",
     "EmitSoundOnCollide",
     "Fixtures",
     "GravityShake",
     "HandheldLight", # Floodlights are serializing these?
+    "PlaySoundBehaviour",
 ]
```

**Comment by DebugOk** [comment]
> @Colin-Tel Try running the tidy tool after making this change
> 
> ```diff
>  # These components should be okay to remove entirely.
>  REMOVE_COMPONENTS = [
>      "AmbientSound",
>      "EmitSoundOnCollide",
>      "Fixtures",
>      "GravityShake",
>      "HandheldLight", # Floodlights are serializing these?
> +    "PlaySoundBehaviour",
>  ]
> ```

Still dont know if this worked or not, but I'll psuh it into the tidy tool anyways

**Comment by DebugOk** [comment]
I'm assuming all our custom maps will need to have the tidy tool ran on it, which I'm definitly not going to be doing right now

**Comment by IamVelcroboy** [comment]
I can do that, maybe in an hour or so. I assume the "normal" stuff is referring to something using the upstream storage/inventory.

**Comment by OCOtheOmega** [comment]
Soon we'll have to do second wizden merge already or update this one. They've redone a lot of stuff already...

**Comment by DebugOk** [comment]
> Soon we'll have to do second wizden merge already or update this one. They've redone a lot of stuff already...

Fixing these problems is easier said then done when you also have a job

**Comment by DebugOk** [comment]
I'm just gonna redo all of this :blunt:

**Pull request closed without merging**
