### PR TITLE
Chef ship

### PR DESCRIPTION
**Pull request by Unkn0wnGh0st333**
## About the PR
Replace the traveling cuisine chef ship with the Piecrust from Frontier!

## Why / Balance
the traveling chef isn't chosen often and notably has a pretty crappy shuttle that doesn't make for the best place to eat. This will hopefully encourage players to pick it up more often and have a more enjoyable experience with it. It includes a lot more features such as hydroponics, filtering atmos, and animals.

This is an edited version of the original Piecrust with some differences here and there for better use on DeltaV.

## Technical details
Requires https://github.com/DeltaV-Station/Delta-v/pull/2373/ to function

## Media
image

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Bleh

**Changelog**
🆑 

- Traveling Cuisine has gotten an upgrade to their ride. They will now spawn with a modified version of the Frontier Piecrust shuttle!

### CODE REVIEW

**Comment by Unkn0wnGh0st333** [comment]
What the fuck

**Comment by Avalon-Proto** [comment]
Damn why'd you instantly close this it looks nice

**Comment by Radezolid** [comment]
Because they bundled it with the #2373 commit by accident.

**Comment by Avalon-Proto** [comment]
Oh I see that now. Woops

**Comment by deltanedas** [comment]
fell off...

**Pull request closed without merging**
