### PR TITLE
ERT Overhaul 2.5

### PR DESCRIPTION
**Pull request by Tryded**
## About the PR

ERT Overhaul 2.5, different levels for ert you know the drill
Basically, 3 levels of ERT
Amber: The same as their station counterparts but a bit better. Basically extra staff and can't take on huge threats.
Red: Normal level ERT. Same as their station counterparts but everyone gets a hardsuit and are armed with better gear and equipment. Comparable to a nuclear strike team but a bit worse. Will still fall apart and die if unorganized.
Gamma: Elite ERT. Way better than their station counterparts and has enough gear and equipment to deal with even the worst threats. Comparable or better than nuclear strike teams.
## Why / Balance

ERT too OP and if we just make a single level of ERT it'll mostly be either overkill for the situation or immediately dies
Also people want this.
Discussion on ERT in General: https://discord.com/channels/968983104247185448/968983104662409244/1175969964692353085
Random people agreeing with ERT overhaul: https://discord.com/channels/968983104247185448/968983104662409244/1175967756122861608
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
image

https://github.com/DeltaV-Station/Delta-v/assets/139474617/bd793c0a-7165-4cc4-a6bc-82e66c0f7fc3
## Breaking changes

**Changelog**

:cl: Tryded
- add: Added different tiers of Emergency Response Teams for central command (admins) to deploy during times of crisis. Amber < Red < Gamma

### CODE REVIEW

**Comment by Tryded** [comment]
I have no idea why is the RSI failing
`Resources/Textures/DeltaV/Objects/Weapons/Guns/Battery/mini_energygun.rsi: mag-unshaded-0: sprite sheet of 32x32 is too small, metadata defines 2 frames, but it can only fit 1 at most
`

**Comment by Tryded** [comment]
This PR is ready for review

**Comment by Colin-Tel** [comment]
It's not likely we will be merging this, primarily because:

1. ERT is **not OP**, it has historically failed numerous times.
2. ERT is hardly used as it is, and we don't plan on using it more. We don't need to add any complexity to a barely used system like ERT

The energy weapons, however, do look cool and I think they could be potentially be worth reviewing in their own PR.

**Comment by Tryded** [comment]
> It's not likely we will be merging this, primarily because:
> 
> 1. ERT is **not OP**, it has historically failed numerous times.
> 2. ERT is hardly used as it is, and we don't plan on using it more. We don't need to add any complexity to a barely used system like ERT
> 
> The energy weapons, however, do look cool and I think they could be potentially be worth reviewing in their own PR.

ERT is OP due to their pulse weapons and high level gear.

And the Point of adding this is to incentivizes the use of ERT as it allows admins to spawn ERT without the chance of losing overpowered gear and high risk items to the station. It also gives more potential ghost roles to be used. (also partially cope because I spent way too much time on this, people seem to want it and are expecting it soon.)

You put old ERT with a nukie. The ERT is going to win due to their gear and mainly, pulse carbine.

**Comment by Tryded** [comment]
The plan is for when shit goes down, a small team ranging from 3 to 8 ERT personnel arrive, with their tier level being what is suppose to be sent.

This is hard to know the results of unless we test it in a live round, so we should probably test this first and if it doesn't work, we revert it and I make a different PR for the guns.

And you don't have to send 1 of each department all the time, you send what is needed. Also, the station should choose between calling an Emergency response team or a shuttle, not both at once. ERT does not need a shuttle to get to the station, it could be easily done with bluespace teleportation and when the crisis is over they could be teleported back to central command and either deleted from existence or chill at the centcom bar.

**Comment by Tryded** [comment]
+ ERT is hardly used right now because it requires your's or Based's approval and due to the lack of options that could really be chosen between. ERT either completely destroys the threat or dies terribly. Tension can still be maintained even with ERT entering the station. It's like firefighters being sent into a burning building, the tension is still there, just that there will be a lot less dead people. Also it gives the dead something to do.

**Comment by Tryded** [comment]
Discussion in general on ERT https://discord.com/channels/968983104247185448/968983104662409244/1175969964692353085

**Comment by Tryded** [comment]
https://discord.com/channels/968983104247185448/968983104662409244/1175967756122861608 General Approval of this

**Comment by Tryded** [comment]
Some game administrators also believe that this PR will be beneficial

**Comment by Colin-Tel** [comment]
I'd be a lot more interested in this if you just ditched the "three tiers" nonsense and just kept it with "one has EVA the other doesn't"

**Comment by Tryded** [comment]
> I'd be a lot more interested in this if you just ditched the "three tiers" nonsense and just kept it with "one has EVA the other doesn't"

Hm what about ditching Gamma level since that is basically the other tier added.

**Comment by Colin-Tel** [comment]
Why do they need to have levels?

**Comment by Tryded** [comment]
> Why do they need to have levels?

You don't want to send an elite team to a low level threat or crisis (a lot of people dead)

Nor do you want to send a weak team to deal with a high level threat (Space dragon that somehow survived security and flooded the station with tens of carps

**Comment by Colin-Tel** [comment]
> You don't want to send an elite team to a low level threat or crisis (a lot of people dead)

I'm not sending ERT for a low level threat. I'm letting the crew figure it out.

> Nor do you want to send a weak team to deal with a high level threat (Space dragon that somehow survived security and flooded the station with tens of carps

ERT are highly trained operators with best-of-the-best equipment.

**Comment by Tryded** [comment]
> > You don't want to send an elite team to a low level threat or crisis (a lot of people dead)
> 
> I'm not sending ERT for a low level threat. I'm letting the crew figure it out.
> 
> > Nor do you want to send a weak team to deal with a high level threat (Space dragon that somehow survived security and flooded the station with tens of carps
> 
> ERT are highly trained operators with best-of-the-best equipment.

It gives more options for admins to use to their discretion. It also doesn't hurt to have these levels.

Most of the time when you need ERT with the best equipment, you need EVA gear. The amber ones are meant for when centcom still wants to save their station, but doesn't want to use the best of the best.

If this is merged in its current state, we could see which ones are used the most and which ones are never used. Then we can adjust accordingly.

**Comment by Tryded** [comment]
Also Everyone gets microbomb implants

**Comment by Colin-Tel** [comment]
> It gives more options for admins to use to their discretion. It also doesn't hurt to have these levels.

I don't think we need more options as far as ERT loadouts. The existing "ERT w/ EVA, ERT w/o EVA" is perfectly fine as it is.

> Most of the time when you need ERT with the best equipment, you need EVA gear. The amber ones are meant for when centcom still wants to save their station, but doesn't want to use the best of the best.

ERT loadouts by themselves are often supplemented by the admin spawning extra stuff for them if they feel the need. We can just give them the default ERT unit with its base loadout if we don't think they need much.

> If this is merged in its current state, we could see which ones are used the most and which ones are never used. Then we can adjust accordingly.

We're not going to merge this just to have people say "Let's send ERT, I mean we gotta test it, right?"

**Comment by Tryded** [comment]
> > It gives more options for admins to use to their discretion. It also doesn't hurt to have these levels.
> 
> I don't think we need more options as far as ERT loadouts. The existing "ERT w/ EVA, ERT w/o EVA" is perfectly fine as it is.
> 
> > Most of the time when you need ERT with the best equipment, you need EVA gear. The amber ones are meant for when centcom still wants to save their station, but doesn't want to use the best of the best.
> 
> ERT loadouts by themselves are often supplemented by the admin spawning extra stuff for them if they feel the need. We can just give them the default ERT unit with its base loadout if we don't think they need much.
> 
> > If this is merged in its current state, we could see which ones are used the most and which ones are never used. Then we can adjust accordingly.
> 
> We're not going to merge this just to have people say "Let's send ERT, I mean we gotta test it, right?"

Eh well, if we are doing that, what loadout you propose that they spawn with?

**Comment by DebugOk** [comment]
I will just come in here to say this will very likely not be merged, as I don't see this being beneficial in any way.

Since this is touching so many core files, it assures we'll have merge conflicts when Wizden changes ERT again, for something we simply will not use.

Admins don't use ERT for a good reason. If we want them nerfed, we just take away the pulse weapons. Which has been done before.

**Comment by Tryded** [comment]
Welp, I believe that this is it.

**Comment by Tryded** [comment]
This is 100% not going to get merged now.

**Comment by DebugOk** [comment]
Wizden *may* be interested in this, as they seem to use ERTs more often than we do

**Comment by Tryded** [comment]
> Wizden _may_ be interested in this, as they seem to use ERTs more often than we do

Problem is, majority of the weapons here are custom made in this PR and it uses Energy Weapons code from deltaV

**Comment by Tryded** [comment]
and I don't play on wizden, which means I cannot at all really argue balance with them and it would be hard to justify to make a second overhaul

**Comment by Tryded** [comment]
Anyways, as Colin said, I'll make another PR for the guns

**Pull request closed without merging**
