### PR TITLE
Remove Head Clothing From Uniform Printer

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

Request from AJ to stop common HOP issue of them handing out cap uniform to random crew.

**Changelog**
:cl:
- tweak: HoP's Uniform printer can no longer print the clothing of all other heads. HoP's clothing can still be printed.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
May be one of the best PR's yet, although ppl should really just get perma banned for this.

**Comment by therealDLondon** [comment]
Yeah makes sense to me, this has the headmin a-ok!

**Review by Axionyxx — APPROVED** [review]
"Request from *random admin*" isn't proper approval, and still requires the pr to be filled out as normal.

**Comment by rosieposieeee** [comment]
...is it not? i figured this was too small a change to bother with a changelog, but i can add it if wanted

**Comment by DangerRevolution** [comment]
> ...is it not? i figured this was too small a change to bother with a changelog, but i can add it if wanted

I imagine Null meant the other categories, like media, changelog and "why"

**Comment by rosieposieeee** [comment]
it has why, it doesnt need an image, its a single page YML change. it doesnt deserve the ritz

**Comment by angelofallars** [comment]
@rosieposieeee It seems like the uniform printer can still print HoP uniforms, as they should since the HoP is the one who owns it. So shouldn't the changelog be something like

> tweak: HoP's Uniform printer can no longer print the clothing of all other heads. HoP's clothing can still be printed.

**Comment by rosieposieeee** [comment]
yeah sure, i figured 'cannot print _all_ heads' already implied it but that works too

**Comment by TadJohnson00** [comment]
I was about to note that this prevents Heads of Security from using their alternate uniforms but I'm assuming this will be merged post-loadouts?

**Comment by angelofallars** [comment]
> I was about to note that this prevents Heads of Security from using their alternate uniforms but I'm assuming this will be merged post-loadouts?

These are the uniforms that the HoS can have in loadouts in the Delta-V `master` branch:

image

From what I can tell, the HoS uniforms removed by the PR are still usable with the loadouts, except for these uniforms:
- head of security's blue jumpsuit (`ClothingUniformJumpsuitHoSBlue`)
- head of security's grey jumpsuit (`ClothingUniformJumpsuitHoSGrey`)
- head of security's parade uniform (`ClothingUniformJumpsuitHoSParadeMale`, `ClothingUniformJumpskirtHoSParadeMale`)

I haven't checked yet, but if the HoS doesn't have these uniforms in their office, it might be a good idea to add these missing jumpsuits to the HoS loadout in another PR.

**Comment by TadJohnson00** [comment]
Currently working on editing my security resprite PR to accommodate. Might take a minute, there's a LOT to fix here with the loadouts.

**Comment by Axionyxx** [comment]
When the conflict is fixed, feel free to @ me directly for a rereview

**Comment by rosieposieeee** [comment]
nyehhhhh

**Pull request closed without merging**
