### PR TITLE
Allow vulps to wag

### PR DESCRIPTION
**Pull request by pissdemon**
## About the PR
Vulps can now toggle wagging if their tail supports it. Corgi and dalmatian tails also get a non-wagging variant courtesy of CD.

## Why / Balance
People have wanted this for a while, I guess?

## Known issues
- Button is still displayed when the tail does not have a wagging animation (which a few do, I think it's: fennec, fox2, fox3, fluffy, otie, long). Nothing will happen if you click on it. Maybe a bit confusing.
- Will log a warning to the server console when someone tries to wag with a tail that doesn't have a wagging animation.

## Technical details
Basically ported from https://github.com/cosmatic-drift-14/cosmatic-drift/pull/214. Uses the lizard tail wagging system. Old "wag" variants are removed and replaced with hidden (in character setup) "animated" variants.

## Media
It's exactly the same as the lizard tail wagging.

## Breaking changes
Database needs a migration to be run on it that fixes the markings field on profiles, since this PR removes the "wagging" variants we used to have and people have those selected. They need to be replaced with the non-wagging variant in the DB, just look at #rebase. 

**Changelog**
:cl:
- tweak: Vulpkanins can now toggle wagging their tails. (Some tails cannot wag yet, please contribute sprites for them!)

### CODE REVIEW

**Comment by pissdemon** [comment]
YAML linter fail not related to this PR but railguns, filed as #1153

**Comment by pissdemon** [comment]
Will probably make the migration part handled with an EF migration later

**Comment by Samsterious** [comment]
Cool. More non-intrusive roleplay mechanics that give people just a little more flexibility? Hell yeah. CD is a treasure trove of uninvasive HRP features that work just fine in MRP, and I am super down to see more PRs mirroring their successes.

**Comment by pissdemon** [comment]
Closing this in favor of a port of this from EE or something.

**Pull request closed without merging**
