### PR TITLE
Make space ruins dirty!

### LINKED ISSUE #1423: Space Ruins Are Way Too Clean
## Description
They're absolutely shiny. Not sure how often they are even being visited these days but they should be dirtied up a bit. 

**Reproduction**
n/a

**Screenshots**
Not a speck of dirt in sight 
image

**Additional context**
Low priority. But would be nice

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
Made the ruins look less like perfect pieces floating in space and more like they degraded overtime.

## Why / Balance
Fixes #1423 fully if merged with #2390.

## Technical details
Map changes.

## Media
`whiteship_ancient.yml`
image
`relaystation.yml`
image
`old_ai_sat.yml`
image
`derelict.yml` (This is way too big to see any details)
image

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Now ruins are a dirtier and a bit more broken.

### CODE REVIEW

**Comment by deltanedas** [comment]
you can use num 4 and 6 to zoom in and out

**Comment by Radezolid** [comment]
> you can use num 4 and 6 to zoom in and out

I know, but walls stops rendering beyond a certain point, if you know how to prevent that i will post the images.

**Comment by IamVelcroboy** [comment]
> > you can use num 4 and 6 to zoom in and out
> 
> I know, but walls stops rendering beyond a certain point, if you know how to prevent that i will post the images.

`sudo cvar net.pvs false` is your friend

**Comment by deltanedas** [comment]
(when it freezes for like 10 seconds thats normal)

**Comment by Radezolid** [comment]
I just noticed i forgot atmos on derelict, gonna do that tomorrow. Thanks for the command.

**Comment by Radezolid** [comment]
Done, I plan on modifying derelict again once AI turrets are added to make it more faithful to the original.

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
