### PR TITLE
Alternative wagging tail for felinids.

### PR DESCRIPTION
**Pull request by Adrian16199**
More options for felinids.

Ported from TG station.

## Why / Balance

More felinid customization = better
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/DeltaV-Station/Delta-v/assets/144424013/f25987d5-5803-4c2b-afdc-b4d43cd814bc

**Changelog**

:cl:
- add: An alternative wagging tail for felinids.

### CODE REVIEW

**Comment by DebugOk** [comment]
> I have added screenshots/videos to this PR showcasing its changes ingame, or this PR does not require an ingame showcase

> Doesnt add screenshots to this pr showing the changes in game

**Comment by Adrian16199** [comment]
Buh. 😔

**Comment by DebugOk** [comment]
@leonardo-dabepis How's this?

**Comment by leonardo-dabepis** [comment]
> @leonardo-dabepis How's this?

looks good 👍

**Pull request merged**
