### PR TITLE
Centcomm justice update

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- added rooms for the justice department so trial at centcom is slightly less of a meme
- replaced map "posters" from upstream with station maps and lost nyano maps
- replaced a lot of static vending machines with random spawners for some variety
- put beacons everywhere

## Why / Balance
quick eorg squad look at the funny beacons on the map!!!
eorg has been eliminated

**Changelog**
:cl:
ADMIN:
- tweak: CentComm now has a justice department if you want to use it for admemes.

i have no idea if admin cl works :trollface:

### CODE REVIEW

**Comment by therealDLondon** [comment]
The centcom update is real? Not clickbait?

**Review by Axionyxx — CHANGES_REQUESTED** [review]
Modifying base maps bad. Move it to DeltaV/centcomm.yml or something and swap mentions of it out

**Comment by IamVelcroboy** [comment]
I'll take a look at this when I get a chance and we can probably temp merge it so it has the justice content. We do have a WIP CC map that I wan to revive in a few weeks though. So, either this gets merged into that or it gets overridden 🤷‍♂️. Will figure that out when I get there. 

But yes, I agree with Null it should be moved to a DV directory so we don't have to deal with conflicts.

**Comment by deltanedas** [comment]
> We do have a WIP CC map that I wan to revive in a few weeks though.

just ignore what i have here then when the time comes and do whatevers best for the new cc

**Review by IamVelcroboy — APPROVED** [review]

**Comment by IamVelcroboy** [comment]
> Modifying base maps bad. Move it to DeltaV/centcomm.yml or something and swap mentions of it out

This was addressed. Can you dismiss please.

**Review by Axionyxx — APPROVED** [review]

**Pull request merged**
