### PR TITLE
make nukie require a round of engi and salv

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
2h engi department requirement = 1 round
2h salv = 1 round therefore ultra robust

## Why / Balance
some motherfucker opted into nukie and didnt know HOW TO PUT ON A HELMET im not making this up

## Technical details
no

## Media
no

### CODE REVIEW

**Comment by DangerRevolution** [comment]
while we're here it's shrimply worth just slapping 2 hours of every department onto it

**Comment by stellar-novas** [comment]
what about salv time?

**Comment by deltanedas** [comment]
salv no longer sosa robust powergamer so useless :trollface:

**Comment by stellar-novas** [comment]
it still teaches you how to eva and a tiny bit of combat
ig sec does too but it teaches 0g combat idk

**Review by DEATHB4DEFEAT — APPROVED** [review]

**Pull request merged**
