### PR TITLE
enforcer, m-90 and adjutant wield sprites

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

gives the 64x enforcer sprite to adjutant (it was commented out for whatever reason, but works)
gives the lecter sprite to enforcer and M-90s (it's generic enough no one will notice)
might comment out vulcans in a separate PR so it's easier to revert in the future when we get proper sprites, but because of licensing I can't give it the lecter sprite

carabinenogl.rsi meta.json reformat because holy fuck

## Why / Balance

https://github.com/DeltaV-Station/Delta-v/issues/1939 open for ages yet no one does anything so

## Media

Enforcer/M-90
image

Adjutant
image

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added the Enforcer, M-90 and Adjutant wield sprites.

### CODE REVIEW

**Comment by Unkn0wnGh0st333** [comment]
Hilarious I was finna ask you if TJ was getting this done

**Comment by MilonPL** [comment]
> Hilarious I was finna ask you if TJ was getting this done

clearly not seeing how long the issue is open for, but you can sprite Vulcans so I don't have to comment it out

**Comment by SolStar2** [comment]
My partner who does sprite work was just asking about this they can get on this if it's not claimed already.

**Comment by MilonPL** [comment]
> My partner who does sprite work was just asking about this they can get on this if it's not claimed already.

Having custom sprites would be so much better than reusing the generic one, this was meant as a band-aid because no one would sprite it. But feel free to!

**Comment by chamomileteatime** [comment]
I'm the partner Ewokswagger mentioned; I'm currently looking into making sprites for this stuff (aka crying trying to navigate all the folders)

**Comment by deltanedas** [comment]
we will wait for your new sprites then

**Comment by TadJohnson00** [comment]
@chamomileteatime Hi, I'm TJ. I hear you're taking on the work of setting up wielded sprites for some of my work. Feel free to give me a ping on Discord and I can help you out with that.

**Comment by SolStar2** [comment]
Sorry they have been a bit swamped with exam season but they say they will reach out to you on Discord once that's over. @TadJohnson00

**Pull request closed without merging**
