### PR TITLE
add carp hardsuit for traitors

### PR DESCRIPTION
**Pull request by deltanedas**
cherry picked from upstream

### CODE REVIEW

**Comment by therealDLondon** [comment]
Cant this wait for the main upstream merge? This isnt of vital importance to DeltaV

**Comment by WarMechanic** [comment]
icarus carp bombing is vital to delta v

**Comment by DangerRevolution** [comment]
the actual answer is that last word on upstream merge put it a month away

**Comment by deltanedas** [comment]
no this cant wait a month we need advanced fishops

**Comment by Squishy77** [comment]
Now we can re the hard suit

**Comment by deltanedas** [comment]
valid

**Pull request closed without merging**
