### PR TITLE
submarine atmosia update

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- actual working cooling that you dont need to replace with a freezer, fully deals with full power operation
- burn chamber is an actual burn chamber
- non-meme teg piping + moved the beacon over by 1
- tritburn mix line
- made kitchen freezer actually functional

i would also remove 99% of atmos since its useless but too much for this :trollface:

### CODE REVIEW

**Comment by deltanedas** [comment]
wish it was merged faster so no manual update needed :trollface:

**Comment by IamVelcroboy** [comment]
@deltanedas hey, seems like Submarine needs help with the TEG again if you feel up to fixing it? Let me know.

**Comment by deltanedas** [comment]
i will look at it in a bit

**Comment by rosieposieeee** [comment]
> i will look at it in a bit

HEEEEEEEEEEEEEEEEEEEEEEEEEEEROOOOOOOOOOOOOOOOOOOOO

you can do whatever the fuck you want with the entire area i dont care

**Pull request merged**
