### PR TITLE
Pebble Update June 20th

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
- Removed Cloning
- Adds Cryogenics (With adjusted pump because the gate = a pump)
- Moves left evac pod and psych office more left
- Adjusts north evac hallway
- Adjusts medbay
## Why / Balance
Cloning 1984

**Changelog**

:cl: DLondon
- tweak: Adjusts pebble's medical

### CODE REVIEW

**Comment by UnicornOnLSD** [comment]
not sure about the passive gate instead of regular gas pump, will it let a certain amount of pressure in and not out ? There was a volumetric pump back on tortuga once and it just overpressurised the system so y'know, making sure

**Comment by UnicornOnLSD** [comment]
also I still see a plasma miner I MIGHT have forgotten while taking care of the map myself, so yep

**Comment by deltanedas** [comment]
if someone sets distro to 600kpa or something it would overpressurize cryo, use a pressure pump
also ideally the filters would be reworked to be inline so they dont mess up pressure too but yeah

**Comment by therealDLondon** [comment]
Ill be real I made a buncha silly errors ill fix this all properly another time

**Pull request closed without merging**
