### PR TITLE
Add the syringe gun as research

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
Added the syringe gun as a civilian T2 research.

## Why / Balance
Mostly for the funs and antag antics.

## Technical details
YAML modifications and a locale.

## Media
image
image
image

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**

:cl:
- tweak: The syringe gun is now a researcheable technology in the T2 civilian category. Get it from the medical techfab once it's researched.

### CODE REVIEW

**Comment by Radezolid** [comment]
Oh god what did i do LMAO.

**Comment by Stop-Signs** [comment]
I would maybe consider adding the recipes to emagged protolathes

**Comment by Stop-Signs** [comment]
> I would maybe consider adding the recipes to emagged protolathes

on second thought, probably not.

**Comment by Avalon-Proto** [comment]
> > I would maybe consider adding the recipes to emagged protolathes
> 
> on second thought, probably not.

Nono, i'd say do it, else its *only* open to med antags/players and no one else. Would rather it be possible to get it from an emagged autolathe

**Comment by deltanedas** [comment]
autolathe is for roundstart things so emagged protolathe is a better fit

**Review by deltanedas — CHANGES_REQUESTED** [review]
add to protolathes emagDynamicRecipes

**Comment by Radezolid** [comment]
ngl, i don't see too much use unless they get nocturine, but sure.

**Review by deltanedas — APPROVED** [review]

**Comment by Radezolid** [comment]
Tests comes OK locally, dunno.

**Comment by MilonPL** [comment]
It's fake

**Pull request merged**
