### PR TITLE
Remove controversial AI name

### PR DESCRIPTION
**Pull request by Stop-Signs**
## About the PR
unfortunately this has caused too many issues after less than a day

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by therealDLondon** [comment]
I dont understand the controversy at all. Blitz means "Lightning" or "Flash" in German.
We have an admin called "Blitz"
"Blitz" is still a very commonly used word in the German language
Nukies have a common strat called "Blitz"ops
Doing something fast is still reffered to as "Blitzing"
The word is everywhere, and nobody has seemed to care

**Comment by deltanedas** [comment]
what were these issues

**Comment by JustAnOrng** [comment]
people who are making this a big deal out of this need to grow the fuck up. Jesus christ.

**Comment by therealDLondon** [comment]
Marking above comment as hidden for being non-constructive

**Comment by Radezolid** [comment]
The issues was a community member and contributor feeling uncomfortable having an AI called Blitz, people fought her over it and they felt wronged and thus left.
Honestly it was a cheap price to lose 1 name to keep someone comfortable, but people kinda attacked them over their opinion. So they left.
The contibutor was the one making the chem master beaker to pills PR for example.

**Comment by Kr8art** [comment]
> The issues was a community member and contributor feeling uncomfortable having an AI called Blitz, people fought her over it and they felt wronged and thus left.

Apparently it was actually an admin who went out of their way and renamed the AI to **'Blitzkrieg'** which is immature/ignorant at best, and an administrator should probably know better. 

That being said, I don't think there's anything inherently wrong with just the word **'Blitz'** or it being used as part of the AI name list. This is a staff/administration problem and not something that needs a PR. 


image
(Screenshot for reference)

**Comment by DisposableCrewmember42** [comment]
I agree, there is nothing wrong with the name "Blitz", but renaming it to "Blitzkrieg" should not be repeated.

**Comment by MilonPL** [comment]
Closing for reasons mentioned above.

**Pull request closed without merging**
