### PR TITLE
Fixing the Frontier diagonal walls issues

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

When I pulled Frontier's secret doors, Dvir took notice and said "Hey, we had changes, did you pull these" and pinged me in the discord!! My live reaction was "Oh fuck oh shit I missed something" and so, now, we should have:
- smoother wall things(?)
- Diagonal walls with proper states and better RSI cleanup
## Why / Balance

Because I made an oopsie while cherrypicking / doing stuff for the artstyle. Yippee.
## Technical details

YAML, Meta.jsons, some C# but it's mostly from Frontier and is up to their standard and not ours. Touches upstream files, all frontier comments. Yippee.
## Media

See new-frontiers-14/frontier-station-14/pull/1603 for frontier implementation. Should do the same things in effect. If it breaks, I will cry.
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by TadJohnson00** [comment]
from a direction standpoint what does this actually do

**Comment by ghost** [comment]
> from a direction standpoint what does this actually do

Does some funny technical shit to smooth walls and make windows / walls connect to eachother and not have seperation. To my knowledge. Also cleans up the meta.jsons. 
It'll more so impact Velcro than anyone, so I'd like a few people to have eyes on this (mostly milon, deltanedas,) and others that know C# better than me because this edits it heavily as a frontier port.
IconSmoothComponent seems to be a pretty good indicator of what this does other than the meta.json cleanup.

**Comment by TadJohnson00** [comment]
Okay, cleans up the joins or lack thereof between walls. Sounds cool to me

**Comment by dvir001** [comment]
Welp, someone should reopen this or open a new PR for this.

**Comment by MilonPL** [comment]
I'll pick it up.

**Pull request closed without merging**
