### PR TITLE
Off Duty Crew

### PR DESCRIPTION
**Pull request by DangerRevolution**
**Why/Balance**

This adds a new role for the sake of roleplay; you're *not* an 'assistant' to serve people., you're someone who's simply off-duty from their work and deciding to relax & chillax on the station, *not* doing work. When loadouts gets merged; this probably could have some varied options regarding "relaxed" variants of the uniforms or the sort.

This is going to be part of more "RP-focused" roles that will be coming soon :)

**Media**

- [X] This PR does not require an ingame showcase

**Changelog**

:cl: DangerRevolution
- add: Off-Duty Crew have now been authorised to relax on the station!

### CODE REVIEW

**Comment by AitorLogedo** [comment]
Assistants already fit the role, you dont need to "assist" you can do whatever you want and even rp out a differerent job or rp job.
This this is kinda just bloat :/

**Comment by DangerRevolution** [comment]
> Assistants already fit the role, you dont need to "assist" you can do whatever you want and even rp out a differerent job or rp job. This this is kinda just bloat :/

This provides an RP direction for people to take; and provides them more RP reasoning to be on the station than a miscellaneous "make your own" reasoning as there is right now.
e.g a new player joining isn't wandering aimlessly trying to figure out how they can "assist" people, they have an RP reason and a backstory to be there.
+ They have more of a story to RP rather than wander around with a "task", to get bored when no one trusts Assistants and so won't hire 'em.

Even though this isn't major bloat of any kind, it's another option on the role screen that is up to **mappers** to allow for, if Wizden allow for it in loadouts; this could get wrapped into loadouts too when available + this is just one role of a few that are going to be coming up soon.

**Comment by Timemaster99** [comment]
Of the roles you've PRed up until now, I believe this one should be reconsidered. I don't disagree with your philosophy at all; you want to provide direction with which someone can roleplay their civilian character.
This role, in particular, lacks that fundamental _direction_ since it's ambiguous and too similar to passenger in the roleplay it evokes. I cannot envision that a less dedicated roleplayer would know how to act out this role differently from passenger.
As for adding this role to maps, I would first consult with maptainers before getting these accepted (assuming you havent already, which I wouldn't know from this post). It is indeed "bloat" until there's a solid plan to add these to one or more maps, similar to PRing a sign texture for a room that no one has planned to make.

Otherwise, I enjoy your Tourist and Barber roles and I look forward to seeing your map including them

**Comment by DangerRevolution** [comment]
> This role, in particular, lacks that fundamental _direction_ since it's ambiguous and too similar to passenger in the roleplay it evokes.

Y'know I see this point ^

**Pull request closed without merging**
