### PR TITLE
Nerf borg AA

### PR DESCRIPTION
**Pull request by DebugOk**
## About the PR
Does what it says on the tin. Just removed stuff like heads and armory

## Why / Balance
Free AA

### CODE REVIEW

**Comment by AitorLogedo** [comment]
Borgs should have AA wtf, eventually they will have full control of doors and stuff, this is an odd change

**Comment by deltanedas** [comment]
for emergencies they can hack doors, they dony need total aa

**Comment by DebugOk** [comment]
> Borgs should have AA wtf, eventually they will have full control of doors and stuff, this is an odd change

Okay cool

**Comment by DangerRevolution** [comment]
thank you so much for removing order access too many +1 for this, i know it's merged but just wanted to comment it

**Pull request merged**
