### PR TITLE
Armour Rework (lyndo please cook)

### PR DESCRIPTION
**Pull request by TadJohnson00**
## About the PR
Adjusted armour values (touches delta, wiz, and nyano files) in anticipation of #1672 
## Why / Balance

See above
## Technical details

n/a
## Media

n/a
## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n/a
**Changelog**

:cl: TJohnson & Lyndomen
- tweak: up to lyndo to decide here (thx luv u)

### CODE REVIEW

**Comment by Lyndomen** [comment]
This is intended to go live with one or two other PRs, shock damage + blunt damage stamina rebuild + weapon rebalance 

https://github.com/DeltaV-Station/Delta-v/pull/1672


stun meta btfo

**Review by ghost — COMMENTED** [review]
Seems good, but you should rewrite some of the comments so the change is documented from like, 0.75 to 0.85 just as a reference of how it was before. Having everything just say "General armor rebalance" gives no future yaml people who want to change this any clue how it was and kinda forces them to look up the PR.

**Comment by TadJohnson00** [comment]
Added comments as requested

**Comment by ghost** [comment]
Keep cooking 👍

**Pull request closed without merging**
