### PR TITLE
Dual Boot Batches

### PR DESCRIPTION
**Pull request by Venrixia**
## About the PR

Adds two batch files to Simultaneously run runserver.bat and runclient.bat . Also includes tool versions.
## Why / Balance

Was spoiled by EE's launch batches , made us our own dual boot batches.
## Technical details

Opens runserver.bat in a CMD window set to stay open . Also does the same for runclient.bat . Performing both actions in one click instead of having to individually run both. 

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

## **Changelog**

Adds batch files to run server and client at once.

### CODE REVIEW

**Comment by Venrixia** [comment]
After back and forth discussion in discord. I've re-added the Tools dual-boot , as well as created batches for starting client & server in debug . Along with the associated dual-boot

**Comment by ghost** [comment]
Would this cause an issue if we merged it?

**Comment by TadJohnson00** [comment]
@deltanedas should this be PR'd upstream or is this okay to merge here?

**Comment by deltanedas** [comment]
im fine with this i wont use it either way :trollface:

**Comment by TadJohnson00** [comment]
can haz merge then?

**Review by TadJohnson00 — APPROVED** [review]

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
