### PR TITLE
fix secborg sprite

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
john shitcode inventing shitcode but then john hack walks in

**Changelog**
:cl: Big Orthagonal
- fix: Diagonal secborgs are not real and were never real.

### CODE REVIEW

**Review by MilonPL — APPROVED** [review]
LMAO

**Comment by HawkeyeBlade** [comment]
Wait no change it back!

**Comment by flowerfall-system** [comment]
change it back pls

**Comment by deltanedas** [comment]
no this is george orwell famous novel "1984"

**Comment by MilonPL** [comment]
did you know they never actually say "literally 1984" in george orwell's 1984?

**Pull request merged**
