### PR TITLE
Ifriit gets theirs power back

### PR DESCRIPTION
**Pull request by Adrian16199**
## About the PR

Brings back the power of ifriit.
## Why / Balance

People complained that ifriit weak, adjusted it to be as balanced as i can imagine/possible since i cant go 1,5 stacks of fire and more than 2 is just overkill on somethin like this.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by deltanedas** [comment]
should consider moths taking extra fire damage could get instacrit still

**Comment by Axionyxx** [comment]
This is still going to deal too much damage in some cases. Ifriits could get another power temporarily but pyro is just not happening with how deadly fire is right now

**Comment by Adrian16199** [comment]
> This is still going to deal too much damage in some cases. Ifriits could get another power temporarily but pyro is just not happening with how deadly fire is right now

Im fully willingfull to make it do only one stack but otherwise, fair.

**Comment by stellar-novas** [comment]
Could pyro be made to deal some burn directly to get the ideal 1.5 fire stacks?

**Comment by Adrian16199** [comment]
> Could pyro be made to deal some burn directly to get the ideal 1.5 fire stacks?

It depends really, the question is, is it ideal?
One stack on a moth is 28 damage
One stack on a human is 14.
What is ideal, less than 50 but not below 30?
Moths/dionas will be extremely countered just due to this being heat.

**Pull request closed without merging**
