### PR TITLE
HOP Resprite

### PR DESCRIPTION
**Pull request by Timemaster99**
## About the PR

HOP's uniform is rather outdated, as is evident by the SS13 forks which have replaced the one we currently have. This PR ports the uniform and coat from Paradise Station and adjusts some other HOP items to match. 
## Technical details

sprites

## Media

Screenshot 2024-07-23 20-49-10
Screenshot 2024-07-23 20-49-28
Screenshot 2024-07-23 20-50-17
Screenshot 2024-07-23 20-50-50
Screenshot 2024-07-23 20-51-07
Screenshot 2024-07-23 20-51-30
Screenshot 2024-07-23 20-51-49
Screenshot 2024-07-23 20-52-20
Screenshot 2024-07-23 20-53-46

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Head of Personnel has received new uniforms from their tailor.

### CODE REVIEW

**Comment by Timemaster99** [comment]
Test fail unrelated

**Comment by ps3moira** [comment]
Unless we're porting everything from paradise, the color pallets of this resprite doesn't fit the rest of the stations current art style that much.

**Comment by Timemaster99** [comment]
> Unless we're porting everything from paradise, the color pallets of this resprite doesn't fit the rest of the stations current art style that much.

I'm inclined to disagree. This seems to line up much better than very bright, unshaded default HOP suit
image
image
image

**Comment by ghost** [comment]
Here's my take on this resprite:
While I want to strive for Paradise as a vision - my one nitpick with bringing this here is the hat. I like the HoP's current hat and the hat that's part of this resprite clashes and it feels like its shape reinforces HoP's existence as second in command to Captain, which it isn't here, since HoP only has service accesses. I also suppose that Moira has a point, but you did state you were inclined to disagree, so

**Comment by Timemaster99** [comment]
> Here's my take on this resprite: While I want to strive for Paradise as a vision - my one nitpick with bringing this here is the hat. I like the HoP's current hat and the hat that's part of this resprite clashes and it feels like its shape reinforces HoP's existence as second in command to Captain, which it isn't here, since HoP only has service accesses. I also suppose that Moira has a point, but you did state you were inclined to disagree, so



https://github.com/user-attachments/assets/171d1bc4-5663-429f-8c36-c804f58d7df2

image

Thoughts?

**Comment by Timemaster99** [comment]
made it green to address Adei's concerns about second in command

**Comment by ghost** [comment]
> > Here's my take on this resprite: While I want to strive for Paradise as a vision - my one nitpick with bringing this here is the hat. I like the HoP's current hat and the hat that's part of this resprite clashes and it feels like its shape reinforces HoP's existence as second in command to Captain, which it isn't here, since HoP only has service accesses. I also suppose that Moira has a point, but you did state you were inclined to disagree, so
> 
> 2024-07-22.23-22-43.mp4
> 
> image
> 
> Thoughts?

I love this, keep it blue, I don't want green HoP. I am pleading.

**Comment by Timemaster99** [comment]
> > > Here's my take on this resprite: While I want to strive for Paradise as a vision - my one nitpick with bringing this here is the hat. I like the HoP's current hat and the hat that's part of this resprite clashes and it feels like its shape reinforces HoP's existence as second in command to Captain, which it isn't here, since HoP only has service accesses. I also suppose that Moira has a point, but you did state you were inclined to disagree, so
> > 
> > 
> > 2024-07-22.23-22-43.mp4
> > image
> > Thoughts?
> 
> I love this, keep it blue, I don't want green HoP. I am pleading.

I'm personally neither here nor there. I just want to make sure it's easy for new players to tell the difference. Lyndo is leading the discussion, so if a negative consensus is reached, I made sure that Green HOP is one simple revert away from turning blue again.

**Comment by Lyndomen** [comment]
There isn't a solid consensus either way, opinions seem pretty deadlocked.

**Comment by Timemaster99** [comment]
> There isn't a solid consensus either way, opinions seem pretty deadlocked.

I will settle on this: I will revert green hop in exchange for the quick merge of this, and then leave another green PR open for discussion

**Comment by Timemaster99** [comment]
> > > Here's my take on this resprite: While I want to strive for Paradise as a vision - my one nitpick with bringing this here is the hat. I like the HoP's current hat and the hat that's part of this resprite clashes and it feels like its shape reinforces HoP's existence as second in command to Captain, which it isn't here, since HoP only has service accesses. I also suppose that Moira has a point, but you did state you were inclined to disagree, so
> > 
> > 
> > 2024-07-22.23-22-43.mp4
> > image
> > Thoughts?
> 
> I love this, keep it blue, I don't want green HoP. I am pleading.

Ready if you want to merge

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
