### PR TITLE
blacklist nukedisk from slime storage

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

what it says on the tin

## Why / Balance

bug fix, you can't access storage when the target cryos so if the captain has the nuke disk there it will get sent to nullspace

## Breaking changes

**Changelog**

no cl because i can't come up with a good one

### CODE REVIEW

**Comment by deltanedas** [comment]
same applies to hypospray etc
it should just be listed like hands and inventory are

**Comment by MilonPL** [comment]
> same applies to hypospray etc it should just be listed like hands and inventory are

that's the ideal long term solution but probably upstream, this is a quick fix so that it's not literally gamebreaking

**Comment by deltanedas** [comment]
would also have to be done for rodentia storage i imagine

**Comment by MilonPL** [comment]
> would also have to be done for rodentia storage i imagine

you're right yeah i forgot that was a thing

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
