### PR TITLE
Emag for fugi

### PR DESCRIPTION
**Pull request by Stop-Signs**
## About the PR
added a kit to the fugi stash that contains a single emag and camera bug

## Why / Balance
Emag is cool, fugi kits are limited. more content yay!

fox asked for the camera bug and I think its a cool idea!

## Media
image

image

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: A new loadout is available in the fugitives stash

### CODE REVIEW

**Comment by therealDLondon** [comment]
I feel like this should come with other items too. Fugi kits should have several items, and make the fugi possibly have to hide their things.
Consider an emag plus... lets say... that new camera thing syndies get. And to sell the "funny computer hacker" bit, some gar glasses. No special effect, but some really gawdy horrible glasses

**Comment by Stop-Signs** [comment]
> I feel like this should come with other items too. Fugi kits should have several items, and make the fugi possibly have to hide their things. Consider an emag plus... lets say... that new camera thing syndies get. And to sell the "funny computer hacker" bit, some gar glasses. No special effect, but some really gawdy horrible glasses

to be honest i didnt want to give them any more because an emag is such a good item, I think the camera bug WOULD fit here though.

**Comment by Bonktrauma** [comment]
> > I feel like this should come with other items too. Fugi kits should have several items, and make the fugi possibly have to hide their things. Consider an emag plus... lets say... that new camera thing syndies get. And to sell the "funny computer hacker" bit, some gar glasses. No special effect, but some really gawdy horrible glasses
> 
> to be honest i didnt want to give them any more because an emag is such a good item, I think the camera bug WOULD fit here though.

I mean, is it really such a good item? It does not work for doors so all you can really do is enag vending machines and computer and lockers and such

**Comment by Avalon-Proto** [comment]
> I mean, is it really such a good item? It does not work for doors so all you can really do is enag vending machines and computer and lockers and such

With an Emag you can get
- Decent armor
- assorted useful goods
- Cybersun pen
- All access 
- fun outfits
- Emagged lathes for weapons
The Emag is one of the most useful items a syndie can buy

**Comment by Bonktrauma** [comment]
> > I mean, is it really such a good item? It does not work for doors so all you can really do is enag vending machines and computer and lockers and such
> 
> With an Emag you can get
> - Decent armor
> - assorted useful goods
> - Cybersun pen
> - All access 
> - fun outfits
> - Emagged lathes for weapons
> The Emag is one of the most useful items a syndie can buy

All of which is locked behind access, or most of it

**Comment by therealDLondon** [comment]
> > I mean, is it really such a good item? It does not work for doors so all you can really do is enag vending machines and computer and lockers and such
> 
> With an Emag you can get
> 
>     * Decent armor
> 
>     * assorted useful goods
> 
>     * Cybersun pen
> 
>     * All access
> 
>     * fun outfits
> 
>     * Emagged lathes for weapons
>       The Emag is one of the most useful items a syndie can buy

Weapons for a thief mean dumb-squat, they're pacified

**Comment by Avalon-Proto** [comment]
> Weapons for a thief mean dumb-squat, they're pacified

Fox. This is for fugitive. The guys wanted by galpol. Thieves already have a lot to get an Emag and a handful of other items

**Comment by Avalon-Proto** [comment]
> All of which is locked behind access, or most of it

Fugis spawn with insuls. Tools, and a few other assorted bits and bobs. They can break into most places easy enough

**Comment by deltanedas** [comment]
step 1 break into the bridge step 2 free AA

**Comment by Stop-Signs** [comment]
Just to make it clear the most recent commit added the camera bug to the kit. Furthermore, yes getting AA would be an option for fugi, but a risky one at that. fugitives do get tools but not a full set (missing wrench, crowbar, and welder i think). getting AA would be incredibly risky seeing as your entire goal is to lay low. Essentially high risk high reward, especially considering that AI exist now.

**Comment by Radezolid** [comment]
> fugitives do get tools but not a full set (missing wrench, crowbar, and welder i think)

They get a crowbar, wirecutters and a screwdriver.

**Review by Lyndomen — APPROVED** [review]
Direction approved, if a fugi gets AA, lament.

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
