### PR TITLE
Add a light to the paramedic's helmet + removal of paramedic suit storage from upstream files.

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
I moved the suit storage unit from upstream's file to ours while updating it to use entity tables and added a light to the paramedic's helmet

## Why / Balance
A Paramedic suit meant to be used in search and rescue would need a light to aid in it's duties.

## Technical details

Adding YAML and sprites.
Moved the paramedic's suit storage + made it use `EntityTableContainerFill`

## Media

image
image

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Nothing... yet.

**Changelog**

:cl:
- tweak: Paramedics void helmets now come with a flashlight attached for better search and rescue.

### CODE REVIEW

**Comment by Radezolid** [comment]
I need a hand with this one.
Sprite doesn't renderize when the light is off, but it does when it's on.
image
image

As far as I know i'm missing something and the "issue" comes from these lines:
```
  - type: Appearance
  - type: HandheldLight
    addPrefix: true
```

**Comment by Emily9031** [comment]
Honestly I have no idea why this works, but I renamed some of the sprites and it seems to have fixed the bald issue.

**Comment by Radezolid** [comment]
Sprites are shit, but we can change that later. I am not a good spriter.

**Review by Lyndomen — APPROVED** [review]
Great change, direction approved

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
