### PR TITLE
Bureaucratic error changes

### PR DESCRIPTION
**Pull request by Guess-My-Name**
## About the PR

reenables bureaucratic error event and changes it to a bit less chaos -- no more closing all jobs except a single unlimited one

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Some budget cuts were made in HR department, expect more bureaucratic errors in near future.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
I've never seen this event before so I'm curious how this plays out. Will be interesting to see!

**Comment by OCOtheOmega** [comment]
YAML Linter go brrrr

**Comment by Adrian16199** [comment]
10 captains on a shift, would be funny.

**Comment by ps3moira** [comment]
This event was pretty unfun, what's the difference to the version that got removed? Other than limiting to no jobs at all or unlimited jobs.

**Comment by DangerRevolution** [comment]
> This event was pretty unfun, what's the difference to the version that got removed? Other than limiting to no jobs at all or unlimited jobs.

Doesn't close all job slots. That's all..

**Comment by deltanedas** [comment]
ftr thats a rate event that only has 25% chance *at max modifier*, its much lower otherwise
forcing latejoins to all be clowns is funy

**Comment by Colin-Tel** [comment]
fixed the errors in this PR

**Review by Elijahrane — COMMENTED** [review]
Looks good to me

**Review by DebugOk — APPROVED** [review]

**Pull request merged**
