### PR TITLE
Senior ID cards get a custom job name: Attempt 2

### PR DESCRIPTION
**Pull request by WarMechanic**
## About the PR

So last time senior ID job titles tried to get implemented, it practically didn't work. I personally never saw senior IDs in effect, and they only applied to players at round-start without even influencing the crew manifest.
I'm not quite done yet, but right now my solution catches both roundstart and latejoining players. It also applies the correct ID icons, so security will finally see some fancy "M"s walking around. Senior ID job name and icon also display correctly in crew manifest now.

## Technical details

This solution reverts #1218 which relied on an event that was raised only after ready players spawned in at roundstart. Instead of a customJobName variable, we use job prototypes for senior roles and add logic before a player joins to use a 'virtualJob' based on your ID card. Senior ID cards now link to senior role prototypes instead of normal roles.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Not from what I've seen so far, although anything that relies on the redundant ID name change on spawn will have to be checked.

**Changelog**

:cl:
- fix: Fixed senior roles not displaying properly

### CODE REVIEW

**Comment by WarMechanic** [comment]
its in a working state now but the crew manifest ended up being bugged because senior job prototypes werent listed in their respective departments :blunt:

ill have to review the logic to cull anything thats not needed.

**Review by Axionyxx — CHANGES_REQUESTED** [review]
This is adding additional data that was the entire reason we avoided doing this in the first place. It should be investigated why the code was faulty and fixed, not removed and replaced by the one thing that was being avoided

**Comment by WarMechanic** [comment]
> This is adding additional data that was the entire reason we avoided doing this in the first place. It should be investigated why the code was faulty and fixed, not removed and replaced by the one thing that was being avoided

is it including unnecessary data in prototypes, or the fact that there are prototypes in the first place that you want to avoid? 

i added things like access to the senior job prototypes just as a formality although they will probably never be used so i can cull them if you want. i did initially try to parent the prototypes but that didn't work.

**Comment by WarMechanic** [comment]
also i originally attempted to work from your fix, but i determined that id have to put bandaids in multiple different scripts and stuff. i didnt think the solution would be very readable and would be more annoying to maintain by extension

here most of the code takes place in one script, and it uses job prototypes for compatibility.

**Comment by WarMechanic** [comment]
alright im going to assume the worst-case scenario in that you want me to remove the prototypes and replace them with components, ill start working on that now

**Comment by WarMechanic** [comment]
actually ill upload it as a separate PR in the case that this solution would be preferred

**Pull request closed without merging**
