### PR TITLE
Updates Micro station

### LINKED ISSUE #1986: micro has no RE machine
## Description
title

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Fixes #1986 

## Why / Balance

AI update!
## Technical details

N/A
## Media

Micro-0

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

N/A
**Changelog**

:cl:
- add: Added AI and reconfigured cameras on Micro station.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
image

**Comment by IamVelcroboy** [comment]
There's no traversal tube or suits to get to AI sat

**Comment by IamVelcroboy** [comment]
That's it, just add the router and go ahead and update proto for robo roll, then we merge

**Comment by IamVelcroboy** [comment]
Same here, add Ai to proto and ready for merge

**Comment by Colin-Tel** [comment]
> Same here, add Ai to proto and ready for merge

It's already in, sir.
image

**Comment by IamVelcroboy** [comment]
> > Same here, add Ai to proto and ready for merge
> 
> It's already in, sir. image

Doh... I was looking at "changes since you last viewed" 🤠

**Review by IamVelcroboy — APPROVED** [review]
Run that shit

**Pull request merged**
