### PR TITLE
Justice can into access Criminal Records Computer

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
added justice to criminal records computer access check thing

## Why / Balance
more mechanics and paperwork rp for justice

## Technical details
webedit ops

## Media
no please

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- tweak: Justice may now edit the Criminal Records Computer

### CODE REVIEW

**Comment by Unkn0wnGh0st333** [comment]
Make sure they can't change things on it, like wanted status

**Comment by Lyndomen** [comment]
> Make sure they can't change things on it, like wanted status

They can, intended. If they abuse it, arrest them. Otherwise these are roles bound to follow SOP and shouldn't abuse it. 

Also gives more mechanics to justice, by allowing them to work sec front desk

**Comment by Radezolid** [comment]
As a prosecutor this feels really nice. Main problem though is that the criminal records computer is usually behind sec doors which justice can't open. They might need to be moved for justice to access them.

**Comment by Lyndomen** [comment]
> As a prosecutor this feels really nice. Main problem though is that the criminal records computer is usually behind sec doors which justice can't open. They might need to be moved for justice to access them.

From what i remember most maps have one at the front desk, which all justice has access to

**Comment by Radezolid** [comment]
> > As a prosecutor this feels really nice. Main problem though is that the criminal records computer is usually behind sec doors which justice can't open. They might need to be moved for justice to access them.
> 
> From what i remember most maps have one at the front desk, which all justice has access to

The ones with accesible consoles are:

- The Hive.
- Lighthouse.
- Edge.
- Asterisk.

Maps without an accesible console are:
<details>
<summary>Tortuga</summary>

image

</details>
<details>
<summary>Glacier</summary>

image

</details>
<details>
<summary>Hammurabi</summary>

image

</details>
<details>
<summary>Shoko</summary>

image

</details>
<details>
<summary>Pebble</summary>

image

</details>
<details>
<summary>Micro</summary>

image

</details>

**Comment by Lyndomen** [comment]
I have been proven as a fake fan

**Review by MilonPL — APPROVED** [review]

**Comment by alterae** [comment]
> > > As a prosecutor this feels really nice. Main problem though is that the criminal records computer is usually behind sec doors which justice can't open. They might need to be moved for justice to access them.
> > 
> > 
> > From what i remember most maps have one at the front desk, which all justice has access to
> 
> The ones with accesible consoles are:
> 
> * The Hive.
> * Lighthouse.
> * Edge.
> * Asterisk.
> 
> Maps without an accesible console are:
> 
> Tortuga
> Glacier
> Hammurabi
> Shoko
> Pebble
> Micro

yeah as a frequent Prosecutor player access to the records computer is a must-have for doing my job. would greatly appreciate a fix

**Comment by IamVelcroboy** [comment]
Tortuga and Hammurabi are both accessible in the court room

**Comment by deltanedas** [comment]
having to leave sec to run all the way (halfway across the station on hammurabi!) to the court just to change someones status is bad

**Pull request merged**
