### PR TITLE
dont give AI a fugi report

### LINKED ISSUE #2361: Fugitive report spawns on the AIs face
## Description
When the galpol announcement comes in and the station gets the fugi report, one is spawned on the AI core, covering its pretty face

**Reproduction**
Have AI
Spawn fugi
Wait for announcement

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
title

## Why / Balance
fixes #2361 

## Technical details
same as the aghost gaming, just dont pick ai

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- fix: Fixed the AI getting a copy of fugitive reports on its face.

### CODE REVIEW

**Review by MilonPL — APPROVED** [review]

**Comment by Bonktrauma** [comment]
Why is ai even given one, they can't read

**Comment by Lyndomen** [comment]
> Why is ai even given one, they can't read

fax machine

**Comment by Avalon-Proto** [comment]
> > Why is ai even given one, they can't read
> 
> fax machine

We should give the AI a fax machine menu so it can shoot messages to departments in a more fun way.

**Comment by Bonktrauma** [comment]
> > > Why is ai even given one, they can't read
> > 
> > fax machine
> 
> We should give the AI a fax machine menu so it can shoot messages to departments in a more fun way. 

Good idea.

**Pull request merged**
