### PR TITLE
Increase round restart time for Peri and Horizon

### PR DESCRIPTION
**Pull request by makyo**
## About the PR

Increases `round_restart_time` (the time spent at CC) to five minutes for Horizon and Periapsis. 

## Why / Balance

Allows players to wrap up stories begun during shifts and relax for a little longer at the bar in CC. Having done so using `sudo cvar game.round_restart_time 300` as an experiment over the last few days under the guidance of Direction, the change was welcomed by the players. Currently, this only applies to Peri/Horizon with additional consideration required for Apo.

## Technical details

CVars change in config

## Media

n/a

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

n/a

**Changelog**

:cl:
- tweak: round restart time

### CODE REVIEW

**Comment by astralExpanse** [comment]
Honestly, I don't even think 5 minutes is enough, I genuinely believe that 10 minutes at Centcom would be perfectly adequate to get some final conclusive rp in after a shift, as well as some interpersonal character discussion.

Since this would only impact Peri and Horizon, I do see it as especially welcome as that's where most of our roleplay playerbase is located. Any increase is huge but 10 minutes would be frosting on the cake if this gets merged.

**Comment by Lyndomen** [comment]
Taking under direction review, 24 hours

**Comment by deltanedas** [comment]
is this not done already

**Comment by makyo** [comment]
> is this not done already

The cvar is set manually as part of testing to see what folks enjoy.

**Review by Lyndomen — APPROVED** [review]

**Pull request merged**
