### PR TITLE
Merge Master

### PR DESCRIPTION
**Pull request by Axionyxx**
## About the PR
Done with partial guidance from @DebugOk. I'm not sure if I did this properly or not

Skipped https://github.com/space-wizards/space-station-14/commit/75287db55545e0bd32425721e5d3751f2913de39 + any changes to map files

Skipped https://github.com/space-wizards/space-station-14/commit/9594afa400ff9dbcbc8f9589e91da53f48206f42

**Changelog**
:cl:
- add: Merged master, please report any bugs

### CODE REVIEW

**Comment by Axionyxx** [comment]
Oh damn, #1000

**Comment by DangerRevolution** [comment]
What date is this up to :?

**Comment by Axionyxx** [comment]
> What date is this up to :?

Today, as of writing the latest available commit in the Space Station 14 repository

**Comment by DangerRevolution** [comment]
> > What date is this up to :?
> 
> Today, as of writing the latest available commit in the Space Station 14 repository

Poggles :)

**Comment by Axionyxx** [comment]
I guess I'll redo this, then dos2unix a second time

**Pull request merged**
