### PR TITLE
Merge gridinv + some other skipped stuff

### PR DESCRIPTION
**Pull request by DebugOk**
How to piss off an entire community in 1 simple step.

Cant automerge anyways so I'll have to figure out a way to do this and *not* fuck up the repo horribly

### CODE REVIEW

**Comment by DebugOk** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

I would've never guessed, thanks

**Comment by deltanedas** [comment]
honestly in its more finished state its not too bad, besides changing every fucking item back :trollface:

**Comment by DEATHB4DEFEAT** [comment]
:shipit: 

image

**Comment by VMSolidus** [comment]
image

_internal screaming_
_external screaming_

**Comment by DebugOk** [comment]
Replaced by https://github.com/DeltaV-Station/Delta-v/pull/703

**Pull request closed without merging**
