### PR TITLE
carrypets

### PR DESCRIPTION
**Pull request by Froffy025**
## About the PR

adds carriable component to a lot of animals that didn't have it
## Why / Balance

grr
## Media

image

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

🆑 
- add: You can now carry most of the station pets.

### CODE REVIEW

**Comment by deltanedas** [comment]
why not put on base mob, i want to carry a fish too

also these all need deltav marker comments

**Comment by noctyrnal** [comment]
> why not put on base mob, i want to carry a fish too
> 
> also these all need deltav marker comments

something something dreaded fish ops

**Comment by DangerRevolution** [comment]
this needs Delta-V comments on every single instance of modified upstream code

**Comment by Froffy025** [comment]
added deltaV comments and the dreaded fishops. wasn't sure how to go about adding carriable to basemob and stopping players from holding very heavy mobs

**Review by Axionyxx — APPROVED** [review]

**Comment by Axionyxx** [comment]
@deltanedas Feel free to merge if you have nothing else to add

**Pull request merged**
