### PR TITLE
pr labeler ops pt 3

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

automatically adds "S: Awaiting Changes" if there's pending changes requested from an org member
should just work i havent actually tested

### CODE REVIEW

**Review by deltanedas — CHANGES_REQUESTED** [review]
requested changes

**Comment by MilonPL** [comment]
it wouldnt work on the pr itself because the actions are taken from the main repo no?

**Comment by MilonPL** [comment]
image

real???

**Review by deltanedas — CHANGES_REQUESTED** [review]
2

**Comment by MilonPL** [comment]
idk why it would fail because the regular add label works :blunt:

**Review by deltanedas — CHANGES_REQUESTED** [review]
revs

**Comment by MilonPL** [comment]
I'll just PR it from another branch instead of the fork and pray :godo:

**Pull request closed without merging**
