### PR TITLE
Remove Yule

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Removes X-Mas maps

## Why / Balance
Tis not the season

- [x] Arena

- [x] Asterisk

- [x] Edge

- [x] Hive

- [x] Pebble

- [x] Shoukou

- [x] Tortuga

**Changelog**
:cl: Velcroboy
- remove: Space winter is officially over!

### CODE REVIEW

**Comment by DebugOk** [comment]
Test failures are valid and also result in the renderer stopping with errors

**Comment by IamVelcroboy** [comment]
> Test failures are valid and also result in the renderer stopping with errors

tidied Tortuga

**Comment by IamVelcroboy** [comment]
Say what now `SpawnAndDeleteAllEntitiesInTheSameSpot`

**Comment by DebugOk** [comment]
I'll merge them now so they can do the funny rendering, but christmas will only be truly gone on the next publish

**Pull request merged**
