### PR TITLE
Delta-V Guidebook Rules

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

Updates the rules with the updates in #1485 and applies the guidebook rules format by pulling it from upstream. Rules rule!!1

## Why / Balance

Doesn't effect game balance, more of a QoL because our rules are fucking CHUNKY and DAUNTING. This gets them in a nicer to read format. 

**Changelog**

:cl: NullWanderer, Adeinitas, Colin_Tel, DLondon
- tweak: Updated the server rules and made them more readable in one go, check them out!!!

### CODE REVIEW

**Review by Axionyxx — DISMISSED** [review]
I trust myself for the code, Adei & the rest for the guidebooks and the tests for spotting any silly mistakes

**Review by Axionyxx — DISMISSED** [review]
Should be good now I hope

**Comment by ghost** [comment]
It is no longer good ( :tm: )

**Review by Axionyxx — APPROVED** [review]

**Comment by pissdemon** [comment]
This broke the rules page on the website: https://delta-v.org/rules.html 

I suggest just removing that page altogether from the website at this point unless someone feels like writing code to turn the Guidebook format rules into something web viewable.

**Pull request merged**
