### PR TITLE
Adds a helpful guide in book format on meeting vulpkanin

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
new salvage book

## Why / Balance
its a nice comfy book

## Technical details
yaml

## Media
image

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
no

### CODE REVIEW

**Comment by Lyndomen** [comment]
yaml maints speedmerge 🙏 trust

**Review by MilonPL — DISMISSED** [review]
based based based

**Comment by Lyndomen** [comment]
test fail was real but now fake, speed merge 🔥

**Review by MilonPL — APPROVED** [review]

**Review by deltanedas — APPROVED** [review]

**Comment by deltanedas** [comment]
pretty sure this cant spawn but yeah

**Comment by MilonPL** [comment]
admin only (staff-furry-rp real) :godo:

**Pull request merged**
