### PR TITLE
Remove Bondage Mail

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

We have very strict no-ERP rules.

We also have a mail set that is handcuffs, a muzzle, and a blindfold.

I don't think we need this mixed signalling.

:cl:
- remove: Removed suggestive mail.

### CODE REVIEW

**Comment by Colin-Tel** [comment]
I thought this was for taking someone into a room, restraining them to a chair and cutting off their ear like in Reservoir dogs. Now you're telling me it's actually for sexy things?

**Comment by rosieposieeee** [comment]
That's it. I'm removing the sexy nurse outfit mail too.

**Comment by IamVelcroboy** [comment]
> That's it. I'm removing the sexy nurse outfit mail too.

Halloween is ruined 😄😉

**Comment by DebugOk** [comment]
> That's it. I'm removing the sexy nurse outfit mail too.

The otherwise easily obtainable outfit? No

**Comment by Colin-Tel** [comment]
Being serious, though. I wholly disagree with this. The items are restraints. They're not inherently erotic.

**Comment by DebugOk** [comment]
So do I, closing this for now.

**Pull request closed without merging**
