### PR TITLE
disable nukeops test role check

### PR DESCRIPTION
**Pull request by deltanedas**
until it gets fixed for real

### CODE REVIEW

**Comment by Bonktrauma** [comment]
What's this for?

**Comment by deltanedas** [comment]
so tests dont fail on master

**Comment by DangerRevolution** [comment]
> What's this for?

To test a PR works, GitHub runs tests we tell it to, and one of the tests is failing because GitHub isn't eligible for the nuclear operative (I think, I haven't read the test fail) and so Delta is disabling that test so it stops failing

**Comment by deltanedas** [comment]
now that it actually validates that you are readied up, opted in and allowed to be an antag, the test fails because it doesnt opt in.

**Review by A-z-z-y — APPROVED** [review]
Looks good n' will help with CI.

**Pull request merged**
