### PR TITLE
Resprite + minor rebalance of security hardsuits

### PR DESCRIPTION
**Pull request by TadJohnson00**
It's been overdue a looong looong time, several months by my last count. But, here it is: security hardsuits are getting resprited, and thank god I don't have it hanging over my head any more.

## About the PR

Slightly tweak the balance of sec suits, replace the contents of lockers and suit storage, resprite all the sec hardsuits.
## Why / Balance

Resprites were necessary, rebalance is very light and slightly nerfs corpsmen + buffs warden at the cost of speed + buffs HoS a bit
## Technical details

N/A
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: TJohnson
- tweak: Security has received new models of hardsuit!

### CODE REVIEW

**Comment by TadJohnson00** [comment]
Anyways surely no errors right??? Right?????

**Comment by leonardo-dabepis** [comment]
the sprites all look good to me :)

**Comment by TadJohnson00** [comment]
Firstly, thanks Leo; secondly, fuck you too YAML linter.

**Review by Colin-Tel — DISMISSED** [review]
Looks good, TJ

**Review by Colin-Tel — APPROVED** [review]
Okay for real this time

**Pull request merged**
