### PR TITLE
Recolors the Sec Biosuit

### LINKED ISSUE #1601: security biosuit needs recolouring
## Description
there are vulp sprites so its not as easy as cherry pick and done

vox one is red the rest are blue (bluesec is not real)

### PR DESCRIPTION
**Pull request by Monotheonist**
## About the PR

Fixes #1601.
## Why / Balance

The biosuit should not change when a vox wears it. Something something "Bluesec Redsec."
## Technical details

Sprite changes mostly. Touches a lot of upstream files. Maybe I should've made an upstream PR?
## Media

Can't be assed to attach any, check files changed. It's all red. Oh god, it's all red.
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Will probably fuck the upstream merge if there's any changes to this biosuit sprite. Please just overwrite the main ones with the ones from upstream.
**Changelog**

No CL no fun, just color change.

### CODE REVIEW

**Comment by Monotheonist** [comment]
Build and Test Debug fail💀

**Comment by TadJohnson00** [comment]
Heya, you should probably just add the new sprites as DeltaV variants instead of touching the upstream sprites. If you can do that and adjust the sprite that the entities use that would be super cool plz & thx

**Review by TadJohnson00 — CHANGES_REQUESTED** [review]
Make a new RSI folder in Textures/DeltaV/ for these rather than overwriting upstream files.

(TJ L for duped comments)

**Comment by Monotheonist** [comment]
Fuck it, doing that.

**Comment by deltanedas** [comment]
you can just push to the same branch dont need to close it

**Pull request closed without merging**
