### PR TITLE
ERT Overhaul 2.0

### PR DESCRIPTION
**Pull request by Tryded**
Adds different ERT levels for different level of threats
Scales from (Smallest Threat to Largest):
Amber: Mostly when crew is extremely understaffed, small threats or a lot of people are dead. No Hardsuits except for Engineering ERT.
Red: For when something terrible has happened for example a traitor single handily killing the entire station's command and security or when nukies take WAY too long.
Gamma: When something catastrophic has happened on the station and you need brute force. For example, revs has taken over majority of the station, every traitor somehow worked together to kill the entire station or everything is burning down. (Spess dragon, your bootleg spess wizards, or way too much zombies.)

## About the PR

Admene QOL and ERT loadout changes. All ERT also has mindshields now.
## Why / Balance

ERT is currently extremely overpower (mainly their pulse weaponry) and that is one reason why admins don't want to use ERTs at all even if the station desperately needs it.
## Media

Reae

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by DebugOk** [comment]
Will not be merged until after we've declared the codebase stable and mostly complete

**Comment by Tryded** [comment]
What does conflicts mean

**Comment by Tryded** [comment]
> What does conflicts mean

Fixed

**Comment by DebugOk** [comment]
ERT was recently overhauled by wizden, theres too many merge conflicts right now to keep this open

**Comment by Tryded** [comment]
> ERT was recently overhauled by wizden, theres too many merge conflicts right now to keep this open

I was waiting for the codebase to be declared stable to continue working on this.

**Pull request closed without merging**
