### PR TITLE
Removes starvation damage from upstream species

### LINKED ISSUE #331: Starvation
## Description
Is it really worth keeping?

We never had it before, and it might be best to just get rid of it again

### PR DESCRIPTION
**Pull request by FluffiestFloof**
Fun fact, Vulpkanin never had any issue with starvation since they don't have starvationDamage :trollface: 

## About the PR

Removes the starvation damage.

## Why / Balance

While it's logical and realistic to literally starve, a lot of people seems to not like it.
I say skill issue, just eat but eh.

## Technical details

Comments out a couple things in basegame files.
closes #331 

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- remove: Removed starvation!

### CODE REVIEW

**Comment by Adrian16199** [comment]
It may be a skill issue, however I think the issue is the fact that the amount of ssd people can get so many and its hard to maintain all of em.

**Comment by Adrian16199** [comment]
also felinid not takin damage? They do tho, i did almost die to starvation and i only play as felinid.

**Comment by FluffiestFloof** [comment]
> also felinid not takin damage? They do tho, i did almost die to starvation and i only play as felinid.

oh ye right, they inherit from human so does harpy
Doesn't matter much for the goal of this PR

**Comment by DebugOk** [comment]
I love it

**Pull request merged**
