### PR TITLE
Trash and Puddles only spawn on main station grid

### LINKED ISSUE #1004: Still need a fix for filth spawning on cargo shuttle
## Description
Debug has a [WIP](https://github.com/DeltaV-Station/Delta-v/pull/954) PR up but, unfortunately, left. So, it didn't get finished.  

**Additional context**
Just hoping someone might pick this up again.

### PR DESCRIPTION
**Pull request by blueDev2**
## About the PR

Trash and Puddles only spawn on main station grid
Fixes #1004

## Technical details

Using the largest grid associated with the station, get all the tiles of said grid and randomly spawn puddles and trash on those tiles.

## Media

https://github.com/DeltaV-Station/Delta-v/assets/89804215/999d796d-cc7d-42ab-bf20-06fa16b99f6f

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: blueDev2
- tweak: Trash and Puddles only spawn on main station grid

### CODE REVIEW

**Comment by blueDev2** [comment]
Making an upstream PR, hopefully we'll find out why that test is failing.

**Comment by blueDev2** [comment]
Upstream wants a solution where the trash is more evenly spread instead of completely removing trash from the smaller grids

**Comment by OCOtheOmega** [comment]
You tested it? I try to merge it and get infinity map loading on variation generation. You sure its done?

**Comment by blueDev2** [comment]
I did test it and it seemed fine?
It did fail a test, but I was pretty sure that was due to a style issue.
In any case, the upstream PR has been radically changed so I will be closing this and suggest a cherry-pick if this needs urgent fixing

**Pull request closed without merging**
