### PR TITLE
Remove Vulpkanin overlay restrictions

### PR DESCRIPTION
**Pull request by TadJohnson00**
no longer must you choose two overly options only

## About the PR

removed pointless vulpkanin overlay restrictions
## Why / Balance

there are far more than two overlay options, no need for them to be restricted thusly
## Technical details

n/a
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Axionyxx** [comment]
What does overlay affect? How does this look in game?

**Comment by TadJohnson00** [comment]
Overlay is a type of marking you can put on your character.
This includes gauze wraps, eyepatches, point markings, etc.
Limiting it two severely restricts options and makes it hell to properly customise a character. Humans do not have a restriction on their overlay markings, for reference.

**Comment by TadJohnson00** [comment]
As for what this looks like in-game, there's no difference except that you can put more markings on your vulp characters, like a human (there is no "points left" on the customisation screen).

**Comment by TadJohnson00** [comment]
Anything I need to do prior to merge or is this all set to go?

**Review by Axionyxx — APPROVED** [review]

**Pull request merged**
