### PR TITLE
enable AI

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
should only be merged once all maps have prs open (they fail tests without this so cant merge them without trolling tests)

list to edit as prs are merged
- [X] Arena (#2138)
- [X] Asterisk (#2325)
- [X] Chibi (no)
- [X] Edge (#1987)
- [X] Glacier (#2058)
- [X] Hammurabi (#2311)
- [X] Lighthouse (#2017)
- [X] Micro (#2181)
- [X] Pebble (#2293)
- [X] Shoukou (#2284)
- [X] Tortuga (#2296)
- [X] TheHive (#2188)

## Changelog
:cl:
- add: Enabled AI for all stations except Chibi!

### CODE REVIEW

**Comment by JustTNE** [comment]
To my knowledge, it was said on discord that every station but `Chibi` would get AI, so it may be worth discussing if `Chibi` should be a requirement for this PR or not.

**Comment by Colin-Tel** [comment]
bumping with the opening of #2049

**Comment by MilonPL** [comment]
> bumping with the opening of #2049

Aren't you a maintainer? You can edit the issue and link it.

**Comment by Colin-Tel** [comment]
> Aren't you a maintainer? You can edit the issue and link it.

b-but this is a PR and not an issue >w<

**Comment by MilonPL** [comment]
> b-but this is a PR and not an issue >w<

image

**Comment by JustTNE** [comment]
Okay there's some things that might need clearing up with this PR to me.

Will cyborgs have their "answers to" round join message changed to the Station AI (as the station AI is now command) instead of the mystagogue? Seems like that's missing.

Although not necessarily required, I am curious what power the AI has over cyborgs. Does the AI get to define what "crew" is or will an antimov AI be at odds with its own cyborgs?

If the AI did get to define crew, we might see an antimov AI define itself as the only crew member and order the cyborgs to do things, but this would have the be clarified for cyborgs somewhere.

**Comment by deltanedas** [comment]
> Will cyborgs have their "answers to" round join message changed to the Station AI (as the station AI is now command) instead of the mystagogue? Seems like that's missing.

upstream hasnt added borg slaving yet

other issues would be fixed with borgs slaved to the ai having laws synced

**Comment by JustTNE** [comment]
I'm specifically referring to the text at the beginning of the round that states "as a cyborg you answer directly to the mystagogue. Special circumstances might change this". Other issue makes sense, thanks!

**Comment by JustTNE** [comment]
It would probably be good if we let the AI call the shuttle using its own internal communications console instead of forcing the AI to go to the bridge and call the shuttle from there.

There are some cases where the bridge is unpowered/the comms console destroyed, where I think it would make perfect sense for the AI to be able to call the shuttle on its own. The only considerations to be had for this in my mind are "what if the AI is antimov", but in my eyes we already have a rule against extending the round needlessly, and I honestly doubt we will see command un-anchoring the comms console so the AI can't recall the shuttle.
Swapping this to true does the trick:
https://github.com/DeltaV-Station/Delta-v/blob/5a7b1c158a643367543dd6d2836ec042b3e5994a/Resources/Prototypes/Entities/Mobs/Player/silicon.yml#L69

I don't know if this is something you would want to add to this pull request, or if you would like me to make a new pull request for this.

**Comment by Radezolid** [comment]
> It would probably be good if we let the AI call the shuttle using its own internal communications console instead of forcing the AI to go to the bridge and call the shuttle from there.

I think it's a good thing that the AI can't call the shuttle in their action menu, read [this comment](https://github.com/space-wizards/space-station-14/pull/31852#issuecomment-2346521799). If for some reason AI want's to evacuate due to it's laws forcing them to the only thing crew can do is go to the extreme and remove the ability of the AI to interact with the station, which is a overkill in my opinion. If you don't want the AI to recall you only need to snip the AI wire in the consoles.

**Pull request merged**
