### PR TITLE
remove deathgasp from the emote wheel

### LINKED ISSUE #1784: Deathgasp emote and feign death action shouldn't be available
## Description

Part of Delta-V's metagaming guidelines is that simulation of the death rattle (deathgasp) "or other game mechanics" is prohibited. As far as I'm aware, there's no reason we shouldn't hide the deathgasp emote from the emote radial and remove the fake death action from the MobDamageable entity.

**Reproduction**

1. Click the funny skull icon in the emote radial.
2. Be instantly boinked and unappealably banned for use of deathgasp.
<br>

1. Be crit and click feign death because funny.
2. Be instantly boinked and unappealably banned for use of "other game mechanics" to simulate a death rattle. (I assume this is what that clause is referring to.)

**Screenshots**

**Additional context**

I would like to PR a fix for this if possible, assuming I'm not incorrect in my reading of the rules.

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR

what it says on the tin
fixes https://github.com/DeltaV-Station/Delta-v/issues/1784

## Why / Balance

direction told me to

## Breaking changes

**Changelog**

:cl:
- remove: Removed deathgasp from the emote wheel.

### CODE REVIEW

**Review by TadJohnson00 — APPROVED** [review]
I approve :giga:

**Comment by Avalon-Proto** [comment]
Well guess I have to manually type it now after doing my bit of closing myself in a coffin or skipping into a bodybag

**Comment by dekigangsta** [comment]
change sux..

**Comment by deltanedas** [comment]
unlucky

**Pull request merged**
