### PR TITLE
Make survival the only gamemode ever

### PR DESCRIPTION
**Pull request by Lyndomen**
## About the PR
I wanna test out making survival the only gamemode, spawning in more sleepers, adding random nukie ghost roles, etc. one gamemode to rule them all. Ideally this has all the normal antags and shit just like, more spread out and less defined. Maybe you get a shift that spawns 3 nukies into revs idk

## Why / Balance
Roundstart zombies is nrp, nukies are barely better. 

## Technical details
Webedit but not real

## Media
No
## Requirements

- [x]I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
yes

**Changelog**
:cl:
- tweak: oops only survival

### CODE REVIEW

**Comment by therealDLondon** [comment]
Lyndo I love you but please dont make joke PRs

**Comment by Lyndomen** [comment]
It isn't a joke I want to add all the antags into survival

**Comment by deltanedas** [comment]
port dynamic from goob instead
also i dont think anyone would genuinely miss zombies gamemode anyway :trollface:

**Comment by Lyndomen** [comment]
why we closin drafts

**Comment by MilonPL** [comment]
> why we closin drafts

webedit :blunt:
(also maintainers can close any PR no matter if it's a draft or not if they do not like the idea proposed)

**Comment by Lyndomen** [comment]
Drafts don't even need a damn edit, that's dumb

**Comment by MilonPL** [comment]
Drafts exists so that you can propose an idea and see the initial reactions. If the maintainers do not like it, they can close it. I would suggest putting a lot more into the **Why / Balance** section when proposing something like this.

**Comment by Lyndomen** [comment]
> Drafts exists so that you can propose an idea and see the initial reactions. If the maintainers do not like it, they can close it. I would suggest putting a lot more into the **Why / Balance** section when proposing something like this.

Damn was hoping for some discussion here but I guess PRs aren't the place for it huh

**Comment by MilonPL** [comment]
> Damn was hoping for some discussion here but I guess PRs aren't the place for it huh

I would use the issues page instead.

**Comment by Lyndomen** [comment]
Ain't an issue, I want to work on something new. 


Issue: revs suck?
Ok that'll get closed

**Comment by MilonPL** [comment]
> Ain't an issue, I want to work on something new.

Issues can be used for discussing new content or proposing changes too, and generally are a way better way of doing that. See https://github.com/DeltaV-Station/Delta-v/issues/1882 for example.

**Comment by Lyndomen** [comment]
What are drafts for?

**Comment by Lyndomen** [comment]
Verbiage for issues sucks too then, might wanna see if we can change that cause that ain't gonna be intuitive for any human being not glued to this repo

**Comment by Lyndomen** [comment]
[
Screenshot_20241106-174204
](url)
Screenshot_20241106-174153
Yes this is good

**Comment by MilonPL** [comment]
> What are drafts for?

Draft PRs are meant to be a way to gather early technical feedback on a work-in-progress PR without signaling that the code is ready for a full review or merge. 
They don’t replace issues or discussions. When proposing a major change like this, it’s usually better to start with an issue to discuss the proposal with maintainers, as this gives everyone a chance to agree on the direction before any code is written.
Draft PRs are best used once there’s a clear, agreed-upon approach, allowing devs to share progress or invite feedback on specific implementation details, rather than the whole scope of the PR.

**Comment by Lyndomen** [comment]
I don't care what maints as maints have to say about the concept? This
isn't a technical issue, and the issues page doesn't indicate any of this
in the slightest. Sorry for discussing things on GitHub, I'll make sure to
use it as little as possible

**Comment by Lyndomen** [comment]
https://github.com/DeltaV-Station/Delta-v/pull/2076

Might wanna make an issue

**Comment by Lyndomen** [comment]
This is the straw that broke my back

**Comment by Unkn0wnGh0st333** [comment]
I find zombies can be actually fun if people roleplay better in intense scenarios. Most people just usually stop roleplaying once all hell breaks loose but even with that some of the best roleplay I've seen has come from zombies and nukies.

> *Couple crying and begging each other to survive over radio*

> *Stealth Op Centcom Nukies Round was also lit*

**Pull request closed without merging**
