### PR TITLE
Degenbrecher Station

### PR DESCRIPTION
**Pull request by noctyrnal**
## About the PR

Adds "Degenbrecher" Station, a Polar Atmospheric Station inspired by Glacier designed to accommodate mid-high pop player counts.

## Why / Balance

Stations are cool I think

## Media

Degenbrecher-0

## Requirements

- [ X ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added Degenbrecher Station.

### CODE REVIEW

**Comment by jimmy12or** [comment]
As a Botanist main, I would like to request that at least one large beaker be put next to the reagent grinder. Makes it much easier to use. 
Also, I know that the spacing it a little cramped and not every station has one, but if you were to add a chem master, you will make the day of many botanists.

**Comment by Timemaster99** [comment]
Vox box should be labeled with an N2 sign. Additionally, assuming you can set these values for the map, it would be better to give the vox box its own air alarm and scrubber. That way, you can avoid the strange two vent and filter setup by setting the scrubber to scrub oxygen.
I've seen submarine set air alarm settings in the past, but I'm not sure to what extent the mapping tools will allow it without breaking.

**Comment by IamVelcroboy** [comment]
This needs to be added in `Content.IntegrationTests/Tests/PostMapInitTest.cs`

**Comment by IamVelcroboy** [comment]
Why closed?

**Pull request closed without merging**
