### PR TITLE
(W.I.P) Lead, Lead Lined Crates, Lead Weaponry

### PR DESCRIPTION
**Pull request by Reene-Ramos**
## About the PR

Adds Lead Ore (Crabs), Lead Ingots, Lead Lined Crates, Lead Spears, and Lead Ammunition [This part is subject to change]

## Why / Balance

This adds a container that can be used to safely transport hazardous materials, such as Bananium.

## Technical details

New code adds: Lead spawning in asteroids
Not coded yet: Lead Ore Crabs, Lead Ore, Lead Ingots, Lead Crate

## Media
Will add media once I do the sprites.

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

P.S. Coding will be slow, as I have to actually find what I need to code in the files first

### CODE REVIEW

**Comment by Reene-Ramos** [comment]
Note to Self: remove the Basalt Lead spawner, and finally find the ore processor code

**Comment by Samsterious** [comment]
I question whether adding this much content is actually justified solely by one key item. I think it would be much more reasonable to write a PR adding a hazmat container that has to be ordered from Logi, like artifact containers.

**Comment by deltanedas** [comment]
artifact containers already block radiation

**Comment by Samsterious** [comment]
This is true, although the catch is that they can only hold one stack of items. A crate variant dedicated specifically to hazmat would serve a function distinct from that. Regardless, I think this PR lacks the mechanical substance to justify an entire new ore material.

**Comment by TadJohnson00** [comment]
Agreed. Besides, I don't think @Reene-Ramos is still working on this.

**Comment by TadJohnson00** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
