### PR TITLE
Breaching Charges

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

image

Adds Breaching Charges, basically as a resprite of the seismic charges salv gets, but for sec.

## Why / Balance

Had a recent round where, as a salv, my seismic charge got us into the bolted-closed vault to get at a loneop who had started the nuke. Made me think sec should have them too.

They have a one-tile explosion that is very effective at breaching walls, and not much else. They do 90 damage if you stand exactly in the center, but they really shouldn't be used for that. They're kind of a mix of the seismic and c4. They are available from the sectech vending machine.

I didn't really like just swapping the colors on the seismic or c4 so I sprited it myself.

https://github.com/DeltaV-Station/Delta-v/assets/52761126/487d5139-d613-43ff-b38f-082718ec9624

## Technical details

Had to modify the sectech fill so its a slight upstream change.

NOTE: I hereby release all changes made in this PR under MIT license.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Added breaching charges to the sectech for officers.

### CODE REVIEW

**Comment by Axionyxx** [comment]
Those are some beeg sprites ._.

**Comment by rosieposieeee** [comment]
> Those are some beeg sprites ._.

sorry lol. seismics are also pretty big. i mean, the rifles on the table next to it are huge anyway

**Comment by Axionyxx** [comment]
> > Those are some beeg sprites ._.
> 
> sorry lol. seismics are also pretty big. i mean, the rifles on the table next to it are huge anyway

Proportions in this game truly are wack

**Comment by rosieposieeee** [comment]
> > > Those are some beeg sprites ._.
> > 
> > 
> > sorry lol. seismics are also pretty big. i mean, the rifles on the table next to it are huge anyway
> 
> Proportions in this game truly are wack

stand next to a pair of gloves and weep

**Comment by IamVelcroboy** [comment]
Man, it would be really cool if we had directional explosions so you could set them to only blast in the direction of the wall.

**Comment by rosieposieeee** [comment]
> Man, it would be really cool if we had directional explosions so you could set them to only blast in the direction of the wall.

code changes :(

it would probably be useful for the low impact landmines too, which i cant set to just one tile without code changes. but ive never even looked at the explosion spread stuff...

**Comment by deltanedas** [comment]
pretty sure 1 tile explosion is just slope == intensity == max intensity

**Comment by rosieposieeee** [comment]
> pretty sure 1 tile explosion is just slope == intensity == max intensity

hmm. i wonder if that would be a better way to do it then. id give sec a couple more breaching charges if that was the case, since you might have to break a couple tiles, and it would be WAY harder for shitters to fuck around with em...

**Comment by rosieposieeee** [comment]
> pretty sure 1 tile explosion is just slope == intensity == max intensity

also, one of the issues with this, which i ran into with the low intensity landmines, is that it still breaks adjacent tiles, which is kind of frustrating

**Comment by rosieposieeee** [comment]
https://github.com/DeltaV-Station/Delta-v/assets/52761126/558917b5-8533-4002-a499-49f2cec26c9d

actually this fuckin rules and is really safe to stand next to, im good with this

**Comment by IamVelcroboy** [comment]
> actually this fuckin rules and is really safe to stand next to, im good with this

Yeah, this is good. I like this

**Comment by IamVelcroboy** [comment]
> > > > Those are some beeg sprites ._.
> > > 
> > > 
> > > sorry lol. seismics are also pretty big. i mean, the rifles on the table next to it are huge anyway
> > 
> > 
> > Proportions in this game truly are wack
> 
> stand next to a pair of gloves and weep

Or the teeny tiny hard hats 😄

**Review by deltanedas — APPROVED** [review]

**Comment by GrandKadoer** [comment]
Available in sectechs? Maybe mapped into the armory?

**Comment by deltanedas** [comment]
good things about being in sectech:
- dont need to map anything
- consistent across all maps, dont have a map with 8 but another with 6 etc
- less entities spawn roundstart
bad things:
- the sectech is never in armoury so breaching charges not being under wardens oversight is odd
- restocks having breaching charges might be weird

**Comment by rosieposieeee** [comment]
> good things about being in sectech:
> 
>     * dont need to map anything
> 
>     * consistent across all maps, dont have a map with 8 but another with 6 etc
> 
>     * less entities spawn roundstart
>       bad things:
> 
>     * the sectech is never in armoury so breaching charges not being under wardens oversight is odd
> 
>     * restocks having breaching charges might be weird

the charges, as they are now, are even less disruptive than the salv charges so i dont think it will be an issue even if sec ends up having tons of them. plus theres no other way to get more, so eh. i could just lower the number of em in the sectech if it becomes an issue

**Pull request merged**
