### PR TITLE
New salvage wreck "Solar Farm"

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
Adds new salvage map called "Solar Farm"
An incomplete solar satelite that has befallen a terrible fate

## Why / Balance
0/10, needs more ticks

## Technical details
creates DV-solar-farm.yml in /Maps/Salvage/DeltaV
edits the YML at /Prototypes/DeltaV/Maps/Salvage.yml

## Media
image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Fox
- add: New large salvage wreck "Solar Farm"

### CODE REVIEW

**Review by IamVelcroboy — APPROVED** [review]

**Comment by IamVelcroboy** [comment]
Apparently, you need to "sign" this commit. I have no idea what that means.

**Comment by therealDLondon** [comment]
I dont know what that means either

**Comment by DangerRevolution** [comment]
you need to sign your commits, to verify it's London making this PR and no one else. Not sure why it was turned on though.

**Comment by IamVelcroboy** [comment]
> you need to sign your commits, to verify it's London making this PR and no one else. Not sure why it was turned on though.

And how is that done?

**Comment by DangerRevolution** [comment]
> > you need to sign your commits, to verify it's London making this PR and no one else. Not sure why it was turned on though.
> 
> And how is that done?

Using WebEdit,
Asking Null to turn it off,
Downloading external programmes, messing around with encryption keys, to let you sign commits

**Pull request merged**
