### PR TITLE
2024/03/05 merge master

### PR DESCRIPTION
**Pull request by DebugOk**
Untested, unfinished. Theres other commits still up for grabs and the trading post still needs to be partially copied due to missing out on a lot of content because of it.

Most notably, the shuttle ui refactor is missing, due to trading post FTL changes. I may still take care of that, but ehh.

I also dont believe tests will pass, and thats fine. If they do, great, otherwise I'll fix them whenever I feel like it.

### CODE REVIEW

**Comment by DebugOk** [comment]
Yaml linter passed locally, thats the only test I ran

**Comment by deltanedas** [comment]
i thought deltav still uses brig access for lawyers

**Comment by IamVelcroboy** [comment]
> i thought deltav still uses brig access for lawyers

No. we have a Lawyer access for that.

**Comment by DebugOk** [comment]
All tests are now green locally
image

**Pull request merged**
