### PR TITLE
mothic salad recipe fix 

### LINKED ISSUE #1739: mothic salad gives free bowl
## Description
mothic salad recipe (cabbage tomato and slice of red onion) doesnt need a bowl but it's considered bowl food and will create free bowls out of thin air if you eat it

**Reproduction**
1. acquire ingredients
2. toss cabbage, tomato, and sliced red onion without a bowl until evenly mixed
3. serve
4. it makes a bowl when you eat it

**Screenshots**
ehh i am in a lot of pain right now

**Additional context**
not latest build its on a fork server but i dont think mothic salads have changed in the past 3 days

### PR DESCRIPTION
**Pull request by MilonPL**
## About the PR
fixes https://github.com/DeltaV-Station/Delta-v/issues/1739

## Technical details

yaml

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed the mothic salad recipe giving you a free bowl.

### CODE REVIEW

**Comment by portfiend** [comment]
see but the thing is there are recipes that use the mothic salad that require bowls so now you're consuming more bowls per recipe (?) i think i havent tested it

edit: fleet, cotton, kachumbari salads use bowls, and sweet chili cabbage wrap does not

**Comment by MilonPL** [comment]
> see but the thing is there are recipes that use the mothic salad that require bowls so now you're consuming more bowls per recipe (?) i think i havent tested it
> 
> edit: fleet, cotton, kachumbari salads use bowls, and sweet chili cabbage wrap does not

dumb if true
it's like a soup that requires another soup to make

**Comment by deltanedas** [comment]
the actual issue is mothic salad recipe not using a bowl

**Comment by MilonPL** [comment]
> the actual issue is mothic salad recipe not using a bowl

yeah so it changes so that mothic salad requires a bowl and the stuff that required the mothic salad no longer need an extra bowl
plz merge

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
