### PR TITLE
Added Agent ID and backpack to the Listening Post Operatives.

### PR DESCRIPTION
**Pull request by Radezolid**
## About the PR
Added an agent ID and a backpack to the LPOs.

## Why / Balance

I've seen several heads just state that without their signature no matter if their stamp is on it, it's fake. This allows LPO to counter that.
Backpack is merely a QoL.
## Technical details

Modified a the `misc_startingear` for the LPO and added an AgentIDCard in `pocket1` and a `ClothingBackpackSyndicate` on the `back` slot.

## Media

image

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added an Agent ID to LPO for them to fake signatures, plus a backpack to store all those illegal documents!.

### CODE REVIEW

**Comment by sheepism1** [comment]
Hello! I'm running #2003 and just have a few suggestions!



If the LP PDA is different, maybe add the Agent ID to the Syndi PDA?
Backpack is fun.

Merge conflict alert if you wanna do stuff to the LP map itself or the Intercept headsets.

**Comment by sheepism1** [comment]
I have an idea here.

**Comment by Radezolid** [comment]
> If the LP PDA is different, maybe add the Agent ID to the Syndi PDA? Backpack is fun.

The LPO PDA is different. If I add it to the Syndicate PDA then the nukies would get free Agent IDs, same with the syndicate refugees.

> Merge conflict alert if you wanna do stuff to the LP map itself or the Intercept headsets.

I know, and this doesn't touch neither, it only modifies the starting gear of the LPO.

**Comment by sheepism1** [comment]
> The LPO PDA is different. If I add it to the Syndicate PDA then the nukies would get free Agent IDs, same with the syndicate refugees.
I THINK we're on the same page here, we should add it to the LPO PDA only so nukes dont get it for free

**Comment by Radezolid** [comment]
It makes more sense that the PDA comes with the syndicate ID, put the agent ID in their pocket for them to notice it and it's in their starting gear to avoid people raiding the LPO for free loot.

**Comment by sheepism1** [comment]
aight, thanks

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
