### PR TITLE
Resprites EE corpse dragging sprites.

### PR DESCRIPTION
**Pull request by dotCatshark**
## About the PR

As title. This exchanges the current EE blood trail sprites produced when you drag a dead/crit person with some slightly modified sprites pulled from Ratwood, a roguetown fork, some that I made based on old sprites from roguetown, and one from classic goonstation. Thank you to whoever made these sprites, though your name is lost to time.

## Why / Balance

I think the current one look like one of those really low quality photoshop/krita/clip studio brushes that have a ton of overlap. Me no like. And this looks way gorier.

## Technical details

Exchanged dragging-1.png through dragging-5.png with a different version, using the same filenames to avoid having to recode anything whatsoever.

## Media

image

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Resprited EE sprites for corpse dragging.

### CODE REVIEW

**Comment by IAmNotGray** [comment]
Saw this stuff on the Discord. I approve.

**Review by deltanedas — CHANGES_REQUESTED** [review]
update the meta.json

**Comment by dotCatshark** [comment]
> update the meta.json

Done.

**Comment by deltanedas** [comment]
changelog should be a single `- tweak` change saying the body dragging sprites were resprited
meta.json cover where it was taken from that doesnt need to be in cl, if there are multiple authors for the pr you can do `:cl: a, b, c, d` to list them

**Comment by dotCatshark** [comment]
> meta.json cover where it was taken from that doesnt need to be in cl, if there are multiple authors for the pr you can do `:cl: a, b, c, d` to list them

Could you please rewrite or otherwise clarify this sentence, I am having difficulty understanding what you're saying.

**Comment by deltanedas** [comment]
its fine now just add `:cl:` and change `Tweak` to `- tweak`

**Comment by dotCatshark** [comment]
I understood it. Done now.

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
