### PR TITLE
Add history tab to bounty console

### PR DESCRIPTION
**Pull request by BarryNorfolk**
## About the PR
Added a history tab to the cargo bounty console.
DeltaV port of https://github.com/space-wizards/space-station-14/pull/33932. Just cherry picked the changes across and added an extra commit for adding DeltaV comments literally everywhere.

## Why / Balance
Knowing whether or not any bounties have been completed and when is important for people in charge of logistics, or command for that matter. It's also important to know who skipped what bounties so people can either teach which ones to not skip, or nod sagely at their good skip choices.

## Technical details
New to the codebase and C# in general, but seemed somewhat straightforward to add. 

## Media
396848148-8bf389a5-3320-48b7-8739-498aef40b6d9

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

:cl:
- add: Added a history tab to the bounty computer, showing all past completed and skipped orders (and who skipped them).

### CODE REVIEW

**Comment by deltanedas** [comment]
remove the deltav comments as it will just make merging upstream more annoying instead of just being skipped

**Comment by BarryNorfolk** [comment]
> remove the deltav comments as it will just make merging upstream more annoying instead of just being skipped

You want me to keep the files in DeltaV places or just remove the comments.

**Comment by deltanedas** [comment]
just use the upstream commits as-is dont have comments or file changes (then thered be duplicate files when merging master, also bad)

**Comment by BarryNorfolk** [comment]
Done.

**Review by deltanedas — APPROVED** [review]

**Pull request merged**
