### PR TITLE
Add mercenary outfit to clothesmate

### PR DESCRIPTION
**Pull request by Kr8art**
## About the PR
Adds parts of the mercenary outfit (bandana, beret, jumpsuit, fingerless gloves) to the Clothesmate.

## Why / Balance
Someone was asking for this, but I also think this is a good idea to add some more variety for appearances. Namely, this would allow passengers to roleplay as mercenaries or other military personnel like colonial marines who are off-duty or on their way to their next deployment.

## Technical details
- Added two of each Mercenary bandana, beret, jumpsuit and fingerless gloves in the DeltaV section of the Clothesmate

## Media
image

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
n/a

**Changelog**
:cl:
- add: Mercenaries and marines can now find a fitting outfit in the Clothesmate!

### CODE REVIEW

**Review by deltanedas — DISMISSED** [review]
lgtm cc @therealDLondon

**Comment by therealDLondon** [comment]
> lgtm cc @therealDLondon

Yeah no issues from me, I love the merc outfits. Cant wait for sec to batong the passenger for wearing it :trollface:

**Comment by therealDLondon** [comment]
Took me 17 minutes to remember I have merge perms

**Comment by therealDLondon** [comment]
Took me 20 seconds to realise I cant bypass the epic shader troll

**Comment by Unkn0wnGh0st333** [comment]
Wouldn't it be better if it was in the costume vendor and not the clothing vendor?

**Comment by Kr8art** [comment]
> Wouldn't it be better if it was in the costume vendor and not the clothing vendor?

Honestly not sure, but to be honest I don't think it matters a great deal.

**Comment by Unkn0wnGh0st333** [comment]
> Honestly not sure, but to be honest I don't think it matters a great deal.

Any other outfit that isn't general clothing/jumpsuits is usually put into the costume vendor. Plus most people who will be using this will mostly be using it as a costume I wouldn't doubt.

**Comment by Kr8art** [comment]
> > Honestly not sure, but to be honest I don't think it matters a great deal.
> 
> Any other outfit that isn't general clothing/jumpsuits is usually put into the costume vendor. Plus most people who will be using this will mostly be using it as a costume I wouldn't doubt.

Can't really say if people are more likely to use it as a costume than a legitimate military outfit, but based on the current inventory the ClothesMate seems like a better fit.

ClothesMate has:
- [X] Bandanas
- [X] Gloves
- [X] Jumpsuits
- [x] Berets 

AutoDrobe has:
- [ ] Bandanas
- [ ] Gloves
- [ ] Jumpsuits
- [X] Berets

**Comment by Kr8art** [comment]
Merge Branch Merge Branch Merge Branch Merge Branch (I don't know why this is still failing when it's just 4 lines of yaml but it's driving me crazy).

**Comment by Radezolid** [comment]
Fail says that with your change now a cloth vend restock gives more money than it's worth

**Comment by Kr8art** [comment]
You know that makes a lot of sense, actually. Though I kinda hate to increase the price of the restock even more given it's already 3500$ for something that doesn't have that many benefits. But I guess Cargo shouldn't have a source of free money, so I'll look into changing it.

**Comment by Radezolid** [comment]
It's by 20 spesos, make it cost 50 more and you're good

**Comment by Kr8art** [comment]
Raised the price by 50$ so it should hopefully pass now. Thanks.

**Review by MilonPL — APPROVED** [review]

**Pull request merged**
