### PR TITLE
upstream merge

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
from july 1 to today
meteor stuff excluded

## Technical details
- updated WhitelistRequirement to be less bad
- moved signature system to shared and predict everything
- remove some legacy nyano shit that nothing uses
- ahelp snitching hopefully disabled

**Changelog**
:cl:
- add: Merged last months changes from upstream, report any issues!
- add: SCREEEEEEEEEEE!!
- tweak: Signing paper is now predicted.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Does this include the new map editor? If so, I have concerns. I absolutely want it but I think we should hold off until it's been thoroughly tested upstream and bugs worked out. [Here](https://github.com/space-wizards/space-station-14/issues/30723)

**Comment by deltanedas** [comment]
> Does this include the new map editor?

yes but its pretty much disabled right now, it still uses actions not the fancy thing that doesnt work

**Comment by deltanedas** [comment]
i have horrifically fucked up the cherrypicking :trollface:

**Comment by IamVelcroboy** [comment]
🙈

**Pull request closed without merging**
