### PR TITLE
Fix Ifriit ghost role showing up as unknown

### PR DESCRIPTION
**Pull request by Adrian16199**
## About the PR

Fixes the hijacked #289 
## Why / Balance

Aparently, ghosting from an ifriit, caused the ghost role to become "unknown", this fixes it.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Adrian16199** [comment]
Zrzut ekranu 2023-05-18 190842
What (why did it fail the test debug)

**Comment by Guess-My-Name** [comment]
Maybe it's the quotation marks that make something not right?
Also, you forgot to add rules, just copy paste lines 11,12,13 from [>here<](https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/Nyanotrasen/Entities/Markers/Spawners/ghost_roles.yml#L11).

**Comment by Adrian16199** [comment]
Would be an odd error due to the:
image
since laika has this.

**Comment by Adrian16199** [comment]
Nevermind, null redid the checks and its aparently fine now, yey.

**Pull request merged**
