### PR TITLE
upstream merge 27/8

### PR DESCRIPTION
**Pull request by deltanedas**
## Notable inclusions
- salvage rework, 1 ore = 1 sheet, should be doable now that junk spawns which can be recycled
- random debris can be picked in salvage magnet
- blueprints, doesnt affect cargo fulton meta yet though :trollface:
- cleaned up guidebooks, including trade station guide which is now actually shown, and the survival guide now tells you how to use a spacepen properly instead of just having the sprite there and nothing else
- some other stuff i forgor

**Changelog**
:cl:
- add: Merged last weeks changes from upstream, report any bugs.
- tweak: Cleaned up a lot of guidebooks.

### CODE REVIEW

**Comment by Avalon-Proto** [comment]
So I got a question about the ore changes, does this mean that salvage will now need to get 1 Full stack of ore for 1 single stack of mats? And what does this do to the industrial ore processor?

**Comment by deltanedas** [comment]
yes, and it becomes like 1 ore for 1.15 sheets or so

**Comment by Avalon-Proto** [comment]
So, I know this PR is closed now, but there have been complaints about the ore changes. So. Maybe to make them less extreme we could do something like this

Common ores (Iron, coal, etc) 1 ore= 3 sheets

Uncommon Ore (Bananium, silver) 1 ore = 2 sheets

Rare Ore (Gold. Uranium, Diamond) 1 ore = 1.5 sheets

And so salvage can recycle/refine the junk they find more easily, maybe consider adjusting most salvage docks to have easy access to a logi/Salvage only recycler, so all the materials are not stolen away by tiders camping disposals

**Comment by IamVelcroboy** [comment]
> And so salvage can recycle/refine the junk they find more easily, maybe consider adjusting most salvage docks to have easy access to a logi/Salvage only recycler, so all the materials are not stolen away by tiders camping disposals

Mapping recyclers in salv is probably necessary for this. I'll have to take a look tonight

**Pull request merged**
