### PR TITLE
listening post rewrite

### LINKED ISSUE #1275: Listening post causes Traitorloose
## Description

Alternative title is _"Antag Refactor broke the LP."_
Probably related to the Antagonist Refactor, and is liable to be like this or similar until a PR is merged with a fix to this - spawning in as a Listening Post operator does a few things now;
- You get objectives that would be on station, as a Listening Post Operative. Furthermore, when you spawn in as a Listening Post op, it activates the Traitor Game Rule, turning any round where LP is spawned into Traitor, even if it's survival.
- Listening Post Operatives get a 20 TC uplink, due to this, and this has a whole range of items including reinforcements, which also add the Traitor gamerule.

**Reproduction**

- Open up development environment
- Startround, do addgamerule PirateRadioSpawn
- Join as Listening Post Operator (LPO)
- Check character menu, actual objectives like a syndicate agent.
- Open uplink, 20 TC.
- Do endgamerule, Traitor is now a gamerule even if it was a Zombies, Nukeops, or Survival / Extended round. Not sure what this entails, but the game might start rolling traitors.

**Screenshots**

I have a video of this in action but it's too big for github - will edit this when it uploads.

**Additional context**

Largely these are unintended, regarding the way LP is set up and its ghost role rules. The source of this may have been fixed upstream, also, so it's worth it to wait until an upstream merge before trying to fix this. If it persists then this becomes valid.
This also locks in with #1258 and #1235 because they're all issues nested in the same thing, the Antag Refactor.

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- rewrite everything about listening post
- the rule uses AntagSelection
- AutoTraitor removed, they are no longer tators they have their own role now
  fixes #1275
- any internals calling it "pirate radio" have been renamed, including the map file's path

in the future they can have funny objectives that make sense for the role and not things like steal the caps laser which would break the ghost roles rules of not revealing yourself

## Why / Balance
listening post having tc is bad, and telegnome ops having infinite tc is really bad

## Technical details
- loading a grid far away is now LoadFarGridRule
- debris spawning is now DebrisSpawnerRule
- the old pirate radio spawn rule go poof as a result

## Media
roles are real

no uplink no fun

greentext or redtext???

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
everything listening post related

**Changelog**
:cl:
- fix: Fixed listening post ops having TC and being counted as traitors.

### CODE REVIEW

**Comment by DangerRevolution** [comment]
o7

**Comment by Lyndomen** [comment]
Is having TC bad? We generally saw some cool strats, with the LP sending a reinforcement wave at the station in bootleg attacks.

**Comment by pissdemon** [comment]
Yeah, I don't think it's bad in and of itself. It's great for defense too. My last LP round, Sec metagamed our existence and conducted a raid, and I bought a Syndicate bomb which ended up killing three of the raiders. And the ability to buy reinforcements allows more flexibility when assisting on-board Syndicate. Fake traders, sending fake GALPOL to help a fugitive escape, etc.

**Comment by Bonktrauma** [comment]
> Is having TC bad? We generally saw some cool strats, with the LP sending a reinforcement wave at the station in bootleg attacks.

Honestly, I'd agree, however the TC duplication does need fixed

**Review by Axionyxx — APPROVED** [review]

**Comment by deltanedas** [comment]
LPs rules explicitly say to keep the LP a secret, sending reinforcements to raid the station is the opposite of that. if they need more guns for self defence just give them more

**Comment by WarMechanic** [comment]
well i mean if you don't see any ties to the LP on the reinforcements then you shouldn't know it exists so it seems fine in my book

**Pull request merged**
