### PR TITLE
Edge Fixes + Minor Updates

### PR DESCRIPTION
**Pull request by therealDLondon**
## About the PR
- Adds the lavaland express (Salv shuttle)
- Adds prison guard
- Solves the containment field issue
- Gives medbay a new coat of paint
- Makes medbay even more SOP compliant
- Adds external ordering computer to Logi
- Minor power fixes
- Reduces Secutiy Officer and Research Assistant slots by 1 each

## Why / Balance
Usual map maintainance

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
No, not this time

### CODE REVIEW

**Comment by MilonPL** [comment]
you should run the tidy map script on it too in case you havent already

**Comment by therealDLondon** [comment]
> you should run the tidy map script on it too in case you havent already

AFAIK I did

**Comment by IamVelcroboy** [comment]
> > you should run the tidy map script on it too in case you havent already
> 
> AFAIK I did

It's a very specific cmd using a python script found in the tools folder. You should probably know how to use it longterm, if you don't already. But short term, I'll probably just run every map after these lavaland PRs go through

**Review by Colin-Tel — CHANGES_REQUESTED** [review]
image
You're missing the mining shuttle console and the dock you used is the wrong one, you need the [Mining, Filled, Locked], not the other one.

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
