### PR TITLE
edgemos rework

### PR DESCRIPTION
**Pull request by Carolyn3114**
## About the PR
changes the horrid, cramped atmos room on edge with a shiny new atmos that has more space and much more versatility.

## Why / Balance
edge atmos was kinda stinky 

## Media
image

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by DebugOk** [comment]
I assume you asked the maintainer before making any changes?

**Comment by Carolyn3114** [comment]
> I assume you asked the maintainer before making any changes?

he said it was fine, and also said it looked good

**Review by DebugOk — DISMISSED** [review]

**Comment by Colin-Tel** [comment]
Looks good to me!

Except for how I *fucked* up by reverting that commit...

**Review by Colin-Tel — APPROVED** [review]
👍

**Pull request merged**
