### PR TITLE
[Feat] Security dogs now have vulpkanin vocal emotes

### PR DESCRIPTION
**Pull request by Remuchi**
## About the PR

I've added vulpkanin emotes for doggos. Now they can bark, howl etc.
Reorganized inventory template so the UI is not longer a buggy mess and all slots are now displayed correctly.

## Why / Balance

Emotes and UI are pure cosmetic changes.

With ID slot comes some questions - I've seen that it was previously deleted. 
I, personally, think that secdogs - especially Laika - should have the ID slot, but it should be empty at the start. So if the security wants they can make an ID for Laika. She can't open doors as Shiva can, so having ID card can help with it.
Without ID card Laika just stuck at bumping security doors until someone from security opens it for her.

## Media

New UI:
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Security dogs (such as Laika) now have vulpkanin vocal emotes. Howl!

### CODE REVIEW

**Comment by Bonktrauma** [comment]
Security dogs have received an ID slot before, and it was removed

**Comment by Bonktrauma** [comment]
> Security dogs have received an ID slot before, and it was removed

I'm like, 90% sure of this

**Comment by Bonktrauma** [comment]
https://github.com/DeltaV-Station/Delta-v/pull/882

**Comment by deltanedas** [comment]
emotes should be separate pr since that seems drama free, dont think anyone will object to it

**Comment by Remuchi** [comment]
I can always just revert the ID slot commit, no problems

**Comment by DangerRevolution** [comment]
Laika ID should be separate PR because it's more controversial than emotes

**Comment by therealDLondon** [comment]
Laika and the sec dogs lost the ID slot for a reason, and they shouldnt be added back without an admin discussion

**Review by Axionyxx — CHANGES_REQUESTED** [review]
Like London said, ID cards aren't allowed to be added back in right now. The emote changes are fine tho

**Comment by Remuchi** [comment]
I suggest then to discuss bringing back sechud glasses for her too. Since all security starts with them again, and it was the reason to remove them from Laika iirc

**Review by Axionyxx — APPROVED** [review]

**Comment by deltanedas** [comment]
@barks bind players keep winning

**Comment by WarMechanic** [comment]
Awesome!

**Pull request merged**
