### PR TITLE
Food cart storage buff

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Buffs storage from 30->100(20 burgers), and whitelists food items.

## Why / Balance
Many complained it was too small

## Technical details
n/a

## Media
n/a

## Breaking changes
Goofy lil error that pops up message that "items don't go in there," when they do.

**Changelog**
:cl: Velcroboy
- tweak: Buffed Food Cart storage. Get out there and slang some burgers, chefs!

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
Putting a pause on merging this. There's an upstream PR I made that is effectively replicating this. This will still be needed because of different storage system though.

**Comment by Colin-Tel** [comment]
Is this able to be merged now that we've merged upstream?

**Comment by IamVelcroboy** [comment]
I'll take a look tomorrow

**Comment by IamVelcroboy** [comment]
Ok, good to go

**Pull request merged**
