### PR TITLE
Salvage loses their shuttle

### PR DESCRIPTION
**Pull request by DebugOk**
I've had it with powergaming salvage, last round was the final straw. If they cant behave, I wont even bother trying to nerf their shuttle because I know they'll find ways around it.

Shipyards wyci.

:cl:
- remove: The salvage shuttle has been completely removed
- tweak: Salvage specialists now start with a mini jetpack in their locker

### CODE REVIEW

**Comment by Adrian16199** [comment]
Just like the nyano fathers intended.

**Comment by DebugOk** [comment]
And absolutely no arguing to be had, this is going out right now and being pushed the second the tests pass

**Comment by rosieposieeee** [comment]
hero.

**Comment by VMSolidus** [comment]
Based

**Comment by Astrumify** [comment]
Finally we can get prime salvage back, amazing change.

**Pull request merged**
