### PR TITLE
Nyano port of digging

### LINKED ISSUE #386: Subfloor/digging ported from Nyano
https://github.com/Nyanotrasen/Nyanotrasen/pull/998

and possibly this
https://github.com/Nyanotrasen/Nyanotrasen/pull/1332

### PR DESCRIPTION
**Pull request by Ygg01**
## About the PR
Ports Nyano digging.

## Why / Balance
Was asked to do it.

## Media
Digging a dirt tile to bedrock.

Digging Preview

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Closes #386 

**Changelog**
:cl:
- add: Digging dirt.

### CODE REVIEW

**Comment by Ygg01** [comment]
It's digging right into the Errors Layer

Content Client_9VIKFKBRiG

**Comment by deltanedas** [comment]
if you dont rock and stone you aint coming home

**Comment by Ygg01** [comment]
> if you dont rock and stone you aint coming home

Did I hear a Rock and Stone?

**Comment by DebugOk** [comment]
@DebugOk remember to review this :clueless:

**Comment by Ygg01** [comment]
@DebugOk did you forget :P ?

**Review by DebugOk — APPROVED** [review]
Code looks good enough. I'm sure people will complain if it doesnt work

**Pull request merged**
