### PR TITLE
Bring back the prisoner role

### LINKED ISSUE #261: Prisoners spawn at latejoin points
## Description

Prisoners join the game at latejoin points instead of their normal spawnpoints.

**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by luringens**
## About the PR
Prisoners now spawn in the prison again, even when late-joining. Re-enabled prisoner role selection.

Gladiators and Prison Guards use the same system, and as such now also always spawn on their job spawner as they used to.

## Why / Balance
Fixes #261.

## Technical details
Fixes `alwaysUseSpawner` by adding a `desiredSpawnPointType` argument to `SpawnPlayerCharacterOnStation` and `PlayerSpawningEvent`. This is checked in `SpawnPointSystem.OnSpawnPlayer(...)` to force them to spawn at their job spawner.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl:
- add: Prisoners are back!
- fix: Gladiators, prisoners and prison guards start the shift at their predesignated locations.

### CODE REVIEW

**Comment by VMSolidus** [comment]
Can you make sure to also do this for Gladiators, to make sure they correctly spawn in the Arena brig? It's been awkward on Arena for the gladiators not correctly spawning in the prison, and just being left to wander the station.

**Comment by luringens** [comment]
@evilexecutive This is tested and works for Gladiators too - I've updated the PR description to mention that 🙂

**Comment by Colin-Tel** [comment]
Exciting! There's more maps than just Edge and Tortuga that should have prisoner roles, though.

**Comment by luringens** [comment]
@Colin-Tel I've only reverted the commit I saw that commented the role numbers out, which happens to only be the two maps that were available initially on rebase. I'm not familiar enough with the role or the maps to know which ones should have prisoner roles, how many, and if they have spawners set up for them already. I figured I'd play it safe and leave that decision for the mappers to tune their maps as they see fit.

**Comment by Colin-Tel** [comment]
One moment, I can make the changes to the map prototypes for you.

**Review by Colin-Tel — APPROVED** [review]
Looks good to me, all maps that should have prisoner roles have them now.

**Comment by luringens** [comment]
Ah, they were (almost) all there already! I should have checked 😅

**Comment by Colin-Tel** [comment]
@DebugOk this should be ready for your review, looks concise enough to me 🥴

**Comment by IamVelcroboy** [comment]
> One moment, I can make the changes to the map prototypes for you.

Do you mind making corpsman on Hive [ 1, 1] as well? I guess I don't see the reason in restricting it any longer.

**Review by DebugOk — APPROVED** [review]

**Pull request merged**
