### PR TITLE
Adjusts migration file

### PR DESCRIPTION
**Pull request by IamVelcroboy**
Removes the mountain rock->asteroid rock migration. We don't want this change

### CODE REVIEW

**Review by Colin-Tel — DISMISSED** [review]
Adjusted the comments, should be good to go now.

**Comment by IamVelcroboy** [comment]
Wait, it looks like you turned them back on?

**Comment by IamVelcroboy** [comment]
We don't want Mountain Rock being replaced.

**Comment by IamVelcroboy** [comment]
Oh, I'm blind...I didn't see the first # only the ones before DeltaV. Never mind me

**Pull request merged**
