### PR TITLE
Make brass textures look nicer

### PR DESCRIPTION
**Pull request by sowelipililimute**
## About the PR
The brass sheets now have new sprites that look shinier and more brass-coloured.

## Why / Balance
The previous brass sheets have a dull and non-shiny texture, as well as a confusing indentation. They immediately stuck out to me as looking unsatisfactory.

## Media
grafik

## Requirements
- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- tweak: New sprites for brass sheets

### CODE REVIEW

**Comment by Unkn0wnGh0st333** [comment]
I find it too bright; a feature of the old one was the unusual design made it stand out compared to other resources. However, I get the previous version was too dark, but this new one is overly bright as well.

**Comment by sowelipililimute** [comment]
grafik


remember that ingame lighting is usually pretty subdued - once subjected to it & in relation to other things it isn't as nearly as bright as it is in isolation

**Comment by Unkn0wnGh0st333** [comment]
> grafik
> 
> remember that ingame lighting is usually pretty subdued - once subjected to it & in relation to other things it isn't as nearly as bright as it is in isolation

I am aware of the in-game lighting but you actually did perfect with this image cause to me it unironically looks like glass.

**Comment by sowelipililimute** [comment]
grafik

the shininess and overall colour palette has been subdued

**Comment by deltanedas** [comment]
looks much nicer now

**Comment by sowelipililimute** [comment]
i am no longer interested in contributing due to the rancid community, sorry

**Pull request closed without merging**
