### PR TITLE
Add evac shuttle: NTES Fishbowl

### PR DESCRIPTION
**Pull request by IamVelcroboy**
## About the PR
Adds The Fishbowl, a unique evac shuttle for The Hive

## Why / Balance
Is neat

## Media
awdaada

**Changelog**
:cl: Velcroboy
- add: Added the NTES-Fishbowl, a stylish new ride to Centcomm from The Hive Station

### CODE REVIEW

**Review by Axionyxx — APPROVED** [review]
Didn't check, must be fine

**Comment by deltanedas** [comment]
fishops 2

**Comment by Lyndomen** [comment]
just as i was thinking how evil diagonal walls are

**Comment by IamVelcroboy** [comment]
> just as i was thinking how evil diagonal walls are

Not walls, windows! ||but yeah, still a little evil 🧿||

**Pull request merged**
