### PR TITLE
Update Autoborg.yml

### PR DESCRIPTION
**Pull request by VMSolidus**
## About the PR
Wizden gave us a list of random borg names that are 95% LRP/NRP. Through a colaborative effort with the DeltaV Discord voice chat, we have come up with a list of replacement names that fit the Culture naming conventions. As a rule, they should be short, whymsical, inside joke names. 

## Why / Balance
I Blame The Clown

### CODE REVIEW

**Comment by TadJohnson00** [comment]
I dunno who was in the voice chat, who was consulted for approval on these names, or when this apparent meeting was held, but it looks like we're going from one list of LRP names to another list of LRP names.

**Comment by Carolyn3114** [comment]
> Wizden gave us a list of random borg names that are 95% LRP/NRP

all of these names still seem similar in terms of "roleplay", just with different references

**Comment by DebugOk** [comment]
Will not be accepted in it's current state, and no similar prs will be accepted without proper discussion

**Comment by IamVelcroboy** [comment]
image

**Pull request closed without merging**
