### PR TITLE
Make RGB Moths a thing again

### PR DESCRIPTION
**Pull request by ghost**
## About the PR

I was scrolling through Einstein Engines PRs and took a look at one that makes RGB moths a thing again. This basically reverts everything #184 does in effect - it is up for Project Manager or Game Director or Maint or just Contrib consideration. Do we want RGB moths? 
## Why / Balance

I dunno *why* we limit the colors of moths to begin with. Is this a nyano-legacy thing? This PR asks this question.
## Technical details

Changes a word in YAML.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Moths now have a bigger range of color. Existing moths may look weirder than usual.

### CODE REVIEW

**Comment by ghost** [comment]
(adding colin for review because he probably knows more since he was on the PR that this reverts in effect, and Deltanedas because they're a moth player.)

**Comment by deltanedas** [comment]
#00ff00 slurp will devastate the population

**Comment by TadJohnson00** [comment]
Was originally added to avoid bright green moths with clashing markings because they look like shit.
...I'm not sure who's going to be in charge of telling people they have to change their character designs because they're major eyesores (probably me :imcry:) but that's something we can handle later, if it becomes a problem that needs handling at all.
Approved by me when it passes all tests.

**Review by TadJohnson00 — APPROVED** [review]
Approved per last comment.

**Pull request merged**
