### PR TITLE
Revert Revert Felinid Thievery

### PR DESCRIPTION
**Pull request by WarMechanic**
Readds DeltaV-Station/Delta-v#1102
Requires 'Do Not Merge' tag - the original PR was merged with pending admin discussion.

yeah also i got a singular rounds to test out changes in-game
- i laughed at a security 'officer' cadet for having a book in their pocket
- noticed july reiter doesnt put their appraisal tool in a utility belt
- a felinid walked up to me and rummaged through my pockets
- took an isolated persons pair of shoes and promptly got yelled at
- stole stuff at round end when everyone was clumped up while concealing my identity

count tails in the bar and youll be fine

### CODE REVIEW

**Comment by Bonktrauma** [comment]
Does this mean that felinids can still steal without being noticed?

**Comment by WarMechanic** [comment]
no, passive thieving gloves has been replaced by a liter version

felinids gain the ability to peek into other players' pockets and they strip faster
unlike passive thieving gloves this stacks with thieving gloves so go crazy

**Comment by Bonktrauma** [comment]
> no, passive thieving gloves has been replaced by a liter version
> 
> felinids gain the ability to peek into other players' pockets and they strip faster

So basically,  they can steal faster but you can still see them stealing?

**Comment by WarMechanic** [comment]
yes, not being able to see items stolen was the OP dealbreaker

**Comment by TadJohnson00** [comment]
Probably needs some further balance discussion and input from administrators. Personally, I'm generally opposed to buffing thieving as I see it kill roleplay more often than it improves it, and I've always been against the "felinid = thief" stigma personally - but I'm open to hear what others have to say as well.

**Comment by WarMechanic** [comment]
any word on this?
it seems that with the latest merge, dragging items has been fixed and now felinids dragging machines has been 'nerfed' due to their lower mass (it was always supposed to be this way). provides better justification for pocket vision :)

**Comment by Axionyxx** [comment]
I don't believe features encouraging theft really fit in an MRP enviroment, and for that reason, this request will be denied entirely. Felinids should have other unique features that don't encourage LRP/NRP behaviour

Lyndomen is likely going to comment on this with a more in depth explanation later.

**Comment by WarMechanic** [comment]
Thank you

**Pull request closed without merging**
