### PR TITLE
make some ores more common on lavaland planets

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
- both planets have triple plasma
- lavaland has double diamonds
- glacier surface has double uranium

## Why / Balance
from experience plasma is much harder to find when its the reason NT came to lavaland anyway
lavaland = volcanic = pressure = diamond
glacier surface = ??? = uranium

**Changelog**
:cl:
- tweak: Plasma and diamonds are more abundant on lavaland.

### CODE REVIEW

**Comment by Avalon-Proto** [comment]
Maybe you can put Bluespace ore on both planets? I've seen it in the spawn menu, and it doesn't spawn anywhere

**Comment by deltanedas** [comment]
bluespace ore isnt a thing i think

**Comment by Avalon-Proto** [comment]
> bluespace ore isnt a thing i think

It exists as an item. And a standard pre refinery has a recipe to turn Bluespace ore into crystals. 1 ore to 1 crystal

**Comment by deltanedas** [comment]
the recipe was ported ages ago without any ore

**Comment by Avalon-Proto** [comment]
> the recipe was ported ages ago without any ore

I can promise you. Pull up your spawn menu. Look up Bluespace ore, you'll see the item. Just no ore rocks

**Comment by deltanedas** [comment]
yes if it cant be mined it doesnt matter, might as well spawn refined bluespace instead of ore item

**Review by Colin-Tel — APPROVED** [review]

**Pull request merged**
