### PR TITLE
tweak: RGB Felinids

### PR DESCRIPTION
**Pull request by DisposableCrewmember42**
## About the PR
This PR allows felinids' skin colors to be set to any RGB value.

## Why / Balance
Allows greater customization of characters. As requested by Game Directors [in Discord](https://discord.com/channels/968983104247185448/1283094866670129163/1283100648128254052).

## Technical details
Changes the skinColoration attribute to Hue for the Felinid species prototype.

## Media
None

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None

**Changelog**

:cl: DisposableCrewmember42
- tweak: Felinids' skin/fur color may now be chosen freely.

### CODE REVIEW

**Review by therealDLondon — APPROVED** [review]
As far as I know, this should work. Also GD approved.

**Comment by therealDLondon** [comment]
Ill CC @deltanedas in for a double check

**Comment by deltanedas** [comment]
im not felenid main why ping me

**Comment by therealDLondon** [comment]
I dunno is this how the skin color thing works?

**Comment by DisposableCrewmember42** [comment]
Same change as for the RGB Moth PR (#1695), works ingame as well:

https://github.com/user-attachments/assets/dce51242-50c8-43b2-9a73-a89c21efa5b5

**Comment by DisposableCrewmember42** [comment]
Also imported my felinid from Delta and he looks the same

**Pull request merged**
