### PR TITLE
Submarine Station

### PR DESCRIPTION
**Pull request by rosieposieeee**
## About the PR

image

ezgif-4-d79ac05c8d

BRRRRRR

It's a fucking submarine baby.

Submarine is a medium-to-high pop map focused around its central Hospital, with a Clinic for non-emergency checkups, a Pharmacy for those pesky Botanists to ask for kudzu-making goop, and a long-term terminal ward for those who sadly cannot be healed physically. For those that cannot be healed mentally, the brig doubles as a psych ward!

It also features a bio-dome style zoo, a labyrinth with a DANGEROUS...! minotaur, and a beautiful park with an ice skating rink. (The maprender really fucks up non-tile decal work; I swear it looks nice!) More maints silliness will probably come when I have time, but otherwise it already has a few points of interest to keep people occupied. I tried my best to fill out every department to the best of my understanding of them, but I'm very open to suggestions to make them better, as long as it doesn't make the station TOO much bigger. (I would suggest atmos mains and anyone who actually knows how singulos work to please double check that biz, I don't know anything.)

Tested and works on the current build. Still has the stock courser evac shuttle but I've already spent all week on this, I'll swap that out for something more fun later. I'll keep an eye on whatever else we add as the rebase continues that needs to be mapped, and add it in whenever I can, plus I'm sure there'll be a lot of bugs caught if we start testing.

Oh and this also includes the parkstation benches.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Submarine Station, a large map with a central hospital, and some benches for it from Parkstation.

### CODE REVIEW

**Comment by FluffiestFloof** [comment]
The first thing that jumped at me is how empty and overly long the corridors _feel_ just by looking at them. They aren't all empty but it's just the feel I get from looking at them. Probably not a bad thing per say but I wouldn't want to go from top to bottom 

Other than that,
ss (2023-10-07 at 04 37 45)
Neat labyrinth but there's not really much going in it and using way too much unnecessary reinforced walls (last I was told, they should be reserved for outside and high risk areas). Things encased in walls are not really the most interesting thing, it requires luck or meta knowledge to find. This could do with some more 'rooms' but you did say "More maints silliness will probably come"

This place in command feels a bit empty. Some chairs/couch, tables and some refreshments/coffee/snacks and have it be a resting area for command maybe? shrug
ss (2023-10-07 at 04 35 27)

**Comment by rosieposieeee** [comment]
Thanks for the feedback! Yeah, the labyrinth is more or less a placeholder, fair on the windoors, and I agree about the halls as well. I still need to do a final detailing pass, but I figured I would pr it now so I could get opinions before I finalize all the grime and stuff.

**Comment by rosieposieeee** [comment]
Submarine is now ready for review and playtesting.

**Comment by rosieposieeee** [comment]
- Fixed missing wiring everywhere mentioned and anywhere else I could find, and doubled up wiring.
- Added TEG suggestions.
- Moved Bartender spawn into their room.
- Added some scrubbers to a section in the park.
- Added connectors for the original scrubbers.
- Modified the cargo bay to allow both directions.
- Moved some of the salv stuff outside.
- Added lights where they were missing.
- Changed to Logistics signs.
- Hopefully fixed all the warp spots, added ninja bombing ones.
- Removed almost every mail thing except the simple one in the morgue. I cannot be fucked to add all those pipes.
- Fortified the armory against fireaxing in, a little more at least.
- Fixed those reinforced windows by Evac.
- Removed comms consoles I missed in some of the head rooms.
- Wired up the HoP shutter buttons I forgot to wire up previously as well as disposals.
- Fixed access on some doors.
- Removed spare ID and too much loot in Sec, and put medals back in heads' secure rooms.

Notes:
- Yeah the Labyrinth is intended to be dangerous. If it turns out to be too much of an issue they can always be removed.
- Hardsuits will not be returning to lockers. I think they ought to have their own storages. I just think it's poorly implemented that they don't have locks. I will be PRing upstream locks, and if they don't accept it for... lord knows whatever stupid reason, I will PR it here separately.
- The LV wires are disconnected between substation areas, usually per department, so that the whole station doesn't eat power from every substation.
- The little disconnected wooden disposals things are a placeholder for the elevator/futurama peoplemover things Velcro is working on. The signs and half-bench are just as a reminder of what the destination will be named.
- Kept the bar windoors cause fuck people hopping the counter.
- Yes, the head offices are intended to be accessible to anyone, hence why they are almost all attached to the hall. That's also why I haven't put anything important in those offices.

**Comment by rosieposieeee** [comment]
Oh, and I didn't change any of the maints lights. Frankly, the maints lights not only have the worlds shittiest radius but ALSO the radius is INCORRECT in the mapping view before initializing, meaning I have to keep re-initializing and re-mapping to test it out and that's a pain in the ass, which is why I made them all normal lights in the first place. I could spread them out more later but that's also a pain so... I will do it later.

**Review by DebugOk — CHANGES_REQUESTED** [review]
Why does this include #167?

**Comment by rosieposieeee** [comment]
> Why does this include #167?

Needed them to make the map until that one is merged. Will be removed when it is.

**Comment by IamVelcroboy** [comment]
Just remove the couch stuff from this PR and make it conditional not to merge until after couches. I think if you set it to be a draft, it won't run the tests and fail. (someone maybe confirm that for me)

**Comment by rosieposieeee** [comment]
I mean, it needs the couches to even build. If I remove them, nobody else will be able to test the station.

**Comment by IamVelcroboy** [comment]
@DebugOk what's a reasonable explanation that the couch PR would be reviewed/merged?

**Comment by DebugOk** [comment]
> @DebugOk what's a reasonable expectation that the couch PR would be reviewed/merged?

When Colin gets to it

**Comment by DebugOk** [comment]
@IamVelcroboy besides requiring #167, is this considered good enough otherwise?

**Comment by DEATHB4DEFEAT** [comment]
That's not a submarine..

**Comment by DebugOk** [comment]
> That's not a submarine..

:nerd_face:

**Comment by DEATHB4DEFEAT** [comment]
> > That's not a submarine..
> 
> 🤓

QuickFix2

**Comment by DebugOk** [comment]
> > > That's not a submarine..
> > 
> > 
> > 🤓
> 
> QuickFix2

death

**Comment by IamVelcroboy** [comment]
> @IamVelcroboy besides requiring #167, is this considered good enough otherwise?

I should be able to fire it up in a little bit and check it out. I haven't really gone through it yet other than what others have reviewed already.

**Comment by DebugOk** [comment]
Conflicts weren't resolved before the initial build, so this wont make it into the first build

**Comment by IamVelcroboy** [comment]
> Conflicts weren't resolved before the initial build, so this wont make it into the first build

We still have a little ways to go in terms of a review. I'll give the thumbs up when it's ready.

**Comment by DebugOk** [comment]
Closing as stale due to no activity

**Comment by IamVelcroboy** [comment]
Most of the discussion on this map has happened in Discord. But I'll send them a reminder if they want to reopen or not.

**Pull request closed without merging**
