### PR TITLE
Updates Asterisk

### PR DESCRIPTION
**Pull request by Colin-Tel**
## About the PR

Added AI slot, as well as adjusted camera layout with AI in mind. Adjusted the airlocks in Epistemics for Roboticist. Added biogenerator to botany, and added a frezon canister to the TEG room.

## Media

None
## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added Station AI to Asterisk Station.

### CODE REVIEW

**Comment by IamVelcroboy** [comment]
These are all unnamed 
image

**Comment by IamVelcroboy** [comment]
Lighting could be reduced a little 
image

**Comment by IamVelcroboy** [comment]
Concludes review. You can also go ahead and add a roboticist spawn/slot to the proto and I'll merge with these fixes

**Comment by Colin-Tel** [comment]
FUCK

**Pull request closed without merging**
