### PR TITLE
tweak: Cooked cutlets can be added to tacos too

### PR DESCRIPTION
**Pull request by DisposableCrewmember42**
## About the PR
Previously, only raw meat slices could be added to tacos. This PR adds the relevant values to the cooked meat slice prototype

## Why / Balance
This seemed like an oversight since raw cutlets could already be added, even though they aren't digestible for most species as opposed to their cooked variants ([wyci-suggestions](https://discord.com/channels/968983104247185448/1282494343776833606/1282494343776833606)).

## Technical details
Simple YAML addition specifying the sprite to be used in the taco in the same manner as for the uncooked cutlets.

## Media
image

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None

**Changelog**

:cl: DisposableCrewmember42
- tweak: You can now add cooked cutlets to tacos.

### CODE REVIEW

**Comment by Timemaster99** [comment]
This should be upstreamed since it's an upstream system

**Comment by DisposableCrewmember42** [comment]
True. Making an upstream PR.

**Comment by DisposableCrewmember42** [comment]
Looks like a food sequence overhaul was merged with upstream just yesterday: https://github.com/space-wizards/space-station-14/pull/31012

**Comment by DisposableCrewmember42** [comment]
This includes allowing cutlets

**Pull request closed without merging**
