### PR TITLE
Adds the SLP-67 "Volk"

### PR DESCRIPTION
**Pull request by TadJohnson00**
Adds the SLP-67, intended to fulfil the role of a fullsize .35 pistol, with higher capacity and improved ergonomics.

## Why / Balance

While the SLP-57 fills the role of a standard issue compact pistol, small and functional, the SLP-67 will be a more balanced option, featuring a 16-round capacity and greater accuracy - at the cost of fitting in neither pockets nor boots. Additionally, the Volk will be restricted to the Armoury, or to Logistics' catalogue.
## Technical details

n/a
## Media

image

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

n/a
**Changelog**

n/a

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Seems to be fine in terms of YAML, but the uh. I envision this is going to catch a merge conflict depending on if I merge the SLP-57 first.

**Comment by TadJohnson00** [comment]
Turns out you were right, teehee. Ready for review again.

**Review by ghost — APPROVED** [review]
Top ten reasons why I don't do two PRs adjacent to one another at once, number one: this sort of merge conflict.

**Comment by TadJohnson00** [comment]
squashing as approved

**Pull request merged**
